"""Listing 3 extracted from chapters/chapter_03_rest_architectural_style.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""hal_serializer.py - render catalog resources as HAL-like documents.

Stdlib-only and deterministic (sorted keys, fixed sample data). The point:
links are DATA emitted by the server, not strings concatenated by clients.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

BASE = "https://api.northwind-robotics.example"  # fictional host, never called


@dataclass(frozen=True)
class Link:
    href: str
    method: str = "GET"
    title: str | None = None
    templated: bool = False

    def render(self) -> dict[str, Any]:
        out: dict[str, Any] = {"href": self.href}
        if self.method != "GET":
            out["method"] = self.method
        if self.title:
            out["title"] = self.title
        if self.templated:
            out["templated"] = True
        return out


@dataclass
class HalResource:
    state: dict[str, Any]
    links: dict[str, Link | list[Link]] = field(default_factory=dict)
    embedded: dict[str, list["HalResource"]] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        doc: dict[str, Any] = dict(self.state)
        doc["_links"] = {
            rel: ([lnk.render() for lnk in link]
                  if isinstance(link, list) else link.render())
            for rel, link in sorted(self.links.items())
        }
        if self.embedded:
            doc["_embedded"] = {
                rel: [res.to_dict() for res in resources]
                for rel, resources in sorted(self.embedded.items())
            }
        return doc


def part_resource(part: dict[str, Any]) -> HalResource:
    sku = part["sku"]
    links: dict[str, Link | list[Link]] = {
        "self": Link(f"{BASE}/parts/{sku}"),
        "collection": Link(f"{BASE}/parts", title="All parts"),
        "category": Link(f"{BASE}/categories/{part['category']}"),
    }
    # Action affordances are state-dependent: only in-stock, active parts
    # advertise the restock transition. Clients need no business rule for this.
    if part["stock"] > 0 and part.get("status", "active") == "active":
        links["restock"] = Link(
            f"{BASE}/parts/{sku}/stock-adjustments",
            method="POST",
            title="Record a stock adjustment",
        )
    return HalResource(state={k: v for k, v in part.items() if k != "status"},
                       links=links)


def parts_collection(parts: list[dict[str, Any]], *, cursor: str | None,
                     next_cursor: str | None) -> HalResource:
    collection = HalResource(
        state={"count": len(parts)},
        links={"self": Link(f"{BASE}/parts" + (f"?cursor={cursor}" if cursor
                                               else ""))},
        embedded={"item": [part_resource(p) for p in parts]},
    )
    # Pagination links are the minimum viable hypermedia: the server owns the
    # cursor format, so it can change storage without breaking clients.
    if next_cursor is not None:
        collection.links["next"] = Link(f"{BASE}/parts?cursor={next_cursor}")
    return collection


CATALOG_SAMPLE: list[dict[str, Any]] = [
    {"sku": "NX-1001", "name": "Servo Motor 12V", "category": "actuators",
     "unitPrice": {"currency": "USD", "amountCents": 2599}, "stock": 140},
    {"sku": "NX-1002", "name": "LIDAR Module R2", "category": "sensors",
     "unitPrice": {"currency": "USD", "amountCents": 18999}, "stock": 32},
    {"sku": "NX-1003", "name": "Aluminum Chassis Plate", "category": "frames",
     "unitPrice": {"currency": "USD", "amountCents": 7450}, "stock": 0,
     "status": "discontinued"},
]


def main() -> None:
    document = part_resource(CATALOG_SAMPLE[0]).to_dict()
    listing = parts_collection(
        CATALOG_SAMPLE, cursor=None, next_cursor="c3RlcDoy"
    ).to_dict()
    print("--- document ---")
    print(json.dumps(document, indent=2, sort_keys=True))
    print("--- collection ---")
    print(json.dumps(listing, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
