"""Listing 1 extracted from chapters/chapter_03_rest_architectural_style.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Northwind Robotics parts catalog API (stdlib-only, offline).

Demonstrates Fielding's constraints without frameworks:
  * uniform interface  - correct methods, status codes, Allow headers
  * cacheability       - ETag, If-None-Match (304), If-Match (412),
                         Cache-Control on every representation
  * statelessness      - zero session state; every request self-contained
  * self-descriptiveness - content negotiation (JSON / CSV), Vary: Accept

Python 3.11+. Run:
    python catalog_api.py --selftest     # deterministic in-process checks
    python catalog_api.py --port 8080    # serve; try curl.exe -i ...
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import re
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger("northwind.catalog")

# --------------------------------------------------------------------------
# Domain layer (anti-corruption: storage shape != representation shape)
# --------------------------------------------------------------------------

SKU_PATTERN = re.compile(r"^[A-Z]{2}-\d{4}$")
VALID_CATEGORIES = {"actuators", "sensors", "frames", "mobility"}


class ValidationError(Exception):
    """Raised when a representation fails boundary validation (400)."""


class ConflictError(Exception):
    """Raised when a write conflicts with existing state (409)."""


@dataclass
class Part:
    sku: str
    name: str
    category: str
    unit_price_cents: int
    stock: int
    version: int = 1

    def to_representation(self) -> dict[str, Any]:
        # Published shape is designed for consumers, not for the table:
        # money is a structured object; the storage column is an int.
        return {
            "sku": self.sku,
            "name": self.name,
            "category": self.category,
            "unitPrice": {
                "currency": "USD",
                "amountCents": self.unit_price_cents,
            },
            "stock": self.stock,
        }


def parse_part(body: bytes, *, sku_from_path: str | None = None) -> Part:
    """Validate a client representation into a Part. Fail fast, specifically."""
    try:
        data = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValidationError(f"request body is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValidationError("request body must be a JSON object")

    price = data.get("unitPrice")
    if not isinstance(price, dict) or not isinstance(
        price.get("amountCents"), int
    ):
        raise ValidationError("unitPrice.amountCents (integer) is required")
    if price["amountCents"] < 0:
        raise ValidationError("unitPrice.amountCents must be >= 0")

    name = data.get("name")
    category = data.get("category")
    stock = data.get("stock")
    if not isinstance(name, str) or not name.strip():
        raise ValidationError("name (non-empty string) is required")
    if category not in VALID_CATEGORIES:
        raise ValidationError(
            f"category must be one of {sorted(VALID_CATEGORIES)}"
        )
    if not isinstance(stock, int) or stock < 0:
        raise ValidationError("stock (integer >= 0) is required")

    sku = sku_from_path or data.get("sku", "")
    if not SKU_PATTERN.match(sku):
        raise ValidationError("sku must match pattern AA-0000")
    if sku_from_path and data.get("sku") not in (None, sku_from_path):
        raise ValidationError("body sku must match the URI sku")

    return Part(
        sku=sku,
        name=name.strip(),
        category=category,
        unit_price_cents=price["amountCents"],
        stock=stock,
    )


class CatalogStore:
    """In-memory repository seeded with deterministic synthetic data."""

    def __init__(self) -> None:
        self._parts: dict[str, Part] = {}
        self._seed()

    def _seed(self) -> None:
        for part in (
            Part("NX-1001", "Servo Motor 12V", "actuators", 2599, 140),
            Part("NX-1002", "LIDAR Module R2", "sensors", 18999, 32),
            Part("NX-1003", "Aluminum Chassis Plate", "frames", 7450, 58),
            Part("NX-1004", "Omni Wheel 96mm", "mobility", 3250, 210),
        ):
            self._parts[part.sku] = part

    def list(self, category: str | None = None) -> list[Part]:
        parts = sorted(self._parts.values(), key=lambda p: p.sku)
        if category is not None:
            parts = [p for p in parts if p.category == category]
        return parts

    def get(self, sku: str) -> Part | None:
        return self._parts.get(sku)

    def create(self, part: Part) -> None:
        if part.sku in self._parts:
            raise ConflictError(f"part {part.sku} already exists")
        self._parts[part.sku] = part

    def replace(self, sku: str, part: Part) -> bool:
        """PUT semantics: full replacement. Returns True if it existed."""
        existed = sku in self._parts
        old = self._parts.get(sku)
        part.version = (old.version + 1) if old else 1
        self._parts[sku] = part
        return existed

    def delete(self, sku: str) -> bool:
        return self._parts.pop(sku, None) is not None


# --------------------------------------------------------------------------
# HTTP layer
# --------------------------------------------------------------------------

COLLECTION_RE = re.compile(r"^/parts$")
DOCUMENT_RE = re.compile(r"^/parts/(?P<sku>[A-Za-z0-9-]+)$")
JSON = "application/json"
CSV = "text/csv"


def etag_for(part: Part) -> str:
    digest = hashlib.sha256(
        json.dumps(part.to_representation(), sort_keys=True).encode()
    ).hexdigest()[:12]
    return f'"p{part.version}-{digest}"'


def negotiate(accept: str | None) -> str | None:
    """Pick the best supported media type, honoring q-values. None => 406."""
    if not accept or accept.strip() in ("", "*/*"):
        return JSON
    best: tuple[float, str] | None = None
    for item in accept.split(","):
        media, _, params = item.partition(";")
        media = media.strip().lower()
        quality = 1.0
        for param in params.split(";"):
            key, _, value = param.partition("=")
            if key.strip() == "q":
                try:
                    quality = float(value)
                except ValueError:
                    quality = 0.0
        if media in (JSON, CSV) and quality > 0:
            if best is None or quality > best[0]:
                best = (quality, media)
    return best[1] if best else None


def to_csv(reps: list[dict[str, Any]]) -> bytes:
    lines = ["sku,name,category,unit_price_cents,stock"]
    for r in reps:
        name = r["name"].replace('"', '""')
        lines.append(
            f'{r["sku"]},"{name}",{r["category"]},'
            f'{r["unitPrice"]["amountCents"]},{r["stock"]}'
        )
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


class CatalogHandler(BaseHTTPRequestHandler):
    server_version = "NorthwindCatalog/1.0"
    store: CatalogStore  # injected by make_server

    def log_message(self, fmt: str, *args: Any) -> None:
        logger.info("%s - %s", self.address_string(), fmt % args)

    # -- response helpers ---------------------------------------------------

    def _send(
        self,
        status: HTTPStatus,
        body: bytes = b"",
        content_type: str = JSON,
        extra: dict[str, str] | None = None,
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Vary", "Accept")
        for key, value in (extra or {}).items():
            self.send_header(key, value)
        self.end_headers()
        if body and self.command != "HEAD":
            self.wfile.write(body)

    def _problem(self, status: HTTPStatus, detail: str) -> None:
        body = json.dumps(
            {"title": status.phrase, "status": int(status), "detail": detail}
        ).encode()
        self._send(status, body, "application/problem+json")

    def _read_body(self) -> bytes:
        length = int(self.headers.get("Content-Length") or 0)
        return self.rfile.read(length) if length else b""

    def _check_json_content_type(self) -> None:
        ctype = (self.headers.get("Content-Type") or "").split(";")[0].strip()
        if ctype not in (JSON, "application/merge-patch+json"):
            raise UnsupportedMediaType(ctype)

    # -- method entry points ------------------------------------------------

    def do_GET(self) -> None:  # noqa: N802 (http.server naming)
        self._dispatch("GET")

    def do_HEAD(self) -> None:  # noqa: N802
        self._dispatch("GET")

    def do_POST(self) -> None:  # noqa: N802
        self._dispatch("POST")

    def do_PUT(self) -> None:  # noqa: N802
        self._dispatch("PUT")

    def do_PATCH(self) -> None:  # noqa: N802
        self._dispatch("PATCH")

    def do_DELETE(self) -> None:  # noqa: N802
        self._dispatch("DELETE")

    def do_OPTIONS(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        allowed = (
            "GET, HEAD, POST, OPTIONS"
            if COLLECTION_RE.match(parsed.path)
            else "GET, HEAD, PUT, PATCH, DELETE, OPTIONS"
        )
        self._send(HTTPStatus.NO_CONTENT, extra={"Allow": allowed})

    # -- router ---------------------------------------------------------------

    def _dispatch(self, method: str) -> None:
        parsed = urlparse(self.path)
        path = parsed.path.rstrip("/") or "/"
        query = parse_qs(parsed.query)
        doc = DOCUMENT_RE.match(path)
        try:
            if COLLECTION_RE.match(path):
                self._collection(method, query)
            elif doc:
                self._document(method, doc.group("sku"))
            else:
                self._problem(HTTPStatus.NOT_FOUND, f"no resource at {path}")
        except ValidationError as exc:
            self._problem(HTTPStatus.BAD_REQUEST, str(exc))
        except ConflictError as exc:
            self._problem(HTTPStatus.CONFLICT, str(exc))
        except UnsupportedMediaType as exc:
            self._problem(
                HTTPStatus.UNSUPPORTED_MEDIA_TYPE,
                f"unsupported media type: {exc}",
            )
        except Exception:  # never leak internals over the wire
            logger.exception("unhandled error processing %s %s", method, path)
            self._problem(HTTPStatus.INTERNAL_SERVER_ERROR, "internal error")

    def _reject(self, allowed: str) -> None:
        body = json.dumps(
            {
                "title": "Method Not Allowed",
                "status": int(HTTPStatus.METHOD_NOT_ALLOWED),
                "detail": "method not allowed on this resource",
            }
        ).encode()
        self._send(
            HTTPStatus.METHOD_NOT_ALLOWED,
            body,
            "application/problem+json",
            extra={"Allow": allowed},
        )

    # -- /parts (collection) --------------------------------------------------

    def _collection(self, method: str, query: dict[str, list[str]]) -> None:
        if method == "GET":
            category = query.get("category", [None])[0]
            reps = [p.to_representation() for p in self.store.list(category)]
            media = negotiate(self.headers.get("Accept"))
            if media is None:
                self._problem(
                    HTTPStatus.NOT_ACCEPTABLE, "supported: application/json, text/csv"
                )
                return
            body = (
                json.dumps({"parts": reps, "count": len(reps)}).encode()
                if media == JSON
                else to_csv(reps)
            )
            self._send(HTTPStatus.OK, body, media)
        elif method == "POST":
            self._check_json_content_type()
            part = parse_part(self._read_body())
            self.store.create(part)
            body = json.dumps(part.to_representation()).encode()
            self._send(
                HTTPStatus.CREATED,
                body,
                extra={
                    "Location": f"/parts/{part.sku}",
                    "ETag": etag_for(part),
                },
            )
        else:
            self._reject("GET, HEAD, POST, OPTIONS")

    # -- /parts/{sku} (document) ------------------------------------------------

    def _document(self, method: str, sku: str) -> None:
        part = self.store.get(sku)
        if method == "GET":  # HEAD is dispatched here with body suppressed
            if part is None:
                self._problem(HTTPStatus.NOT_FOUND, f"no part with sku {sku!r}")
                return
            etag = etag_for(part)
            if self.headers.get("If-None-Match") == etag:
                self._send(HTTPStatus.NOT_MODIFIED, extra={"ETag": etag})
                return
            media = negotiate(self.headers.get("Accept"))
            if media is None:
                self._problem(HTTPStatus.NOT_ACCEPTABLE, "supported: json, csv")
                return
            rep = part.to_representation()
            body = (
                json.dumps(rep).encode() if media == JSON else to_csv([rep])
            )
            self._send(HTTPStatus.OK, body, media, extra={"ETag": etag})
        elif method == "PUT":
            self._check_json_content_type()
            if part and self.headers.get("If-Match") not in (None, etag_for(part)):
                self._problem(
                    HTTPStatus.PRECONDITION_FAILED,
                    "If-Match does not match current ETag; re-read and retry",
                )
                return
            new_part = parse_part(self._read_body(), sku_from_path=sku)
            existed = self.store.replace(sku, new_part)
            etag = etag_for(self.store.get(sku))  # type: ignore[arg-type]
            status = HTTPStatus.OK if existed else HTTPStatus.CREATED
            extra = {"ETag": etag}
            if not existed:
                extra["Location"] = f"/parts/{sku}"
            self._send(status, b"", extra=extra)
        elif method == "PATCH":
            if part is None:
                self._problem(HTTPStatus.NOT_FOUND, f"no part with sku {sku!r}")
                return
            ctype = (self.headers.get("Content-Type") or "").split(";")[0]
            if ctype.strip() != "application/merge-patch+json":
                raise UnsupportedMediaType(ctype or "<missing>")
            patch = json.loads(self._read_body().decode("utf-8") or "{}")
            merged = merge_patch(part.to_representation(), patch)
            updated = parse_part(
                json.dumps(merged).encode(), sku_from_path=sku
            )
            self.store.replace(sku, updated)  # bumps the version counter
            stored = self.store.get(sku)
            assert stored is not None  # just written by replace()
            body = json.dumps(stored.to_representation()).encode()
            self._send(HTTPStatus.OK, body, extra={"ETag": etag_for(stored)})
        elif method == "DELETE":
            if self.store.delete(sku):
                self._send(HTTPStatus.NO_CONTENT)
            else:
                self._problem(HTTPStatus.NOT_FOUND, f"no part with sku {sku!r}")
        else:
            self._reject("GET, HEAD, PUT, PATCH, DELETE, OPTIONS")


class UnsupportedMediaType(Exception):
    """Raised when Content-Type is not one the resource understands (415)."""


def merge_patch(target: dict[str, Any], patch: dict[str, Any]) -> dict[str, Any]:
    """RFC 7386 JSON Merge Patch: merge keys; null deletes the key."""
    result = dict(target)
    for key, value in patch.items():
        if value is None:
            result.pop(key, None)
        elif isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge_patch(result[key], value)
        else:
            result[key] = value
    return result


def make_server(port: int) -> ThreadingHTTPServer:
    CatalogHandler.store = CatalogStore()
    return ThreadingHTTPServer(("127.0.0.1", port), CatalogHandler)


def run_selftest() -> None:
    """Deterministic in-process checks; no sockets, no network."""
    from http.client import HTTPConnection
    import threading

    server = make_server(0)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    host, port = server.server_address
    conn = HTTPConnection(host, port, timeout=5)
    try:
        conn.request("GET", "/parts/NX-1001")
        resp = conn.getresponse()
        assert resp.status == 200 and resp.getheader("ETag")
        etag = resp.getheader("ETag")
        resp.read()

        conn.request("GET", "/parts/NX-1001", headers={"If-None-Match": etag})
        assert conn.getresponse().status == 304

        conn.request("GET", "/parts/NOPE")
        assert conn.getresponse().status == 404

        conn.request(
            "POST",
            "/parts",
            body=json.dumps({
                "sku": "NX-1005", "name": "Torque Wrench Arm",
                "category": "actuators",
                "unitPrice": {"currency": "USD", "amountCents": 9900},
                "stock": 12,
            }),
            headers={"Content-Type": "application/json"},
        )
        resp = conn.getresponse()
        assert resp.status == 201
        assert resp.getheader("Location") == "/parts/NX-1005"
        resp.read()

        conn.request("DELETE", "/parts/NX-1005")
        assert conn.getresponse().status == 204
        conn.request("DELETE", "/parts/NX-1005")
        assert conn.getresponse().status == 404

        conn.request(
            "GET", "/parts", headers={"Accept": "application/xml"}
        )
        assert conn.getresponse().status == 406
        print("selftest: all checks passed (200/304/404/201/204/404/406)")
    finally:
        conn.close()
        server.shutdown()
        server.server_close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    if args.selftest:
        run_selftest()
    else:
        logger.info("serving Northwind parts catalog on 127.0.0.1:%d", args.port)
        make_server(args.port).serve_forever()
