"""Listing 2 extracted from chapters/chapter_03_rest_architectural_style.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""uri_lint.py - enforce the URI design grammar on a route table.

Usage (PowerShell):
    python uri_lint.py                    # lint the embedded sample table
    python uri_lint.py routes.json        # JSON route table (stdlib only)
    python uri_lint.py routes.yaml        # YAML route table (needs pyyaml)

Exit code 0 = clean, 1 = violations found, 2 = input could not be parsed.
Deterministic: findings are sorted; no clock, no network, no randomness.
"""
from __future__ import annotations

import json
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger("northwind.uri_lint")

MAX_NESTING_DEPTH = 2  # collection/document pairs, per style guide

# Verb lexicon: segments that signal RPC-style tunneling (rule R001).
VERB_LEXICON = {
    "get", "fetch", "read", "list", "query", "search", "find",
    "create", "add", "insert", "register", "make", "new",
    "update", "edit", "modify", "change", "set", "patch",
    "delete", "remove", "destroy", "purge",
    "do", "process", "execute", "run", "submit", "trigger",
    "calculate", "compute", "export", "import", "sync",
}

KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
PARAM_RE = re.compile(r"^\{[a-zA-Z][a-zA-Z0-9_]*\}$")


@dataclass(frozen=True)
class Finding:
    rule: str
    path: str
    message: str

    def render(self) -> str:
        return f"[{self.rule}] {self.path}: {self.message}"


def static_segments(path: str) -> list[str]:
    """Path segments minus template parameters like {sku}."""
    return [s for s in path.split("/") if s and not PARAM_RE.match(s)]


def lint_path(path: str) -> list[Finding]:
    findings: list[Finding] = []

    if path != "/" and path.endswith("/"):                       # R005
        findings.append(Finding(
            "R005", path,
            "trailing slash creates a duplicate URI; use the bare form "
            "and 301-redirect the slashed form",
        ))

    segments = [s for s in path.split("/") if s]
    for seg in segments:
        if PARAM_RE.match(seg):
            continue
        if seg.lower() in VERB_LEXICON:                          # R001
            findings.append(Finding(
                "R001", path,
                f"verb {seg!r} in path; the HTTP method supplies the verb - "
                f"reify the action as a resource instead",
            ))
        if not KEBAB_RE.match(seg):                              # R004
            findings.append(Finding(
                "R004", path,
                f"segment {seg!r} is not lowercase kebab-case "
                f"(no camelCase, snake_case, or mixed case)",
            ))

    depth = (len(segments) + 1) // 2                             # R002
    if depth > MAX_NESTING_DEPTH:
        findings.append(Finding(
            "R002", path,
            f"nesting depth {depth} exceeds {MAX_NESTING_DEPTH}; "
            f"prefer a top-level collection with a query filter",
        ))
    return findings


def lint_pluralization(paths: list[str]) -> list[Finding]:
    """R003: collection segments must be consistently plural."""
    singular: list[str] = []
    plural: list[str] = []
    for path in paths:
        segs = static_segments(path)
        if not segs:
            continue
        first = segs[0]
        (plural if first.endswith("s") else singular).append(first)
    if singular and plural:
        return [Finding(
            "R003", ", ".join(sorted(set(singular))),
            "singular collection segment(s) mixed with plural "
            f"{sorted(set(plural))}; pick plural everywhere",
        )]
    return []


def lint_route_table(table: dict[str, Any]) -> list[Finding]:
    paths = table.get("paths")
    if not isinstance(paths, dict) or not paths:
        raise ValueError("route table must contain a non-empty 'paths' object")
    findings: list[Finding] = []
    for path in paths:
        if not isinstance(path, str) or not path.startswith("/"):
            raise ValueError(f"invalid path key: {path!r}")
        findings.extend(lint_path(path))
    findings.extend(lint_pluralization(list(paths)))
    return sorted(findings, key=lambda f: (f.path, f.rule))


def load_table(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if path.suffix in (".yaml", ".yml"):
        try:
            import yaml  # type: ignore[import-untyped]
        except ImportError as exc:
            raise RuntimeError(
                "YAML input requires pyyaml: pip install pyyaml"
            ) from exc
        data = yaml.safe_load(text)
    else:
        data = json.loads(text)
    if not isinstance(data, dict):
        raise ValueError("route table must be a JSON/YAML object")
    return data


SAMPLE_TABLE: dict[str, Any] = {
    "paths": {
        "/parts": {},
        "/parts/{sku}": {},
        "/parts/{sku}/restock": {},    # action-like; reify as stock-adjustments
        "/getPart": {},                # R003 + R004 (getPart: camelCase, singular)
        "/warehouses/{wid}/stock/{sku}/history": {},  # R002: depth 3
        "/purchaseOrders/{id}": {},            # R004: camelCase
        "/suppliers/": {},                     # R005: trailing slash
    }
}


def main(argv: list[str]) -> int:
    logging.basicConfig(level=logging.WARNING, format="%(levelname)s %(message)s")
    if len(argv) > 1:
        try:
            table = load_table(Path(argv[1]))
        except (OSError, ValueError, RuntimeError,
                json.JSONDecodeError) as exc:
            logger.error("cannot load route table: %s", exc)
            return 2
    else:
        table = SAMPLE_TABLE

    findings = lint_route_table(table)
    for finding in findings:
        print(finding.render())
    print(f"\n{len(findings)} violation(s) in {len(table['paths'])} path(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
