"""Listing 5 extracted from chapters/chapter_09_versioning_evolution.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Retirement-readiness report generator (Chapter 9, Listing 9.5).

Reads a JSON-lines access log (one event per line: ts, path, consumer) and
reports per-version usage share, distinct consumers, and monthly trend, then
emits a retirement verdict against the chapter's threshold policy.

Usage (PowerShell):
    python retirement_report.py --demo            # embedded fixture
    python retirement_report.py access_log.jsonl  # your own export
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

RETIRE_SHARE_THRESHOLD = 0.05  # retire when v1 < 5% of catalog traffic...

DEMO_LOG = """\
{"ts": "2026-05-04T09:13:00Z", "path": "/v1/catalog/WR-1042", "consumer": "partner-acme"}
{"ts": "2026-05-05T10:01:00Z", "path": "/v2/catalog", "consumer": "storefront-web"}
{"ts": "2026-05-06T11:40:00Z", "path": "/v2/catalog/WR-2210", "consumer": "storefront-web"}
{"ts": "2026-06-02T09:00:00Z", "path": "/v2/catalog", "consumer": "storefront-web"}
{"ts": "2026-06-03T09:05:00Z", "path": "/v2/catalog", "consumer": "partner-globex"}
{"ts": "2026-06-04T12:31:00Z", "path": "/v2/catalog/WR-4100", "consumer": "warehouse-wms"}
{"ts": "2026-06-05T15:10:00Z", "path": "/v2/catalog", "consumer": "storefront-web"}
{"ts": "2026-07-01T09:00:00Z", "path": "/v2/catalog", "consumer": "storefront-web"}
{"ts": "2026-07-02T09:10:00Z", "path": "/v2/catalog/WR-3307", "consumer": "partner-globex"}
{"ts": "2026-07-03T10:20:00Z", "path": "/v2/catalog", "consumer": "warehouse-wms"}
{"ts": "2026-07-04T11:00:00Z", "path": "/v2/catalog", "consumer": "mobile-ios-4.0"}
{"ts": "2026-07-05T13:45:00Z", "path": "/v2/catalog/WR-1042", "consumer": "storefront-web"}
{"ts": "2026-08-02T08:30:00Z", "path": "/v2/catalog", "consumer": "storefront-web"}
{"ts": "2026-08-02T09:00:00Z", "path": "/v2/catalog", "consumer": "partner-globex"}
{"ts": "2026-08-03T09:30:00Z", "path": "/v2/catalog/WR-4100", "consumer": "warehouse-wms"}
{"ts": "2026-08-04T10:00:00Z", "path": "/v2/catalog", "consumer": "mobile-ios-4.0"}
{"ts": "2026-08-05T11:15:00Z", "path": "/v2/catalog/WR-2210", "consumer": "storefront-web"}
{"ts": "2026-08-06T12:00:00Z", "path": "/v2/catalog", "consumer": "partner-globex"}
{"ts": "2026-08-07T12:30:00Z", "path": "/v2/catalog/WR-3307", "consumer": "warehouse-wms"}
{"ts": "2026-08-08T13:00:00Z", "path": "/v2/catalog", "consumer": "mobile-ios-4.0"}
{"ts": "2026-08-09T14:20:00Z", "path": "/v2/catalog/WR-1042", "consumer": "storefront-web"}
"""


def path_version(path: str) -> str | None:
    for prefix in ("/v1/", "/v2/"):
        if path.startswith(prefix):
            return prefix.strip("/")
    return None


def build_report(lines: list[str]) -> str:
    total: dict[str, int] = defaultdict(int)
    consumers: dict[str, set[str]] = defaultdict(set)
    monthly: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))

    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        event = json.loads(raw)
        version = path_version(str(event["path"]))
        if version is None:
            continue  # unversioned traffic is out of scope for this report
        total[version] += 1
        consumers[version].add(str(event["consumer"]))
        monthly[str(event["ts"])[:7]][version] += 1

    grand_total = sum(total.values())
    if grand_total == 0:
        return "No versioned traffic found; nothing to report."

    out = ["RETIREMENT-READINESS REPORT -- Northwind Robotics Catalog API",
           "=" * 62, f"Total versioned requests: {grand_total}", ""]
    for version in sorted(total):
        share = total[version] / grand_total
        out.append(f"{version}: {total[version]:>4} requests "
                   f"({share:6.1%}), {len(consumers[version])} consumer(s): "
                   f"{sorted(consumers[version])}")
    out += ["", "Monthly trend (v1 share): "]
    for month in sorted(monthly):
        m = monthly[month]
        month_total = sum(m.values())
        out.append(f"  {month}: v1={m.get('v1', 0):>2} v2={m.get('v2', 0):>2} "
                   f"(v1 share {m.get('v1', 0) / month_total:6.1%})")

    months = sorted(monthly)
    first = monthly[months[0]]
    last = monthly[months[-1]]
    first_share = first.get("v1", 0) / sum(first.values())
    last_share = last.get("v1", 0) / sum(last.values())
    declining = last_share <= first_share
    v1_share = total.get("v1", 0) / grand_total

    out += ["", "Verdict:"]
    if v1_share < RETIRE_SHARE_THRESHOLD and declining:
        out.append(f"  v1 share {v1_share:.1%} < {RETIRE_SHARE_THRESHOLD:.0%} "
                   "and declining: SCHEDULE SUNSET BROWNOUTS, confirm the "
                   f"remaining consumer(s) {sorted(consumers.get('v1', []))}, "
                   "then retire on the published date.")
    else:
        out.append(f"  v1 share {v1_share:.1%} (declining={declining}): KEEP "
                   "v1 RUNNING; continue migration campaign and re-evaluate "
                   "next month.")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("logfile", type=Path, nargs="?",
                        help="JSON-lines access log export")
    parser.add_argument("--demo", action="store_true",
                        help="use the embedded deterministic fixture")
    args = parser.parse_args(argv)

    if args.demo or args.logfile is None:
        lines = DEMO_LOG.splitlines()
    else:
        lines = args.logfile.read_text(encoding="utf-8").splitlines()
    print(build_report(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
