"""Listing 1 extracted from chapters/chapter_09_versioning_evolution.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Dual-serving Catalog API (v1 + v2) for Northwind Robotics.

Chapter 9, Listing 9.1 -- one v2 domain model serves two public versions.
The v1 surface is a pure adapter over the v2 model and carries RFC 8594 /
RFC 9745 deprecation metadata. Offline: run the module for a deterministic
demonstration via FastAPI's TestClient.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone

from fastapi import FastAPI, Request, Response
from fastapi.responses import JSONResponse
from fastapi.testclient import TestClient
from pydantic import BaseModel, Field

# --- Deprecation policy constants (dates are fixed => deterministic output) ---
DEPRECATED_AT = datetime(2026, 9, 1, tzinfo=timezone.utc)
SUNSET_AT = datetime(2027, 5, 1, tzinfo=timezone.utc)
DEPRECATION_HEADER = f"@{int(DEPRECATED_AT.timestamp())}"          # RFC 9745
SUNSET_HEADER = "Sat, 01 May 2027 00:00:00 GMT"                    # RFC 8594
MIGRATION_GUIDE = "https://docs.northwind-robotics.example/catalog/migration"


# --- Single source of truth: the v2 domain model ------------------------------
class Category(str, enum.Enum):
    """Open enum: consumers MUST tolerate unknown values (fallback rule)."""

    ACTUATOR = "actuator"
    SENSOR = "sensor"
    CONTROLLER = "controller"
    BATTERY = "battery"  # added mid-lifecycle; safe only because enum is open


class PartV2(BaseModel):
    """Current (v2) domain model. All business logic speaks only this type."""

    part_id: str
    sku: str
    name: str
    unit_price_cents: int = Field(ge=0)
    currency: str = "USD"
    category: Category
    stock: int = Field(ge=0)
    tags: list[str] = []
    status: str = "active"


class PartV1(BaseModel):
    """Legacy (v1) wire contract, frozen forever: float-dollar price, bool stock."""

    id: str
    sku: str
    name: str
    price: float
    category: str
    in_stock: bool


CATALOG: dict[str, PartV2] = {
    p.part_id: p
    for p in [
        PartV2(part_id="WR-1042", sku="SRV-T450", name="Torque Servo T450",
               unit_price_cents=12999, category=Category.ACTUATOR, stock=34,
               tags=["servo", "high-torque"]),
        PartV2(part_id="WR-2210", sku="LDR-M90", name="Lidar Module M90",
               unit_price_cents=45900, category=Category.SENSOR, stock=0,
               tags=["lidar", "navigation"]),
        PartV2(part_id="WR-3307", sku="CTL-AX12", name="Axis Controller AX12",
               unit_price_cents=8900, category=Category.CONTROLLER, stock=112,
               tags=["controller", "can-bus"]),
        PartV2(part_id="WR-4100", sku="BAT-LP38", name="LiPo Pack LP38",
               unit_price_cents=15450, category=Category.BATTERY, stock=57,
               tags=["battery", "38wh"]),
    ]
}


# --- Anti-corruption layer: v2 domain model -> frozen v1 wire contract --------
def to_v1(part: PartV2) -> PartV1:
    """Pure, total translation: every v1 field is derivable from the v2 model."""

    return PartV1(
        id=part.part_id,
        sku=part.sku,
        name=part.name,
        price=round(part.unit_price_cents / 100, 2),
        category=part.category.value,
        in_stock=part.stock > 0,
    )


def lookup(part_id: str) -> PartV2 | None:
    return CATALOG.get(part_id.upper())


app = FastAPI(title="Northwind Robotics Catalog API", version="2.0.0")


@app.middleware("http")
async def deprecation_middleware(request: Request, call_next) -> Response:
    """Stamp RFC 8594/9745 lifecycle metadata on every v1 response."""

    response: Response = await call_next(request)
    if request.url.path.startswith("/v1/"):
        response.headers["Deprecation"] = DEPRECATION_HEADER
        response.headers["Sunset"] = SUNSET_HEADER
        response.headers["Link"] = (
            f'<{MIGRATION_GUIDE}>; rel="deprecation", '
            f'</v2/catalog>; rel="successor-version"'
        )
    return response


def not_found(version: str, part_id: str) -> JSONResponse:
    return JSONResponse(
        status_code=404,
        content={"type": "about:blank", "title": "Part not found",
                 "status": 404, "detail": f"no part '{part_id}' in {version}"},
    )


# --- v1 surface (deprecated): adapter over the core ---------------------------
@app.get("/v1/catalog", response_model=list[PartV1])
def list_catalog_v1() -> list[PartV1]:
    return [to_v1(p) for p in CATALOG.values()]


@app.get("/v1/catalog/{part_id}", response_model=PartV1)
def get_part_v1(part_id: str) -> PartV1 | JSONResponse:
    part = lookup(part_id)
    return to_v1(part) if part else not_found("v1", part_id)


# --- v2 surface (current): native domain model --------------------------------
@app.get("/v2/catalog", response_model=list[PartV2])
def list_catalog_v2() -> list[PartV2]:
    return list(CATALOG.values())


@app.get("/v2/catalog/{part_id}", response_model=PartV2)
def get_part_v2(part_id: str) -> PartV2 | JSONResponse:
    part = lookup(part_id)
    return part if part else not_found("v2", part_id)


def demo() -> None:
    client = TestClient(app)
    r1 = client.get("/v1/catalog/WR-1042")
    print("== v1 (deprecated) ==")
    print("Deprecation:", r1.headers.get("Deprecation"))
    print("Sunset:     ", r1.headers.get("Sunset"))
    print("Link:       ", r1.headers.get("Link"))
    print("Body:       ", r1.json())
    r2 = client.get("/v2/catalog/WR-1042")
    print("\n== v2 (current) ==")
    print("Deprecation:", r2.headers.get("Deprecation"))
    print("Body:       ", r2.json())
    r3 = client.get("/v2/catalog/NOPE-1")
    print("\n== unknown part ==", r3.status_code, r3.json()["detail"])


if __name__ == "__main__":
    demo()
