"""Listing 3 extracted from chapters/chapter_09_versioning_evolution.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Media-type version negotiation (Chapter 9, Listing 9.3).

Parses Accept headers carrying vendor media types with a `version=N`
parameter, honors q-values, and returns None (-> HTTP 406) when no supported
version matches. Run the module for a deterministic negotiation table plus a
TestClient demonstration. Stdlib + FastAPI.
"""

from __future__ import annotations

from dataclasses import dataclass

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.testclient import TestClient

VENDOR_TYPE = "application/vnd.northwind.catalog+json"
SUPPORTED_VERSIONS = (1, 2)
DEFAULT_VERSION = 2

PART_V1 = {"id": "WR-1042", "sku": "SRV-T450", "name": "Torque Servo T450",
           "price": 129.99, "category": "actuator", "in_stock": True}
PART_V2 = {"part_id": "WR-1042", "sku": "SRV-T450", "name": "Torque Servo T450",
           "unit_price_cents": 12999, "currency": "USD",
           "category": "actuator", "stock": 34}


@dataclass(frozen=True)
class MediaRange:
    media_type: str
    q: float
    version: int | None
    order: int


def parse_accept(header: str | None) -> list[MediaRange]:
    """Parse an Accept header into q-sorted media ranges (stable on ties)."""

    if not header:
        return [MediaRange("*/*", 1.0, None, 0)]
    ranges: list[MediaRange] = []
    for order, raw in enumerate(header.split(",")):
        tokens = [t.strip() for t in raw.split(";")]
        media_type = tokens[0].lower()
        q, version = 1.0, None
        for param in tokens[1:]:
            if "=" not in param:
                continue
            key, _, value = param.partition("=")
            key, value = key.strip().lower(), value.strip().strip('"')
            if key == "q":
                try:
                    q = float(value)
                except ValueError:
                    q = 0.0
            elif key == "version":
                try:
                    version = int(value)
                except ValueError:
                    version = None
        ranges.append(MediaRange(media_type, q, version, order))
    acceptable = [r for r in ranges if r.q > 0.0]
    return sorted(acceptable, key=lambda r: (-r.q, r.order))


def negotiate(
    header: str | None,
    supported: tuple[int, ...] = SUPPORTED_VERSIONS,
    default: int = DEFAULT_VERSION,
) -> int | None:
    """Return the best supported version for the header, or None (-> 406).

    A vendor range with an explicit version matches only that version; a bare
    vendor type, application/json, or */* maps to the server default.
    """

    best_version: int | None = None
    best_q = -1.0
    for r in parse_accept(header):
        if r.media_type == VENDOR_TYPE and r.version is not None:
            if r.version in supported and r.q > best_q:
                best_version, best_q = r.version, r.q
        elif r.media_type in (VENDOR_TYPE, "application/json", "*/*"):
            if r.q > best_q:
                best_version, best_q = default, r.q
    return best_version


app = FastAPI(title="Northwind Robotics Catalog (media-type versioned)")


@app.get("/catalog/{part_id}")
def get_part(part_id: str, request: Request) -> JSONResponse:
    version = negotiate(request.headers.get("accept"))
    if version is None:
        return JSONResponse(
            status_code=406,
            content={"type": "about:blank", "title": "Not Acceptable",
                     "status": 406,
                     "detail": "supported: " + ", ".join(
                         f"{VENDOR_TYPE}; version={v}"
                         for v in SUPPORTED_VERSIONS)},
            headers={"Link": f'</catalog>; rel="versions"'},
        )
    body = PART_V1 if version == 1 else PART_V2
    return JSONResponse(
        content=body,
        media_type=f"{VENDOR_TYPE}; version={version}",
        headers={"Vary": "Accept"},
    )


def demo() -> None:
    cases = [
        None,
        "application/json",
        "application/vnd.northwind.catalog+json; version=1",
        "application/vnd.northwind.catalog+json; version=2",
        "application/vnd.northwind.catalog+json; version=1;q=0.4, "
        "application/vnd.northwind.catalog+json; version=2;q=0.9",
        "application/vnd.northwind.catalog+json; version=3",
        "application/xml",
    ]
    print(f"{'Accept header':<78} -> version")
    for header in cases:
        print(f"{str(header):<78} -> {negotiate(header)}")
    client = TestClient(app)
    r = client.get("/catalog/WR-1042",
                   headers={"Accept": f"{VENDOR_TYPE}; version=3"})
    print("\n406 case:", r.status_code, r.json()["detail"])


if __name__ == "__main__":
    demo()
