"""Listing 2 extracted from chapters/chapter_09_versioning_evolution.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""OpenAPI breaking-change gate (Chapter 9, Listing 9.2).

Classifies the delta between an OLD and a NEW OpenAPI 3.x YAML spec as
BREAKING or NON-BREAKING and exits non-zero when any breaking change exists.
Stdlib + PyYAML only. Inline schemas assumed (no $ref resolution).

Usage (PowerShell):
    python openapi_diff_gate.py catalog_v1.yaml catalog_v2.yaml
"""

from __future__ import annotations

import argparse
import enum
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

HTTP_METHODS = frozenset(
    {"get", "put", "post", "delete", "patch", "head", "options", "trace"}
)


class Severity(enum.Enum):
    BREAKING = "BREAKING"
    NON_BREAKING = "NON-BREAKING"


@dataclass(frozen=True)
class Change:
    severity: Severity
    location: str
    message: str

    def render(self) -> str:
        return f"[{self.severity.value:>12}] {self.location}: {self.message}"


def _operations(path_item: dict[str, Any]) -> dict[str, Any]:
    return {m: op for m, op in path_item.items() if m.lower() in HTTP_METHODS}


def _diff_schema(
    old: dict[str, Any],
    new: dict[str, Any],
    location: str,
    direction: str,  # "request" or "response"
    changes: list[Change],
) -> None:
    old_props: dict[str, Any] = old.get("properties", {}) or {}
    new_props: dict[str, Any] = new.get("properties", {}) or {}
    new_required = set(new.get("required", []) or [])

    for name in old_props:
        if name not in new_props:
            changes.append(Change(
                Severity.BREAKING, location,
                f"property '{name}' removed from {direction} schema"))

    for name, new_prop in new_props.items():
        if name not in old_props:
            if direction == "request" and name in new_required:
                changes.append(Change(
                    Severity.BREAKING, location,
                    f"required request property '{name}' added"))
            else:
                changes.append(Change(
                    Severity.NON_BREAKING, location,
                    f"optional {direction} property '{name}' added"))
            continue
        old_type = old_props[name].get("type")
        new_type = new_prop.get("type")
        if old_type != new_type:
            changes.append(Change(
                Severity.BREAKING, location,
                f"property '{name}' type changed {old_type!r} -> {new_type!r}"))
        elif old_type == "object":
            _diff_schema(old_props[name], new_prop,
                         f"{location}.{name}", direction, changes)
        elif old_type == "array":
            _diff_schema(old_props[name].get("items", {}) or {},
                         new_prop.get("items", {}) or {},
                         f"{location}.{name}[]", direction, changes)
        old_enum = old_props[name].get("enum")
        new_enum = new_prop.get("enum")
        if old_enum and new_enum:
            removed = set(old_enum) - set(new_enum)
            if removed:
                changes.append(Change(
                    Severity.BREAKING, location,
                    f"enum value(s) removed from '{name}': {sorted(removed)}"))
            added = set(new_enum) - set(old_enum)
            if added:
                changes.append(Change(
                    Severity.NON_BREAKING, location,
                    f"enum value(s) added to '{name}': {sorted(added)} "
                    "(safe only if the enum is documented as open)"))


def _json_schema(media: dict[str, Any]) -> dict[str, Any]:
    content = media.get("content", {}) or {}
    return (content.get("application/json", {}) or {}).get("schema", {}) or {}


def _diff_operation(
    old: dict[str, Any],
    new: dict[str, Any],
    location: str,
    changes: list[Change],
) -> None:
    old_body = _json_schema(old.get("requestBody", {}) or {})
    new_body = _json_schema(new.get("requestBody", {}) or {})
    if new_body and old_body:
        _diff_schema(old_body, new_body, f"{location} requestBody",
                     "request", changes)
    elif new_body and not old_body and new_body.get("required"):
        changes.append(Change(
            Severity.BREAKING, location,
            "request body with required properties introduced"))

    old_responses: dict[str, Any] = old.get("responses", {}) or {}
    new_responses: dict[str, Any] = new.get("responses", {}) or {}
    for code in old_responses:
        if code not in new_responses:
            changes.append(Change(
                Severity.BREAKING, location,
                f"response status '{code}' removed"))
    for code in new_responses:
        if code not in old_responses:
            changes.append(Change(
                Severity.NON_BREAKING, location,
                f"response status '{code}' added"))
    for code in old_responses.keys() & new_responses.keys():
        _diff_schema(_json_schema(old_responses[code]),
                     _json_schema(new_responses[code]),
                     f"{location} response {code}", "response", changes)


def diff_specs(old: dict[str, Any], new: dict[str, Any]) -> list[Change]:
    changes: list[Change] = []
    old_paths: dict[str, Any] = old.get("paths", {}) or {}
    new_paths: dict[str, Any] = new.get("paths", {}) or {}

    for path in old_paths:
        if path not in new_paths:
            changes.append(Change(Severity.BREAKING, path, "path removed"))
    for path in new_paths:
        if path not in old_paths:
            changes.append(Change(Severity.NON_BREAKING, path, "path added"))

    for path in old_paths.keys() & new_paths.keys():
        old_ops = _operations(old_paths[path])
        new_ops = _operations(new_paths[path])
        for method in old_ops:
            if method not in new_ops:
                changes.append(Change(
                    Severity.BREAKING, f"{method.upper()} {path}",
                    "operation removed"))
        for method in new_ops:
            if method not in old_ops:
                changes.append(Change(
                    Severity.NON_BREAKING, f"{method.upper()} {path}",
                    "operation added"))
        for method in old_ops.keys() & new_ops.keys():
            _diff_operation(old_ops[method], new_ops[method],
                            f"{method.upper()} {path}", changes)
    return changes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("old_spec", type=Path)
    parser.add_argument("new_spec", type=Path)
    args = parser.parse_args(argv)

    old = yaml.safe_load(args.old_spec.read_text(encoding="utf-8"))
    new = yaml.safe_load(args.new_spec.read_text(encoding="utf-8"))
    changes = diff_specs(old, new)

    breaking = [c for c in changes if c.severity is Severity.BREAKING]
    for change in changes:
        print(change.render())
    print(f"\n{len(changes)} change(s): {len(breaking)} breaking, "
          f"{len(changes) - len(breaking)} non-breaking")
    if breaking:
        print("GATE RESULT: FAIL -- breaking changes require a new version")
        return 1
    print("GATE RESULT: PASS -- all changes are backward compatible")
    return 0


if __name__ == "__main__":
    sys.exit(main())
