"""Listing 4 extracted from chapters/chapter_09_versioning_evolution.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Consumer-tolerance contract tests (Chapter 9, Listing 9.4).

Proves that a frozen v1-era client keeps working while the API evolves:
unknown-field tolerance, additive changes, open-enum fallback, and the
stability of the deprecated v1 surface. Run: pytest -q
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from catalog_api import app

# A v1-era client knows exactly these fields and nothing else.
LEGACY_FIELDS = frozenset({"id", "sku", "name", "price", "category", "in_stock"})
LEGACY_CATEGORIES = frozenset({"actuator", "sensor", "controller"})


def legacy_parse_part(payload: dict) -> dict:
    """Tolerant reader: extract known fields, ignore everything else."""

    return {k: payload[k] for k in LEGACY_FIELDS & payload.keys()}


def legacy_category(value: str) -> str:
    """Open-enum fallback rule documented in the v1 contract."""

    return value if value in LEGACY_CATEGORIES else "unknown"


@pytest.fixture(scope="module")
def client() -> TestClient:
    return TestClient(app)


def test_v1_surface_keeps_every_promised_field(client: TestClient) -> None:
    response = client.get("/v1/catalog")
    assert response.status_code == 200
    parts = response.json()
    assert parts, "fixture catalog must not be empty"
    for part in parts:
        assert LEGACY_FIELDS <= set(part), f"v1 contract violated: {part}"
        assert isinstance(part["price"], float)
        assert isinstance(part["in_stock"], bool)


def test_unknown_fields_are_ignored_by_tolerant_reader() -> None:
    future_payload = {
        "id": "WR-9000", "sku": "NXT-1", "name": "Next-Gen Servo",
        "price": 42.5, "category": "actuator", "in_stock": True,
        # Fields a future version might add:
        "unit_price_cents": 4250, "stock": 7, "tags": ["servo"],
        "dimensions": {"w_mm": 40, "h_mm": 20}, "carbon_footprint_g": 812,
    }
    parsed = legacy_parse_part(future_payload)
    assert parsed == {
        "id": "WR-9000", "sku": "NXT-1", "name": "Next-Gen Servo",
        "price": 42.5, "category": "actuator", "in_stock": True,
    }


def test_new_enum_value_degrades_to_fallback_not_crash() -> None:
    # 'battery' was added after this client shipped; fallback keeps it alive.
    assert legacy_category("battery") == "unknown"
    assert legacy_category("actuator") == "actuator"


def test_v2_additive_fields_do_not_leak_into_v1(client: TestClient) -> None:
    v1 = client.get("/v1/catalog/WR-1042").json()
    v2 = client.get("/v2/catalog/WR-1042").json()
    assert set(v1) == LEGACY_FIELDS
    assert {"unit_price_cents", "stock", "currency", "tags"} <= set(v2)
    # Adapter fidelity: v1 values are derivable from the v2 model.
    assert v1["price"] == round(v2["unit_price_cents"] / 100, 2)
    assert v1["in_stock"] == (v2["stock"] > 0)


def test_v1_carries_deprecation_metadata_v2_does_not(client: TestClient) -> None:
    v1 = client.get("/v1/catalog/WR-1042")
    assert v1.headers["Deprecation"].startswith("@")
    assert "Sunset" in v1.headers
    assert 'rel="successor-version"' in v1.headers["Link"]
    v2 = client.get("/v2/catalog/WR-1042")
    assert "Deprecation" not in v2.headers
    assert "Sunset" not in v2.headers
