"""Listing 3 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ch02_retry.py -- retry wrapper: full jitter + Retry-After + idempotency gate.

Policy (matches Section 3.5):
  * retry on ApiTransportError, ApiServerError5xx, ApiRateLimited;
  * full jitter: wait ~ Uniform(0, min(cap, base * 2**(n-1))), base=0.5s, cap=8s;
  * on 429 with Retry-After, the server-advertised delay OVERRIDES the jitter;
  * budget: at most 4 attempts AND at most 20s total elapsed;
  * idempotency gate: non-idempotent methods retry only with an
    Idempotency-Key header;
  * deterministic tests: inject `rng` and `sleep`.
"""
from __future__ import annotations

import logging
import random
from collections.abc import Callable

import httpx
from tenacity import (
    RetryCallState,
    Retrying,
    retry_if_exception_type,
    stop_after_attempt,
    stop_after_delay,
)

from ch02_httpx_client import (
    ApiRateLimited,
    ApiServerError5xx,
    ApiTransportError,
    NorthwindPartsClient,
)

logger = logging.getLogger("ch02.retry")

BASE_DELAY_S = 0.5
CAP_DELAY_S = 8.0
MAX_ATTEMPTS = 4
MAX_ELAPSED_S = 20.0

SAFE_METHODS: frozenset[str] = frozenset({"GET", "HEAD", "OPTIONS", "PUT", "DELETE"})
RETRYABLE = (ApiTransportError, ApiServerError5xx, ApiRateLimited)


def wait_policy(state: RetryCallState, *, rng: random.Random) -> float:
    """Retry-After from a 429 wins; otherwise full jitter on exponential backoff.

    tenacity calls this between attempts with the just-failed attempt's state,
    so the server-advertised delay is read straight off the raised exception.
    """
    exc = state.outcome.exception() if state.outcome is not None else None
    if isinstance(exc, ApiRateLimited) and exc.retry_after is not None:
        logger.info("429 received: honoring Retry-After of %.1fs", exc.retry_after)
        return exc.retry_after
    upper = min(CAP_DELAY_S, BASE_DELAY_S * (2 ** (state.attempt_number - 1)))
    delay = rng.uniform(0.0, upper)
    logger.info("attempt %d failed; full-jitter backoff %.2fs",
                state.attempt_number, delay)
    return delay


class ResilientPartsClient:
    """NorthwindPartsClient + retry policy. Retryable failures only."""

    def __init__(
        self,
        inner: NorthwindPartsClient,
        *,
        rng: random.Random | None = None,
        sleep: Callable[[float], None] | None = None,
    ) -> None:
        self._inner = inner
        # Seeded RNG and injectable sleep keep tests deterministic & instant.
        self._rng = rng or random.Random(1337)
        self._sleep = sleep  # None -> tenacity's real sleep (production)

    def request_with_retry(
        self,
        method: str,
        path: str,
        *,
        idempotency_key: str | None = None,
        **kwargs: object,
    ) -> httpx.Response:
        method = method.upper()
        if method not in SAFE_METHODS and not idempotency_key:
            raise ValueError(
                f"refusing to auto-retry non-idempotent {method} without "
                "an idempotency key"
            )
        if idempotency_key:
            headers = dict(kwargs.pop("headers", {}) or {})
            headers["Idempotency-Key"] = idempotency_key
            kwargs["headers"] = headers

        retrying = Retrying(
            retry=retry_if_exception_type(RETRYABLE),
            wait=lambda state: wait_policy(state, rng=self._rng),
            stop=stop_after_attempt(MAX_ATTEMPTS) | stop_after_delay(MAX_ELAPSED_S),
            sleep=self._sleep if self._sleep is not None else _real_sleep,
            reraise=True,
        )
        return retrying(self._inner._request, method, path, **kwargs)


def _real_sleep(seconds: float) -> None:
    import time

    time.sleep(seconds)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    inner = NorthwindPartsClient("http://127.0.0.1:8765", api_key="demo-key-nr-001")
    resilient = ResilientPartsClient(inner)
    try:
        response = resilient.request_with_retry("GET", "/parts/NR-1001")
        logger.info("status=%d body=%s", response.status_code, response.text[:80])
    finally:
        inner.close()


if __name__ == "__main__":
    main()
