"""Listing 5 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""test_ch02_client.py -- hermetic tests: no network, no wall clock, seeded RNG.

Run:  pytest -q
Simulates: 500s then success, 429 with Retry-After, deterministic 4xx,
transport timeouts, slow responses (mocked), contract breaches, and the
idempotency gate.
"""
from __future__ import annotations

import random

import httpx
import pytest

from ch02_httpx_client import (
    ApiClientError4xx,
    ApiContractError,
    ApiRateLimited,
    ApiServerError5xx,
    ApiTransportError,
    NorthwindPartsClient,
)
from ch02_retry import ResilientPartsClient

BASE_URL = "http://stub.local"  # never resolves: MockTransport intercepts


def make_client(handler, **kwargs) -> NorthwindPartsClient:
    return NorthwindPartsClient(
        BASE_URL, api_key="test-key",
        transport=httpx.MockTransport(handler), **kwargs,
    )


# --- Status handling & taxonomy ---------------------------------------------

def test_get_part_success() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.headers["Authorization"] == "Bearer test-key"
        return httpx.Response(200, json={"part_id": "NR-1001", "name": "Servo"})
    with make_client(handler) as client:
        assert client.get_part("NR-1001")["name"] == "Servo"


def test_404_maps_to_typed_client_error() -> None:
    with make_client(lambda r: httpx.Response(404, json={"error": "no such part"})) as c:
        with pytest.raises(ApiClientError4xx) as exc_info:
            c.get_part("NOPE-1")
        assert exc_info.value.status_code == 404


def test_500_maps_to_server_error() -> None:
    with make_client(lambda r: httpx.Response(503)) as c:
        with pytest.raises(ApiServerError5xx):
            c.get_part("NR-1001")


def test_429_carries_retry_after() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(429, headers={"Retry-After": "7"})
    with make_client(handler) as c:
        with pytest.raises(ApiRateLimited) as exc_info:
            c.get_part("NR-1001")
        assert exc_info.value.retry_after == 7.0


def test_transport_timeout_maps_to_transport_error() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ReadTimeout("simulated hung peer", request=request)
    with make_client(handler) as c:
        with pytest.raises(ApiTransportError):
            c.get_part("NR-1001")


def test_200_with_broken_body_is_contract_error() -> None:
    with make_client(lambda r: httpx.Response(200, content=b"<html>oops</html>")) as c:
        with pytest.raises(ApiContractError):
            c.get_part("NR-1001")


# --- Retry policy --------------------------------------------------------------

def test_retry_recovers_from_transient_500s() -> None:
    calls = {"n": 0}
    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] < 3:
            return httpx.Response(500)
        return httpx.Response(200, json={"part_id": "NR-1001"})
    inner = make_client(handler)
    sleeps: list[float] = []
    resilient = ResilientPartsClient(
        inner, rng=random.Random(42), sleep=sleeps.append
    )
    response = resilient.request_with_retry("GET", "/parts/NR-1001")
    assert response.status_code == 200
    assert calls["n"] == 3
    assert len(sleeps) == 2  # two retries, two jittered sleeps, zero wall time


def test_retry_honors_retry_after_over_jitter() -> None:
    calls = {"n": 0}
    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            return httpx.Response(429, headers={"Retry-After": "5"})
        return httpx.Response(200, json={"ok": True})
    inner = make_client(handler)
    sleeps: list[float] = []
    resilient = ResilientPartsClient(
        inner, rng=random.Random(42), sleep=sleeps.append
    )
    resilient.request_with_retry("GET", "/parts/NR-1001")
    assert sleeps == [5.0]  # server-advertised delay, not jitter


def test_4xx_is_never_retried() -> None:
    calls = {"n": 0}
    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        return httpx.Response(422, json={"detail": "invalid"})
    inner = make_client(handler)
    resilient = ResilientPartsClient(inner, rng=random.Random(42),
                                     sleep=lambda s: None)
    with pytest.raises(ApiClientError4xx):
        resilient.request_with_retry("GET", "/parts/NR-1001")
    assert calls["n"] == 1


def test_post_without_idempotency_key_is_refused() -> None:
    inner = make_client(lambda r: httpx.Response(200, json={}))
    resilient = ResilientPartsClient(inner)
    with pytest.raises(ValueError, match="idempotency"):
        resilient.request_with_retry("POST", "/orders", json={"qty": 1})


def test_post_with_idempotency_key_retries_and_sends_header() -> None:
    seen: list[str | None] = []
    calls = {"n": 0}
    def handler(request: httpx.Request) -> httpx.Response:
        seen.append(request.headers.get("Idempotency-Key"))
        calls["n"] += 1
        if calls["n"] == 1:
            return httpx.Response(503)
        return httpx.Response(201, json={"order_id": "ORD-9"})
    inner = make_client(handler)
    resilient = ResilientPartsClient(inner, rng=random.Random(42),
                                     sleep=lambda s: None)
    response = resilient.request_with_retry(
        "POST", "/orders", idempotency_key="key-abc-123", json={"qty": 1}
    )
    assert response.status_code == 201
    assert seen == ["key-abc-123", "key-abc-123"]  # key stable across replays
