"""Listing 6 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ch02_stub_server.py -- offline stub for the Northwind Robotics Parts API.

Stdlib only. Deterministic. Listens on 127.0.0.1:8765 (localhost only).

Endpoints:
  GET /parts/{id}        -> 200 JSON part, or 404
  GET /parts?limit&cursor-> cursor-paginated catalog (5 synthetic parts)
  GET /parts-link        -> RFC 8288 Link-header pagination (2 pages)
  GET /rate-limited      -> 429 with Retry-After: 2 (always)
  GET /flaky             -> 500, 500, then 200 (per-process state)
  GET /catalog/export    -> streamed JSONL catalog

Run:  python ch02_stub_server.py
"""
from __future__ import annotations

import json
import logging
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger("ch02.stub")

# Synthetic Northwind Robotics catalog: fictional parts, fictional prices.
CATALOG: list[dict[str, object]] = [
    {"part_id": "NR-1001", "name": "Servo Motor SG-90", "unit_price_cents": 450},
    {"part_id": "NR-1002", "name": "LiDAR Unit LR-2", "unit_price_cents": 8999},
    {"part_id": "NR-1003", "name": "Chassis Plate AL-7075", "unit_price_cents": 3200},
    {"part_id": "NR-1004", "name": "Wheel Encoder WE-512", "unit_price_cents": 1250},
    {"part_id": "NR-1005", "name": "Battery Pack BP-4S", "unit_price_cents": 5400},
]

_flaky_calls = {"n": 0}
_state_lock = threading.Lock()


class StubHandler(BaseHTTPRequestHandler):
    server_version = "NorthwindStub/1.0"

    def _send_json(self, status: int, payload: dict[str, object],
                   extra_headers: dict[str, str] | None = None) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        for key, value in (extra_headers or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 (stdlib naming)
        parsed = urlparse(self.path)
        route, query = parsed.path, parse_qs(parsed.query)

        if route.startswith("/parts/"):
            part_id = route.rsplit("/", 1)[-1]
            part = next((p for p in CATALOG if p["part_id"] == part_id), None)
            if part is None:
                self._send_json(404, {"error": f"no such part: {part_id}"})
            else:
                self._send_json(200, part)
            return

        if route == "/parts":
            limit = int(query.get("limit", ["50"])[0])
            cursor = query.get("cursor", [None])[0]
            start = int(cursor) if cursor is not None else 0  # stub: cursor = index
            items = CATALOG[start:start + limit]
            next_index = start + limit
            payload: dict[str, object] = {"items": items}
            if next_index < len(CATALOG):
                payload["next_cursor"] = str(next_index)
            self._send_json(200, payload)
            return

        if route == "/parts-link":
            if query.get("page") == ["2"]:
                # Final page: no Link header -> iterator terminates.
                self._send_json(200, {"items": CATALOG[3:]})
            else:
                self._send_json(
                    200, {"items": CATALOG[:3]},
                    extra_headers={"Link": '</parts-link?page=2>; rel="next"'},
                )
            return

        if route == "/rate-limited":
            self._send_json(429, {"error": "slow down"},
                            extra_headers={"Retry-After": "2"})
            return

        if route == "/flaky":
            with _state_lock:
                _flaky_calls["n"] += 1
                n = _flaky_calls["n"]
            if n < 3:
                self._send_json(500, {"error": "transient blip"})
            else:
                self._send_json(200, {"part_id": "NR-1001", "ok": True})
            return

        if route == "/catalog/export":
            lines = "".join(json.dumps(p) + "\n" for p in CATALOG).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/x-ndjson")
            self.send_header("Content-Length", str(len(lines)))
            self.end_headers()
            self.wfile.write(lines)
            return

        self._send_json(404, {"error": f"unknown route: {route}"})

    def log_message(self, fmt: str, *args: object) -> None:
        logger.info("stub: " + fmt, *args)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    server = ThreadingHTTPServer(("127.0.0.1", 8765), StubHandler)
    logger.info("Northwind stub listening on http://127.0.0.1:8765 (Ctrl+C to stop)")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


if __name__ == "__main__":
    main()
