"""Listing 1 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ch02_urllib_baseline.py -- stdlib urllib consumer (baseline, with sharp edges).

Run against the local stub:  python ch02_stub_server.py   (in another shell)
Then:                        python ch02_urllib_baseline.py
"""
from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger("ch02.urllib_baseline")

BASE_URL = "http://127.0.0.1:8765"  # local stub only -- never the internet


@dataclass(frozen=True)
class Part:
    part_id: str
    name: str
    unit_price_cents: int


def fetch_part(part_id: str, timeout_s: float = 5.0) -> Part:
    """Fetch one part with urllib. NOTE the single, flat timeout.

    Sharp edges on display:
      * one timeout covers DNS+connect+read; no write/pool dimension;
      * no session -> no keep-alive: DNS/TCP/TLS are re-paid per call;
      * HTTPError is raised for 4xx/5xx AND doubles as a response object;
      * JSON, status classification, and retry are all manual.
    """
    url = f"{BASE_URL}/parts/{part_id}"
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            status: int = resp.status
            raw: bytes = resp.read()  # unbounded: a hostile peer can exhaust RAM
    except urllib.error.HTTPError as exc:
        # HTTPError is simultaneously the exception and the response.
        logger.error("HTTP %s for %s", exc.code, url)
        raise RuntimeError(f"status {exc.code}") from exc
    except urllib.error.URLError as exc:
        # Transport failure (DNS, refused connection, timeout -> socket.timeout
        # wrapped inside .reason). Nothing distinguishes the sub-causes here.
        logger.error("transport failure for %s: %s", url, exc.reason)
        raise RuntimeError(f"transport: {exc.reason}") from exc

    if status != 200:
        raise RuntimeError(f"unexpected status {status}")
    payload: dict[str, Any] = json.loads(raw.decode("utf-8"))
    return Part(
        part_id=str(payload["part_id"]),
        name=str(payload["name"]),
        unit_price_cents=int(payload["unit_price_cents"]),
    )


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    part = fetch_part("NR-1001")
    logger.info("got part: %s", part)


if __name__ == "__main__":
    main()
