"""Listing 2 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ch02_httpx_client.py -- production-grade httpx client for the
Northwind Robotics Parts API.

Design contract:
  * explicit 4-dimension timeouts (connect/read/write/pool); nothing infinite;
  * bounded connection pool with keep-alive; one long-lived client instance;
  * auth injected in exactly one place, never logged;
  * typed error taxonomy: transport vs status vs contract;
  * telemetry via event hooks (latency + status, header-safe logging);
  * transport injection (httpx.MockTransport) for hermetic offline tests.
"""
from __future__ import annotations

import logging
import time
from typing import Any

import httpx

logger = logging.getLogger("ch02.httpx_client")

RETRYABLE_STATUSES: frozenset[int] = frozenset({408, 425, 429, 500, 502, 503, 504})


# ---- Error taxonomy ---------------------------------------------------------

class ApiClientError(Exception):
    """Root of all errors raised by this client."""


class ApiTransportError(ApiClientError):
    """The request never completed: DNS, TCP, TLS, timeout, pool exhaustion."""


class ApiStatusError(ApiClientError):
    """The server answered with a non-2xx status."""

    def __init__(self, message: str, *, status_code: int) -> None:
        super().__init__(message)
        self.status_code = status_code


class ApiClientError4xx(ApiStatusError):
    """Deterministic caller fault; retrying as-is is futile."""


class ApiServerError5xx(ApiStatusError):
    """Transient server fault; a candidate for retry per policy."""


class ApiRateLimited(ApiStatusError):
    """429: carries the server-advertised delay when present."""

    def __init__(self, message: str, *, status_code: int, retry_after: float | None) -> None:
        super().__init__(message, status_code=status_code)
        self.retry_after = retry_after


class ApiContractError(ApiClientError):
    """2xx received, but the payload violates the expected contract."""


# ---- Telemetry hooks ---------------------------------------------------------

def _log_request(request: httpx.Request) -> None:
    # NEVER log request.headers: Authorization lives there.
    logger.info("request %s %s", request.method, request.url.path)


def _log_response(response: httpx.Response) -> None:
    # Latency is timed in _request() with time.monotonic(): response.elapsed
    # is only populated after the body is read, which a hook must not force
    # (it would buffer streaming responses).
    logger.info(
        "response %s %s -> %d",
        response.request.method, response.request.url.path, response.status_code,
    )


# ---- The client ---------------------------------------------------------------

class NorthwindPartsClient:
    """Typed, resilient consumer for the Northwind Robotics Parts API."""

    def __init__(
        self,
        base_url: str,
        api_key: str,
        *,
        transport: httpx.BaseTransport | None = None,  # inject MockTransport in tests
        timeout: httpx.Timeout | None = None,
        limits: httpx.Limits | None = None,
    ) -> None:
        if not base_url:
            raise ValueError("base_url must be non-empty")
        if not api_key:
            raise ValueError("api_key must be non-empty")
        self._client = httpx.Client(
            base_url=base_url.rstrip("/"),
            # Auth lives HERE and nowhere else.
            headers={
                "Authorization": f"Bearer {api_key}",
                "Accept": "application/json",
                "User-Agent": "northwind-parts-sdk/1.0 (ops@northwind-robotics.example)",
            },
            timeout=timeout or httpx.Timeout(
                connect=2.0, read=10.0, write=10.0, pool=2.0
            ),
            limits=limits or httpx.Limits(
                max_connections=20, max_keepalive_connections=10,
                keepalive_expiry=30.0,
            ),
            event_hooks={"request": [_log_request], "response": [_log_response]},
            transport=transport,
        )

    # Context-manager protocol: deterministic socket lifecycle.
    def __enter__(self) -> "NorthwindPartsClient":
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    def close(self) -> None:
        self._client.close()

    # Core request path ------------------------------------------------------

    def _request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        started = time.monotonic()
        try:
            response = self._client.request(method, path, **kwargs)
        except httpx.TimeoutException as exc:
            kind = type(exc).__name__  # ConnectTimeout / ReadTimeout / PoolTimeout / ...
            logger.warning("timeout (%s) on %s %s", kind, method, path)
            raise ApiTransportError(f"{kind} on {method} {path}") from exc
        except httpx.TransportError as exc:
            logger.warning("transport error on %s %s: %s", method, path, exc)
            raise ApiTransportError(f"transport error on {method} {path}: {exc}") from exc
        finally:
            logger.debug(
                "call %s %s took %.1fms",
                method, path, (time.monotonic() - started) * 1000.0,
            )
        self._raise_for_status(response)
        return response

    @staticmethod
    def _raise_for_status(response: httpx.Response) -> None:
        code = response.status_code
        if code < 400:
            return
        message = f"{response.request.method} {response.request.url.path} -> {code}"
        if code == 429:
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            raise ApiRateLimited(message, status_code=code, retry_after=retry_after)
        if code >= 500:
            raise ApiServerError5xx(message, status_code=code)
        raise ApiClientError4xx(message, status_code=code)

    # Public API --------------------------------------------------------------

    def get_json(self, path: str, **kwargs: Any) -> dict[str, Any]:
        response = self._request("GET", path, **kwargs)
        try:
            payload = response.json()
        except ValueError as exc:  # 200 OK but not JSON: contract breach.
            raise ApiContractError(f"{path}: invalid JSON body") from exc
        if not isinstance(payload, dict):
            raise ApiContractError(f"{path}: expected JSON object, got {type(payload).__name__}")
        return payload

    def get_part(self, part_id: str) -> dict[str, Any]:
        if not part_id:
            raise ValueError("part_id must be non-empty")
        return self.get_json(f"/parts/{part_id}")


def _parse_retry_after(value: str | None, *, ceiling_s: float = 60.0) -> float | None:
    """Parse a delta-seconds Retry-After header, clamped to a ceiling."""
    if value is None:
        return None
    try:
        seconds = float(value)  # delta-seconds form; HTTP-date form omitted for brevity
    except ValueError:
        return None
    return max(0.0, min(seconds, ceiling_s))


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    # The demo key is synthetic; the stub accepts any non-empty bearer token.
    with NorthwindPartsClient("http://127.0.0.1:8765", api_key="demo-key-nr-001") as client:
        part = client.get_part("NR-1001")
        logger.info("part: %s", part)


if __name__ == "__main__":
    main()
