"""Listing 4 extracted from chapters/chapter_02_consuming_apis_python.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ch02_pagination_stream.py -- typed pagination iterators + streaming download.

Cursor iterator: follows opaque `next_cursor` tokens; never parses them.
Link iterator: follows RFC 8288 `Link: <url>; rel="next"` headers.
Downloader:    streams via iter_bytes (bounded memory), reports progress,
               and honours cancellation by closing the response promptly.
"""
from __future__ import annotations

import logging
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

import httpx

from ch02_httpx_client import ApiContractError, NorthwindPartsClient

logger = logging.getLogger("ch02.pagination")

CHUNK_SIZE = 64 * 1024  # 64 KiB: memory stays O(chunk), never O(payload)


def iter_parts_cursor(
    client: NorthwindPartsClient,
    *,
    page_size: int = 50,
    max_pages: int = 1000,  # runaway-guard: a broken server must not loop us forever
) -> Iterator[dict[str, Any]]:
    """Yield every part from a cursor-paginated /parts endpoint."""
    cursor: str | None = None
    for _ in range(max_pages):
        params: dict[str, Any] = {"limit": page_size}
        if cursor is not None:
            params["cursor"] = cursor  # opaque token: pass through, never parse
        page = client.get_json("/parts", params=params)
        items = page.get("items")
        if not isinstance(items, list):
            raise ApiContractError("/parts: 'items' must be a list")
        yield from items
        cursor = page.get("next_cursor")
        if not cursor:  # termination: absent next_cursor
            return
    raise ApiContractError(f"/parts: exceeded {max_pages} pages (server bug?)")


def iter_parts_link_header(
    client: NorthwindPartsClient, *, max_pages: int = 1000
) -> Iterator[dict[str, Any]]:
    """Yield every part by following RFC 8288 Link: rel="next" headers."""
    response = client._request("GET", "/parts-link")
    for _ in range(max_pages):
        try:
            page: dict[str, Any] = response.json()
        except ValueError as exc:
            raise ApiContractError("/parts-link: invalid JSON body") from exc
        items = page.get("items")
        if not isinstance(items, list):
            raise ApiContractError("/parts-link: 'items' must be a list")
        yield from items
        next_url = _parse_link_next(response.headers.get("Link"))
        if next_url is None:  # termination: no rel="next"
            return
        response = client._request("GET", next_url)
    raise ApiContractError(f"/parts-link: exceeded {max_pages} pages")


def _parse_link_next(header: str | None) -> str | None:
    """Extract the rel="next" target from an RFC 8288 Link header."""
    if not header:
        return None
    for segment in header.split(","):
        parts = segment.split(";")
        if len(parts) == 2 and parts[1].strip() == 'rel="next"':
            return parts[0].strip().strip("<>")
    return None


def stream_download(
    client: NorthwindPartsClient,
    path: str,
    destination: Path,
    *,
    on_progress: Callable[[int, int | None], None] | None = None,
    cancel: Callable[[], bool] = lambda: False,
) -> int:
    """Stream `path` to `destination`; return bytes written.

    Memory stays O(CHUNK_SIZE). Cancellation is cooperative: when cancel()
    returns True we abort, close the stream, and delete the partial file so
    no corrupt artifact survives.
    """
    received = 0
    tmp = destination.with_suffix(destination.suffix + ".part")
    try:
        with client._client.stream("GET", path) as response:
            client._raise_for_status(response)
            total_header = response.headers.get("Content-Length")
            total = int(total_header) if total_header else None
            with tmp.open("wb") as fh:
                for chunk in response.iter_bytes(CHUNK_SIZE):
                    if cancel():
                        raise InterruptedError("download cancelled by caller")
                    fh.write(chunk)
                    received += len(chunk)
                    if on_progress:
                        on_progress(received, total)
        tmp.replace(destination)  # atomic rename: all-or-nothing artifact
        return received
    except BaseException:
        tmp.unlink(missing_ok=True)  # never leave a partial file behind
        raise


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    with NorthwindPartsClient("http://127.0.0.1:8765", api_key="demo-key-nr-001") as client:
        count = sum(1 for _ in iter_parts_cursor(client, page_size=2))
        logger.info("cursor-paginated parts: %d", count)
        written = stream_download(
            client, "/catalog/export",
            Path("catalog_export.jsonl"),
            on_progress=lambda done, total: logger.info("progress: %d/%s bytes", done, total),
        )
        logger.info("downloaded %d bytes", written)


if __name__ == "__main__":
    main()
