"""Listing 6 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

import grpc, telemetry_pb2, telemetry_pb2_grpc
channel = grpc.insecure_channel("localhost:50051")
stub = telemetry_pb2_grpc.TelemetryServiceStub(channel)
req = telemetry_pb2.RobotStatusRequest(robot_id="RB-SLOW")
print(stub.GetRobotStatus(req, timeout=5.0).robot_id)   # succeeds: budget ample
try:
    stub.GetRobotStatus(req, timeout=0.05)               # 50 ms < 200 ms stall
except grpc.RpcError as err:
    print(err.code())                                    # StatusCode.DEADLINE_EXCEEDED
