"""Listing 4 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Bidirectional control-loop demo with flow-control-aware production.

A producer thread writes commands into a bounded queue; the gRPC request
generator drains it. When the queue is full the producer blocks, giving the
application its own backpressure on top of HTTP/2 flow control. Offline:
localhost only, synthetic commands, deterministic pacing.
"""
from __future__ import annotations

import queue
import threading
import time
from typing import Iterator

import grpc

import telemetry_pb2
import telemetry_pb2_grpc

_DONE: object = object()  # sentinel closing the command stream


def _producer(
    outbox: queue.Queue,
    robot_id: str,
    count: int,
    interval_s: float,
) -> None:
    try:
        for seq in range(count):
            if seq % 5 == 4:
                command = telemetry_pb2.ControlCommand(
                    robot_id=robot_id, sequence=seq, estop=False
                )
            else:
                command = telemetry_pb2.ControlCommand(
                    robot_id=robot_id,
                    sequence=seq,
                    set_mode=telemetry_pb2.ROBOT_MODE_MOVING,
                )
            # put() blocks while the window is full: application backpressure.
            outbox.put(command)
            time.sleep(interval_s)
    finally:
        outbox.put(_DONE)


def _commands(
    inbox: queue.Queue,
) -> Iterator[telemetry_pb2.ControlCommand]:
    while True:
        item = inbox.get()
        if item is _DONE:
            return
        yield item


def run_control_loop(
    stub: telemetry_pb2_grpc.TelemetryServiceStub,
    robot_id: str,
    count: int,
    interval_s: float = 0.005,
    window: int = 8,
    deadline_s: float = 10.0,
) -> list[telemetry_pb2.TelemetryFrame]:
    """Drive a bidi ControlLoop; returns every frame the server echoed."""
    outbox: queue.Queue = queue.Queue(maxsize=window)
    producer = threading.Thread(
        target=_producer,
        args=(outbox, robot_id, count, interval_s),
        daemon=True,
    )
    producer.start()
    frames: list[telemetry_pb2.TelemetryFrame] = []
    try:
        for frame in stub.ControlLoop(_commands(outbox), timeout=deadline_s):
            frames.append(frame)
    finally:
        producer.join(timeout=2.0)
    return frames


def main() -> None:
    import argparse

    from telemetry_client import make_channel

    parser = argparse.ArgumentParser(description="Bidirectional control-loop demo")
    parser.add_argument("--port", type=int, default=50051)
    args = parser.parse_args()
    channel = make_channel(f"localhost:{args.port}")
    stub = telemetry_pb2_grpc.TelemetryServiceStub(channel)
    frames = run_control_loop(stub, robot_id="RB-1001", count=10)
    for frame in frames:
        mode = telemetry_pb2.RobotMode.Name(frame.mode)
        print(f"ack robot={frame.robot_id} mode={mode} t={frame.observed_at.seconds}")
    channel.close()


if __name__ == "__main__":
    main()
