"""Listing 5 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Offline pytest suite for the Chapter 13 telemetry service.

The server runs in-process on an ephemeral localhost port (port 0); no
network, no credentials, deterministic data. Covers all four RPC modes,
deadline propagation, cancellation, and stream error paths.
"""
from __future__ import annotations

import grpc
import pytest

import telemetry_pb2
import telemetry_pb2_grpc
from bidi_demo import run_control_loop
from error_middleware import ErrorMappingInterceptor, decode_error_details
from telemetry_client import make_channel
from telemetry_server import BASE_EPOCH_S, make_server


@pytest.fixture()
def stub():
    server = make_server(interceptors=(ErrorMappingInterceptor(),))
    port = server.add_insecure_port("localhost:0")
    server.start()
    channel = make_channel(
        f"localhost:{port}", correlation_factory=lambda: "corr-test-0001"
    )
    yield telemetry_pb2_grpc.TelemetryServiceStub(channel)
    channel.close()
    server.stop(None)


def _frame(robot_id: str, battery: float) -> telemetry_pb2.TelemetryFrame:
    frame = telemetry_pb2.TelemetryFrame(robot_id=robot_id, battery_pct=battery)
    frame.observed_at.FromSeconds(BASE_EPOCH_S)
    return frame


def test_unary_status_happy_path(stub) -> None:
    reply = stub.GetRobotStatus(
        telemetry_pb2.RobotStatusRequest(robot_id="RB-1001"), timeout=5.0
    )
    assert reply.robot_id == "RB-1001"
    assert reply.mode == telemetry_pb2.ROBOT_MODE_MOVING
    assert 0.0 <= reply.battery_pct <= 100.0
    assert reply.last_frame.joint_positions_rad["shoulder"] != 0.0


def test_unknown_robot_maps_to_not_found_with_rich_details(stub) -> None:
    with pytest.raises(grpc.RpcError) as excinfo:
        stub.GetRobotStatus(
            telemetry_pb2.RobotStatusRequest(robot_id="RB-9999"), timeout=5.0
        )
    err = excinfo.value
    assert err.code() == grpc.StatusCode.NOT_FOUND
    details = decode_error_details(err)
    assert details is not None
    assert details.reason == "ROBOT_NOT_FOUND"
    assert details.correlation_id == "corr-test-0001"


def test_deadline_exceeded_propagates(stub) -> None:
    # RB-SLOW stalls 200 ms server-side; the 50 ms client deadline wins.
    with pytest.raises(grpc.RpcError) as excinfo:
        stub.GetRobotStatus(
            telemetry_pb2.RobotStatusRequest(robot_id="RB-SLOW"), timeout=0.05
        )
    assert excinfo.value.code() == grpc.StatusCode.DEADLINE_EXCEEDED


def test_server_stream_respects_max_frames(stub) -> None:
    request = telemetry_pb2.StreamTelemetryRequest(
        robot_id="RB-1002", max_frames=4, period_ms=5
    )
    frames = list(stub.StreamTelemetry(request, timeout=5.0))
    assert len(frames) == 4
    assert [f.observed_at.seconds for f in frames] == [
        BASE_EPOCH_S + i * 5 for i in range(4)
    ]


def test_client_cancellation_stops_server_stream(stub) -> None:
    request = telemetry_pb2.StreamTelemetryRequest(
        robot_id="RB-1001", max_frames=100_000, period_ms=5
    )
    call = stub.StreamTelemetry(request, timeout=30.0)
    first = next(call)
    assert first.robot_id == "RB-1001"
    call.cancel()
    with pytest.raises(grpc.RpcError) as excinfo:
        next(call)
    assert excinfo.value.code() == grpc.StatusCode.CANCELLED


def test_upload_rejects_out_of_range_battery(stub) -> None:
    frames = [_frame("RB-1001", 90.0), _frame("RB-1001", 140.0), _frame("RB-1001", 50.0)]
    call = stub.UploadTelemetry.future(iter(frames), timeout=5.0)
    summary = call.result()
    assert (summary.accepted, summary.rejected) == (2, 1)
    assert summary.min_battery_pct == pytest.approx(50.0)
    assert summary.max_battery_pct == pytest.approx(90.0)


def test_upload_unknown_robot_aborts_mid_stream_with_details(stub) -> None:
    frames = [_frame("RB-1001", 90.0), _frame("RB-9999", 10.0)]
    call = stub.UploadTelemetry.future(iter(frames), timeout=5.0)
    with pytest.raises(grpc.RpcError) as excinfo:
        call.result()
    err = excinfo.value
    assert err.code() == grpc.StatusCode.INVALID_ARGUMENT
    details = decode_error_details(err)
    assert details is not None
    assert details.reason == "FRAME_VALIDATION_FAILED"
    assert details.violations[0].field == "robot_id"
    assert details.correlation_id == "corr-test-0001"


def test_control_loop_bidi_round_trip(stub) -> None:
    frames = run_control_loop(
        stub, robot_id="RB-1001", count=10, interval_s=0.001, deadline_s=10.0
    )
    assert len(frames) == 10
    # Sequence numbers echo through to deterministic timestamps.
    assert [f.observed_at.seconds for f in frames] == [
        BASE_EPOCH_S + i * 5 for i in range(10)
    ]
    # seq % 5 == 4 carries estop=False -> IDLE; everything else MOVING.
    assert frames[4].mode == telemetry_pb2.ROBOT_MODE_IDLE
    assert frames[0].mode == telemetry_pb2.ROBOT_MODE_MOVING
