"""Listing 1 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Northwind Robotics telemetry service -- gRPC server implementation.

Chapter 13 listing. Offline-first: binds to localhost only; every payload is
synthetic and derived from a fixed seed, never from the wall clock.
"""
from __future__ import annotations

import argparse
import random
import time
from concurrent import futures
from typing import Iterable, Iterator

import grpc

import telemetry_pb2
import telemetry_pb2_grpc

BASE_EPOCH_S = 1_700_000_000  # fixed synthetic epoch for deterministic payloads
KNOWN_ROBOTS = ("RB-1001", "RB-1002", "RB-1003", "RB-SLOW")
MIN_BUDGET_S = 0.005


class DomainError(Exception):
    """Application error carrying its intended gRPC status mapping."""

    status_code: grpc.StatusCode = grpc.StatusCode.INTERNAL
    reason: str = "INTERNAL"

    def __init__(
        self,
        message: str,
        violations: list[telemetry_pb2.FieldViolation] | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.violations = violations or []


class UnknownRobotError(DomainError):
    status_code = grpc.StatusCode.NOT_FOUND
    reason = "ROBOT_NOT_FOUND"


class FrameValidationError(DomainError):
    status_code = grpc.StatusCode.INVALID_ARGUMENT
    reason = "FRAME_VALIDATION_FAILED"


def _check_known(robot_id: str) -> None:
    if robot_id not in KNOWN_ROBOTS:
        raise UnknownRobotError(f"unknown robot_id {robot_id!r}")


def _require_budget(
    context: grpc.ServicerContext, min_s: float = MIN_BUDGET_S
) -> None:
    """Fail fast if the propagated deadline leaves no useful budget."""
    remaining = context.time_remaining()
    if remaining < min_s:
        context.abort(
            grpc.StatusCode.DEADLINE_EXCEEDED,
            f"budget exhausted: {remaining * 1000:.2f} ms remaining",
        )


class TelemetryService(telemetry_pb2_grpc.TelemetryServiceServicer):
    """All four RPC modes with explicit deadline and cancellation checks."""

    def __init__(self, seed: int = 1337) -> None:
        self._seed = seed

    def _frame(
        self,
        robot_id: str,
        seq: int,
        mode: telemetry_pb2.RobotMode | None = None,
    ) -> telemetry_pb2.TelemetryFrame:
        # Per-frame seeded RNG keeps payloads deterministic and reproducible.
        rng = random.Random(f"{self._seed}:{robot_id}:{seq}")
        frame = telemetry_pb2.TelemetryFrame(
            robot_id=robot_id,
            battery_pct=round(95.0 - 0.01 * seq + rng.uniform(-0.25, 0.25), 3),
            chassis_temp_celsius=round(32.0 + rng.uniform(-1.0, 1.0), 2),
            mode=(
                telemetry_pb2.ROBOT_MODE_MOVING if mode is None else mode
            ),
        )
        frame.observed_at.FromSeconds(BASE_EPOCH_S + seq * 5)
        frame.joint_positions_rad["shoulder"] = round(rng.uniform(-1.0, 1.0), 4)
        frame.joint_positions_rad["elbow"] = round(rng.uniform(0.0, 2.0), 4)
        frame.aisle.CopyFrom(
            telemetry_pb2.AislePosition(
                aisle_id="A-07", offset_m=round(rng.uniform(0.0, 120.0), 2)
            )
        )
        return frame

    # -- Mode 1: unary ----------------------------------------------------
    def GetRobotStatus(
        self,
        request: telemetry_pb2.RobotStatusRequest,
        context: grpc.ServicerContext,
    ) -> telemetry_pb2.RobotStatusReply:
        _require_budget(context)
        _check_known(request.robot_id)
        if request.robot_id == "RB-SLOW":
            time.sleep(0.200)  # simulated slow dependency
            _require_budget(context, min_s=0.100)  # re-check after the stall
        last = self._frame(request.robot_id, seq=0)
        reply = telemetry_pb2.RobotStatusReply(
            robot_id=request.robot_id,
            mode=last.mode,
            battery_pct=last.battery_pct,
        )
        reply.firmware_built_at.FromSeconds(BASE_EPOCH_S - 86_400)
        reply.last_frame.CopyFrom(last)
        return reply

    # -- Mode 2: server streaming ------------------------------------------
    def StreamTelemetry(
        self,
        request: telemetry_pb2.StreamTelemetryRequest,
        context: grpc.ServicerContext,
    ) -> Iterator[telemetry_pb2.TelemetryFrame]:
        _check_known(request.robot_id)
        if request.max_frames == 0:
            raise FrameValidationError(
                "max_frames must be >= 1",
                [
                    telemetry_pb2.FieldViolation(
                        field="max_frames", description="must be >= 1"
                    )
                ],
            )
        period_s = max(request.period_ms, 1) / 1000.0
        for seq in range(request.max_frames):
            if not context.is_active():
                return  # client cancelled: stop producing promptly
            _require_budget(context)
            time.sleep(period_s)
            yield self._frame(request.robot_id, seq)

    # -- Mode 3: client streaming -------------------------------------------
    def UploadTelemetry(
        self,
        request_iterator: Iterable[telemetry_pb2.TelemetryFrame],
        context: grpc.ServicerContext,
    ) -> telemetry_pb2.UploadSummary:
        accepted = 0
        rejected = 0
        min_battery = float("inf")
        max_battery = float("-inf")
        for frame in request_iterator:
            if not context.is_active():
                break
            if frame.robot_id not in KNOWN_ROBOTS:
                raise FrameValidationError(
                    "frame references unknown robot",
                    [
                        telemetry_pb2.FieldViolation(
                            field="robot_id",
                            description="must be a known robot",
                        )
                    ],
                )
            if not 0.0 <= frame.battery_pct <= 100.0:
                rejected += 1
                continue
            accepted += 1
            min_battery = min(min_battery, frame.battery_pct)
            max_battery = max(max_battery, frame.battery_pct)
        return telemetry_pb2.UploadSummary(
            accepted=accepted,
            rejected=rejected,
            min_battery_pct=round(min_battery, 3) if accepted else 0.0,
            max_battery_pct=round(max_battery, 3) if accepted else 0.0,
        )

    # -- Mode 4: bidirectional streaming -------------------------------------
    def ControlLoop(
        self,
        request_iterator: Iterable[telemetry_pb2.ControlCommand],
        context: grpc.ServicerContext,
    ) -> Iterator[telemetry_pb2.TelemetryFrame]:
        for command in request_iterator:
            if not context.is_active():
                return
            _require_budget(context)
            _check_known(command.robot_id)
            action = command.WhichOneof("action")
            if action == "set_mode":
                mode = command.set_mode
            elif action == "estop":
                mode = (
                    telemetry_pb2.ROBOT_MODE_FAULT
                    if command.estop
                    else telemetry_pb2.ROBOT_MODE_IDLE
                )
            elif action == "set_speed_mps":
                mode = telemetry_pb2.ROBOT_MODE_MOVING
            else:
                raise FrameValidationError(
                    "command has no action set",
                    [
                        telemetry_pb2.FieldViolation(
                            field="action", description="oneof must be set"
                        )
                    ],
                )
            yield self._frame(command.robot_id, seq=command.sequence, mode=mode)


def make_server(
    interceptors: tuple[grpc.ServerInterceptor, ...] = (),
    max_workers: int = 8,
) -> grpc.Server:
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=max_workers),
        interceptors=interceptors,
        options=[
            ("grpc.max_connection_age_ms", 300_000),  # let L4/L7 LBs rebalance
            ("grpc.keepalive_time_ms", 60_000),
            ("grpc.keepalive_permit_without_calls", 0),
        ],
    )
    telemetry_pb2_grpc.add_TelemetryServiceServicer_to_server(
        TelemetryService(), server
    )
    return server


def main() -> None:
    from error_middleware import ErrorMappingInterceptor

    parser = argparse.ArgumentParser(description="Telemetry gRPC server")
    parser.add_argument("--port", type=int, default=50051)
    args = parser.parse_args()
    server = make_server(interceptors=(ErrorMappingInterceptor(),))
    bound = server.add_insecure_port(f"localhost:{args.port}")
    server.start()
    print(f"telemetry server listening on localhost:{bound}")
    server.wait_for_termination()


if __name__ == "__main__":
    main()
