"""Listing 3 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Client for the Northwind Robotics telemetry service (Chapter 13).

Shows metadata, per-call deadline budgets, an auth + correlation-ID
interceptor, and a retry policy installed via gRPC service config.
Offline-first: localhost only.
"""
from __future__ import annotations

import itertools
import json
from dataclasses import dataclass
from typing import Any, Callable, Iterable, Iterator

import grpc

import telemetry_pb2
import telemetry_pb2_grpc

# Retry policy delivered through the channel's service config. Retries are
# bounded (maxAttempts) and restricted to UNAVAILABLE -- the only status here
# that is provably safe to retry for these non-idempotent methods when the
# attempt never reached the server.
RETRY_SERVICE_CONFIG = json.dumps(
    {
        "methodConfig": [
            {
                "name": [{"service": "northwind.telemetry.v1.TelemetryService"}],
                "retryPolicy": {
                    "maxAttempts": 3,
                    "initialBackoff": "0.050s",
                    "maxBackoff": "0.500s",
                    "backoffMultiplier": 2.0,
                    "retryableStatusCodes": ["UNAVAILABLE"],
                },
                # Overall per-RPC timeout when the caller sets none.
                "timeout": "2.000s",
            }
        ]
    }
)


@dataclass(frozen=True)
class _ClientCallDetails:
    """grpc.ClientCallDetails is an interface; this is our concrete copy."""

    method: str
    timeout: float | None
    metadata: tuple[tuple[str, Any], ...]
    credentials: Any
    wait_for_ready: bool | None
    compression: Any


class AuthMetadataInterceptor(
    grpc.UnaryUnaryClientInterceptor,
    grpc.UnaryStreamClientInterceptor,
    grpc.StreamUnaryClientInterceptor,
    grpc.StreamStreamClientInterceptor,
):
    """Attaches auth and correlation metadata to every outgoing RPC."""

    def __init__(
        self, token: str, correlation_factory: Callable[[], str]
    ) -> None:
        self._token = token
        self._correlation_factory = correlation_factory

    def _augment(
        self, details: grpc.ClientCallDetails
    ) -> _ClientCallDetails:
        metadata = tuple(details.metadata or ()) + (
            ("authorization", f"Bearer {self._token}"),
            ("x-correlation-id", self._correlation_factory()),
        )
        return _ClientCallDetails(
            method=details.method,
            timeout=details.timeout,
            metadata=metadata,
            credentials=details.credentials,
            wait_for_ready=details.wait_for_ready,
            compression=details.compression,
        )

    def intercept_unary_unary(self, continuation, client_call_details, request):
        return continuation(self._augment(client_call_details), request)

    def intercept_unary_stream(self, continuation, client_call_details, request):
        return continuation(self._augment(client_call_details), request)

    def intercept_stream_unary(
        self, continuation, client_call_details, request_iterator
    ):
        return continuation(self._augment(client_call_details), request_iterator)

    def intercept_stream_stream(
        self, continuation, client_call_details, request_iterator
    ):
        return continuation(self._augment(client_call_details), request_iterator)


def make_channel(
    address: str,
    token: str = "synthetic-dev-token",
    correlation_factory: Callable[[], str] | None = None,
) -> grpc.Channel:
    """Channel with retries (service config) and the auth interceptor."""
    if correlation_factory is None:
        counter = itertools.count(1)

        def _next_id() -> str:
            return f"corr-{next(counter):06d}"

        correlation_factory = _next_id
    options = [
        ("grpc.enable_retries", 1),
        ("grpc.service_config", RETRY_SERVICE_CONFIG),
        ("grpc.keepalive_time_ms", 60_000),
    ]
    raw = grpc.insecure_channel(address, options=options)
    return grpc.intercept_channel(
        raw, AuthMetadataInterceptor(token, correlation_factory)
    )


def fetch_status(
    stub: telemetry_pb2_grpc.TelemetryServiceStub,
    robot_id: str,
    deadline_s: float = 1.0,
) -> telemetry_pb2.RobotStatusReply:
    """Unary call with an explicit deadline budget."""
    request = telemetry_pb2.RobotStatusRequest(robot_id=robot_id)
    return stub.GetRobotStatus(request, timeout=deadline_s)


def stream_frames(
    stub: telemetry_pb2_grpc.TelemetryServiceStub,
    robot_id: str,
    max_frames: int,
    deadline_s: float = 5.0,
) -> Iterator[telemetry_pb2.TelemetryFrame]:
    request = telemetry_pb2.StreamTelemetryRequest(
        robot_id=robot_id, max_frames=max_frames, period_ms=20
    )
    yield from stub.StreamTelemetry(request, timeout=deadline_s)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Telemetry gRPC client demo")
    parser.add_argument("--port", type=int, default=50051)
    args = parser.parse_args()
    channel = make_channel(f"localhost:{args.port}")
    stub = telemetry_pb2_grpc.TelemetryServiceStub(channel)

    reply = fetch_status(stub, "RB-1001", deadline_s=1.0)
    mode = telemetry_pb2.RobotMode.Name(reply.mode)
    print(f"status: {reply.robot_id} mode={mode} battery={reply.battery_pct:.2f}%")

    print("stream:")
    for frame in stream_frames(stub, "RB-1001", max_frames=3):
        print(f"  frame battery={frame.battery_pct:.2f} mode={frame.mode}")

    frames = [
        telemetry_pb2.TelemetryFrame(robot_id="RB-1001", battery_pct=b)
        for b in (91.5, 90.8, 88.2)
    ]
    summary = stub.UploadTelemetry(iter(frames), timeout=2.0)
    print(f"upload: accepted={summary.accepted} rejected={summary.rejected}")
    channel.close()


if __name__ == "__main__":
    main()
