"""Listing 2 extracted from chapters/chapter_13_grpc_high_performance_rpc.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Server interceptor: map domain errors to gRPC status + rich details.

Rich details ride in the binary trailing-metadata key "error-details-bin",
the same transport trick Google APIs use for google.rpc.Status in
"grpc-status-details-bin". A client helper decodes them back.
"""
from __future__ import annotations

from typing import Any, Callable

import grpc

import telemetry_pb2
from telemetry_server import DomainError

TRAILER_KEY = "error-details-bin"


def _correlation_id(context: grpc.ServicerContext) -> str:
    for key, value in context.invocation_metadata():
        if key == "x-correlation-id":
            return str(value)
    return ""


def _abort_with_details(
    context: grpc.ServicerContext, err: DomainError
) -> None:
    details = telemetry_pb2.ErrorDetails(
        reason=err.reason,
        domain="telemetry.northwind.example",
        correlation_id=_correlation_id(context),
    )
    details.violations.extend(err.violations)
    context.set_trailing_metadata(
        ((TRAILER_KEY, details.SerializeToString()),)
    )
    context.abort(err.status_code, err.message)


def _wrap_unary(behavior: Callable) -> Callable:
    def handler(request: Any, context: grpc.ServicerContext) -> Any:
        try:
            return behavior(request, context)
        except DomainError as err:
            _abort_with_details(context, err)

    return handler


def _wrap_stream(behavior: Callable) -> Callable:
    def handler(request_or_iter: Any, context: grpc.ServicerContext) -> Any:
        try:
            yield from behavior(request_or_iter, context)
        except DomainError as err:
            _abort_with_details(context, err)

    return handler


class ErrorMappingInterceptor(grpc.ServerInterceptor):
    """Rebuilds each handler so DomainError becomes status + rich details."""

    def intercept_service(self, continuation, handler_call_details):
        handler = continuation(handler_call_details)
        if handler is None:
            return None
        deserializer = handler.request_deserializer
        serializer = handler.response_serializer
        if handler.request_streaming and handler.response_streaming:
            return grpc.stream_stream_rpc_method_handler(
                _wrap_stream(handler.stream_stream),
                request_deserializer=deserializer,
                response_serializer=serializer,
            )
        if handler.request_streaming:
            return grpc.stream_unary_rpc_method_handler(
                _wrap_unary(handler.stream_unary),
                request_deserializer=deserializer,
                response_serializer=serializer,
            )
        if handler.response_streaming:
            return grpc.unary_stream_rpc_method_handler(
                _wrap_stream(handler.unary_stream),
                request_deserializer=deserializer,
                response_serializer=serializer,
            )
        return grpc.unary_unary_rpc_method_handler(
            _wrap_unary(handler.unary_unary),
            request_deserializer=deserializer,
            response_serializer=serializer,
        )


def decode_error_details(
    call_or_error: Any,
) -> telemetry_pb2.ErrorDetails | None:
    """Client side: pull ErrorDetails out of a failed call's trailers."""
    metadata = call_or_error.trailing_metadata() or ()
    for key, value in metadata:
        if key == TRAILER_KEY:
            details = telemetry_pb2.ErrorDetails()
            details.ParseFromString(value)
            return details
    return None
