"""Listing 3 extracted from chapters/chapter_00_introduction.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Northwind Robotics parts API + client, stdlib-only and fully offline.

Server:  GET /healthz                 -> {"status": "ok"}
         GET /v1/parts                -> {"items": [...]}
         GET /v1/parts/<sku>          -> part object or RFC-shaped error
Client:  typed functions with explicit timeouts and error mapping.

Run server:  python mini_api.py serve --port 8000
Run client demo (spawns server in-process):  python mini_api.py demo
"""
from __future__ import annotations

import argparse
import json
import logging
import threading
import urllib.error
import urllib.request
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

logger = logging.getLogger("mini_api")

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
CLIENT_TIMEOUT_S = 2.0  # every network call in this book carries a timeout

# Synthetic fixture data (Northwind Robotics universe). No real PII.
PARTS: dict[str, dict[str, Any]] = {
    "NR-AXLE-001": {"sku": "NR-AXLE-001", "name": "Drive axle, Mk IV",
                    "unit_price_cents": 4599, "stock": 37},
    "NR-LIDAR-204": {"sku": "NR-LIDAR-204", "name": "LiDAR puck, 16-channel",
                     "unit_price_cents": 189900, "stock": 4},
    "NR-GRIP-011": {"sku": "NR-GRIP-011", "name": "Parallel gripper jaw",
                    "unit_price_cents": 12350, "stock": 120},
}


def problem(status: int, title: str, detail: str) -> bytes:
    """RFC 9457-flavored error body (formalized in Chapter 7)."""
    body = {
        "type": "about:blank",
        "title": title,
        "status": status,
        "detail": detail,
    }
    return json.dumps(body).encode("utf-8")


class PartsHandler(BaseHTTPRequestHandler):
    server_version = "NorthwindParts/0.1"

    def log_message(self, fmt: str, *args: Any) -> None:
        logger.info("%s - %s", self.address_string(), fmt % args)

    def _send_json(self, status: int, payload: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_GET(self) -> None:  # noqa: N802 -- stdlib naming contract
        if self.path == "/healthz":
            self._send_json(200, json.dumps({"status": "ok"}).encode())
            return
        if self.path == "/v1/parts":
            payload = json.dumps({"items": list(PARTS.values())}).encode()
            self._send_json(200, payload)
            return
        if self.path.startswith("/v1/parts/"):
            sku = self.path.removeprefix("/v1/parts/").strip()
            part = PARTS.get(sku)
            if part is None:
                self._send_json(404, problem(
                    404, "Not Found", f"no part with sku '{sku}'"))
                return
            self._send_json(200, json.dumps(part).encode())
            return
        self._send_json(404, problem(
            404, "Not Found", f"unknown path '{self.path}'"))


def make_server(host: str = DEFAULT_HOST,
                port: int = DEFAULT_PORT) -> ThreadingHTTPServer:
    return ThreadingHTTPServer((host, port), PartsHandler)


# ------------------------------- client side -------------------------------

class ApiClientError(RuntimeError):
    """Base class for client-side failures."""


class ApiHttpError(ApiClientError):
    """The server answered with a non-2xx status."""

    def __init__(self, status: int, detail: str) -> None:
        super().__init__(f"HTTP {status}: {detail}")
        self.status = status
        self.detail = detail


@dataclass(frozen=True)
class PartsClient:
    """Minimal typed client for the parts API."""

    base_url: str = f"http://{DEFAULT_HOST}:{DEFAULT_PORT}"
    timeout_s: float = CLIENT_TIMEOUT_S

    def _get_json(self, path: str) -> Any:
        if not path.startswith("/"):
            raise ValueError(f"path must start with '/', got {path!r}")
        request = urllib.request.Request(self.base_url + path, method="GET")
        try:
            with urllib.request.urlopen(request,
                                        timeout=self.timeout_s) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise ApiHttpError(exc.code, detail) from exc
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            raise ApiClientError(f"transport failure: {exc}") from exc

    def health(self) -> bool:
        return self._get_json("/healthz")["status"] == "ok"

    def list_parts(self) -> list[dict[str, Any]]:
        return list(self._get_json("/v1/parts")["items"])

    def get_part(self, sku: str) -> dict[str, Any]:
        if not sku:
            raise ValueError("sku must be non-empty")
        return dict(self._get_json(f"/v1/parts/{sku}"))


def demo() -> int:
    """Start the server in-process and exercise the client. Offline."""
    server = make_server()
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        client = PartsClient()
        logger.info("health: %s", client.health())
        parts = client.list_parts()
        logger.info("catalog size: %d", len(parts))
        part = client.get_part("NR-LIDAR-204")
        logger.info("fetched: %s (%d cents)",
                    part["name"], part["unit_price_cents"])
        try:
            client.get_part("NO-SUCH-SKU")
        except ApiHttpError as exc:
            logger.info("expected 404 mapped cleanly: status=%d", exc.status)
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2.0)
    return 0


def main() -> int:
    logging.basicConfig(level=logging.INFO,
                        format="%(levelname)-7s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    serve = sub.add_parser("serve", help="run the server in the foreground")
    serve.add_argument("--port", type=int, default=DEFAULT_PORT)
    sub.add_parser("demo", help="in-process server + client round trip")
    args = parser.parse_args()

    if args.command == "serve":
        if not 1024 <= args.port <= 65535:
            parser.error("port must be in [1024, 65535]")
        server = make_server(port=args.port)
        logger.info("serving on http://%s:%d", DEFAULT_HOST, args.port)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            logger.info("shutting down")
        finally:
            server.server_close()
        return 0
    return demo()


if __name__ == "__main__":
    raise SystemExit(main())
