"""Listing 4 extracted from chapters/chapter_00_introduction.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Lab 0 measurement driver: benchmark the stdlib client end to end."""
from __future__ import annotations

import logging
import threading

from bench import run_benchmark
from mini_api import PartsClient, make_server

logger = logging.getLogger("lab0")


def main() -> int:
    logging.basicConfig(level=logging.INFO,
                        format="%(levelname)-7s %(message)s")
    server = make_server(port=8000)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        client = PartsClient(base_url="http://127.0.0.1:8000")
        result = run_benchmark(
            lambda: client.get_part("NR-AXLE-001"),
            samples=500, warmup=50, label="stdlib-local",
        )
        for key, value in result.summary().items():
            logger.info("%-16s %s", key, value)
        if result.errors != 0:
            logger.error("expected zero errors on localhost, got %d",
                         result.errors)
            return 1
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2.0)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
