"""Listing 1 extracted from chapters/chapter_00_introduction.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Environment sanity check for the API curriculum (offline, stdlib-only).

Verifies: interpreter version, required packages, localhost port
availability, and writes a structured report via logging.
Run:  python sanity_check.py
Exit code 0 means the environment is ready for every lab in the book.
"""
from __future__ import annotations

import importlib.util
import logging
import socket
import sys
from dataclasses import dataclass, field

MIN_PYTHON: tuple[int, int] = (3, 11)
REQUIRED_PACKAGES: tuple[str, ...] = (
    "fastapi", "uvicorn", "httpx", "pydantic", "pytest",
)
REQUIRED_PORTS: tuple[int, ...] = (8000, 8001, 8765)

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)-7s %(message)s",
)
logger = logging.getLogger("sanity_check")


@dataclass
class CheckReport:
    """Accumulates named check results for a final verdict."""

    failures: list[str] = field(default_factory=list)

    def record(self, name: str, ok: bool, detail: str) -> None:
        status = "PASS" if ok else "FAIL"
        logger.info("[%s] %s: %s", status, name, detail)
        if not ok:
            self.failures.append(name)


def check_python_version(report: CheckReport) -> None:
    current = sys.version_info[:2]
    ok = current >= MIN_PYTHON
    detail = f"found {current[0]}.{current[1]}, require >= {MIN_PYTHON[0]}.{MIN_PYTHON[1]}"
    report.record("python-version", ok, detail)


def check_packages(report: CheckReport) -> None:
    for package in REQUIRED_PACKAGES:
        found = importlib.util.find_spec(package) is not None
        detail = "importable" if found else "NOT INSTALLED"
        report.record(f"package:{package}", found, detail)


def check_port_available(port: int) -> tuple[bool, str]:
    """A port is 'available' if we can bind it on loopback right now."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            probe.bind(("127.0.0.1", port))
        return True, "free"
    except OSError as exc:
        return False, f"unavailable ({exc.strerror or exc})"


def check_ports(report: CheckReport) -> None:
    for port in REQUIRED_PORTS:
        ok, detail = check_port_available(port)
        report.record(f"port:{port}", ok, detail)


def main() -> int:
    report = CheckReport()
    check_python_version(report)
    check_packages(report)
    check_ports(report)
    if report.failures:
        logger.error("Environment NOT ready; failed checks: %s",
                     ", ".join(report.failures))
        return 1
    logger.info("Environment ready for all labs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
