"""Listing 4 extracted from chapters/chapter_17_deployment_infrastructure.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Canary analysis: error-rate delta + Wald SPRT promote/rollback decision.

Given a stable baseline metric series and a canary metric series (synthetic
fixtures generated with fixed seeds), this script computes, per analysis
batch:

* the canary/baseline error-rate delta,
* a Wald Sequential Probability Ratio Test (SPRT) on Bernoulli error
  events, which decides PROMOTE (canary no worse) or ROLLBACK (canary
  regressed by at least delta) as soon as the evidence crosses a boundary,
* a hard latency gate: batch p95 must stay within 25% of baseline p95.

Stdlib only, fully deterministic: every run prints identical output.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass

# Configuration (the numbers an SRE would set in the rollout policy)
BATCH_SIZE = 200           # canary requests analyzed per gate evaluation
MAX_BATCHES = 10           # give up (hold) if still undecided after this many
DELTA = 0.010              # H1: canary error rate worse by >= 1 percentage pt
ALPHA = 0.05               # false-promote probability budget
BETA = 0.05                # false-rollback probability budget
LATENCY_P95_FACTOR = 1.25  # hard gate: canary p95 <= baseline p95 * 1.25


@dataclass(frozen=True)
class Event:
    latency_ms: float
    error: bool


def synth_series(n: int, mean_latency: float, jitter: float,
                 error_rate: float, seed: int) -> list[Event]:
    """Deterministic synthetic request series (lognormal-ish latencies)."""
    rng = random.Random(seed)
    series: list[Event] = []
    for _ in range(n):
        latency = mean_latency + 10.0 * rng.lognormvariate(0.0, jitter)
        series.append(Event(round(latency, 1), rng.random() < error_rate))
    return series


def percentile(sorted_values: list[float], pct: float) -> float:
    """Nearest-rank percentile; input must already be sorted ascending."""
    if not sorted_values:
        raise ValueError("percentile of empty series")
    rank = max(1, math.ceil(pct / 100.0 * len(sorted_values)))
    return sorted_values[rank - 1]


class BernoulliSPRT:
    """Wald's sequential test: H0 (p = p0) vs H1 (p = p1 = p0 + delta)."""

    def __init__(self, p0: float, p1: float, alpha: float, beta: float) -> None:
        if not (0.0 < p0 < p1 < 1.0):
            raise ValueError("require 0 < p0 < p1 < 1")
        self.p0, self.p1 = p0, p1
        self.upper = math.log((1.0 - beta) / alpha)   # rollback boundary
        self.lower = math.log(beta / (1.0 - alpha))   # promote boundary
        self.llr = 0.0
        self.errors = 0
        self.total = 0

    def observe(self, error: bool) -> None:
        self.total += 1
        if error:
            self.errors += 1
            self.llr += math.log(self.p1 / self.p0)
        else:
            self.llr += math.log((1.0 - self.p1) / (1.0 - self.p0))

    def verdict(self) -> str:
        if self.llr >= self.upper:
            return "ROLLBACK"
        if self.llr <= self.lower:
            return "PROMOTE"
        return "CONTINUE"


def analyze(label: str, baseline: list[Event], canary: list[Event]) -> str:
    base_errors = sum(1 for e in baseline if e.error)
    p0 = base_errors / len(baseline)
    base_lat = sorted(e.latency_ms for e in baseline)
    base_p95 = percentile(base_lat, 95)
    p95_limit = base_p95 * LATENCY_P95_FACTOR

    print("=" * 74)
    print(f"FIXTURE: {label}")
    print(f"baseline: {len(baseline)} reqs, {base_errors} errors "
          f"({p0:.2%}), p50={percentile(base_lat, 50):.1f} ms, "
          f"p95={base_p95:.1f} ms")
    print(f"H0: p_canary = {p0:.2%}   H1: p_canary >= {p0 + DELTA:.2%}   "
          f"alpha=beta={ALPHA}   latency gate: p95 <= {p95_limit:.1f} ms")
    print("-" * 74)
    print(f"{'batch':>5} {'reqs':>5} {'errors':>6} {'err-rate':>9} "
          f"{'delta':>8} {'p95 ms':>8} {'lat-gate':>8} {'LLR':>8}  decision")
    print("-" * 74)

    sprt = BernoulliSPRT(p0, p0 + DELTA, ALPHA, BETA)
    final = "HOLD (inconclusive after max batches)"
    for batch_no in range(1, MAX_BATCHES + 1):
        lo, hi = (batch_no - 1) * BATCH_SIZE, batch_no * BATCH_SIZE
        batch = canary[lo:hi]
        if not batch:
            break
        latency_breach = False
        for event in batch:
            sprt.observe(event.error)
        batch_lat = sorted(e.latency_ms for e in batch)
        batch_p95 = percentile(batch_lat, 95)
        if batch_p95 > p95_limit:
            latency_breach = True
        err_rate = sprt.errors / sprt.total
        delta = err_rate - p0
        verdict = sprt.verdict()
        print(f"{batch_no:>5} {sprt.total:>5} {sprt.errors:>6} "
              f"{err_rate:>9.2%} {delta:>+8.2%} {batch_p95:>8.1f} "
              f"{'BREACH' if latency_breach else 'ok':>8} "
              f"{sprt.llr:>8.3f}  {verdict}")
        if latency_breach:
            final = f"ROLLBACK (latency gate breached at batch {batch_no})"
            break
        if verdict == "ROLLBACK":
            final = (f"ROLLBACK (error regression detected at batch "
                     f"{batch_no}, {sprt.total} canary requests)")
            break
        if verdict == "PROMOTE":
            final = (f"PROMOTE (error parity proven at batch {batch_no}, "
                     f"{sprt.total} canary requests)")
            break
    print("-" * 74)
    print(f"FINAL DECISION: {final}")
    print()
    return final


def main() -> None:
    print("Canary analysis -- Northwind Robotics Orders API rollout")
    print(f"policy: batches of {BATCH_SIZE}, error delta >= {DELTA:.1%} "
          f"rolls back, p95 latency x{LATENCY_P95_FACTOR} rolls back")
    print()

    baseline = synth_series(4000, mean_latency=45.0, jitter=0.6,
                            error_rate=0.004, seed=2026)

    good = synth_series(MAX_BATCHES * BATCH_SIZE, mean_latency=47.0,
                        jitter=0.6, error_rate=0.004, seed=1701)
    analyze("canary v2.4.1 -- healthy (error parity, latency parity)",
            baseline, good)

    bad = synth_series(MAX_BATCHES * BATCH_SIZE, mean_latency=58.0,
                       jitter=0.6, error_rate=0.014, seed=1702)
    analyze("canary v2.4.2 -- regressed (error rate 3.5x baseline)",
            baseline, bad)


if __name__ == "__main__":
    main()
