"""Listing 1 extracted from chapters/chapter_17_deployment_infrastructure.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Northwind Robotics Orders API -- used to demonstrate graceful shutdown.

Run standalone (``python orders_server.py``) or under the driver in
``shutdown_demo.py``. Every response carries three diagnostic headers so an
outside observer can prove what happened to in-flight work during a
termination signal:

* ``X-Request-Id`` -- monotonically increasing request identifier.
* ``X-In-Flight-Remaining`` -- requests still in flight after this one.
* ``X-Elapsed-Ms`` -- server-side wall time for the request.
"""

from __future__ import annotations

import asyncio
import itertools
import time

from fastapi import FastAPI, Request, Response

app = FastAPI(title="Northwind Robotics Orders API")

IN_FLIGHT: dict[int, str] = {}
_request_ids = itertools.count(1)


@app.middleware("http")
async def track_in_flight(request: Request, call_next) -> Response:
    """Ledger middleware: register on entry, deregister on exit."""
    rid = next(_request_ids)
    IN_FLIGHT[rid] = f"{request.method} {request.url.path}"
    started = time.perf_counter()
    try:
        response = await call_next(request)
    finally:
        IN_FLIGHT.pop(rid, None)
    response.headers["X-Request-Id"] = str(rid)
    response.headers["X-In-Flight-Remaining"] = str(len(IN_FLIGHT))
    response.headers["X-Elapsed-Ms"] = f"{(time.perf_counter() - started) * 1000:.0f}"
    return response


@app.get("/healthz")
async def healthz() -> dict[str, bool]:
    """Cheap probe endpoint: process is alive and the event loop turns."""
    return {"ok": True}


@app.post("/orders", status_code=201)
async def create_order() -> dict[str, str]:
    """Fast path: a normal order write."""
    await asyncio.sleep(0.05)  # simulated database round trip
    return {"order_id": "ord-1042", "status": "accepted"}


@app.get("/orders/export")
async def export_orders() -> dict[str, object]:
    """Slow path: a five-second report, one simulated chunk per second.

    This endpoint exists to be *in flight* when the termination signal
    arrives; whether it completes is the whole point of the demo.
    """
    chunks = 0
    for _ in range(5):
        await asyncio.sleep(1.0)  # one chunk of report work per second
        chunks += 1
    return {
        "report": "orders",
        "chunks_completed": chunks,
        "in_flight_at_finish": len(IN_FLIGHT),
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8571, log_level="warning")
