"""Listing 3 extracted from chapters/chapter_17_deployment_infrastructure.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Kubernetes probe-semantics simulator (offline, stdlib-only, deterministic).

Two scenarios run over the same world:

  A. WITH a startup probe: slow boots are tolerated; a deadlock is
     detected by liveness and fixed by a restart; a dependency outage
     only removes the Pod from Service endpoints (no restart).
  B. WITHOUT a startup probe (the copy-paste anti-pattern where the
     liveness probe doubles as the startup check): a 45-second cold boot
     exceeds the liveness budget, so the kubelet kills the container
     before it ever serves -- CrashLoopBackOff.

The clock is virtual (one-second ticks), so every run prints byte-for-byte
identical output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

SIM_SECONDS = 240
MAX_RESTARTS = 2  # afterwards the kubelet backs off (CrashLoopBackOff)


class Mode(Enum):
    BOOTING = "booting"          # process alive, app still initializing
    HEALTHY = "healthy"
    DEP_DOWN = "dep_down"        # dependency down: /ready fails, /live fine
    DEADLOCKED = "deadlocked"    # event loop stuck: every probe times out


@dataclass(frozen=True)
class ProbeSpec:
    name: str
    period_seconds: int
    failure_threshold: int
    success_threshold: int = 1


STARTUP = ProbeSpec("startup", period_seconds=5, failure_threshold=12)  # 60 s
READINESS = ProbeSpec("readiness", period_seconds=5, failure_threshold=3)
LIVENESS = ProbeSpec("liveness", period_seconds=10, failure_threshold=3)

# The fault environment: (start_s, end_s, mode once booted).
TIMELINE: list[tuple[int, int, Mode]] = [
    (0, 60, Mode.HEALTHY),
    (60, 95, Mode.DEP_DOWN),       # 35 s database outage
    (95, 150, Mode.HEALTHY),
    (150, 10_000, Mode.DEADLOCKED),  # transient deadlock; a restart cures it
]


def timeline_mode(t: int) -> Mode:
    for start, end, mode in TIMELINE:
        if start <= t < end:
            return mode
    return Mode.HEALTHY


@dataclass
class SimResult:
    label: str
    events: list[str] = field(default_factory=list)
    restarts: int = 0
    traffic_seconds: int = 0
    ready_at_end: bool = False


def run_scenario(label: str, use_startup_probe: bool, boot_seconds: int,
                 reboot_seconds: int) -> SimResult:
    """Simulate one Pod. Returns an event log plus routing statistics."""
    result = SimResult(label=label)

    boot_started = 0
    boot_len = boot_seconds
    booted = False          # startup check has passed at least once
    ready = False           # Pod is a member of the Service endpoints
    deadlock_cleared = False  # restarts cure process-local deadlocks
    crashlooped = False

    startup_fail = ready_fail = ready_ok = live_fail = 0

    def mode_at(t: int) -> Mode:
        if t - boot_started < boot_len:
            return Mode.BOOTING
        mode = timeline_mode(t)
        if mode is Mode.DEADLOCKED and deadlock_cleared:
            return Mode.HEALTHY
        return mode

    def restart(t: int, why: str) -> None:
        nonlocal boot_started, boot_len, booted, ready
        nonlocal startup_fail, ready_fail, ready_ok, live_fail
        nonlocal deadlock_cleared, crashlooped
        result.restarts += 1
        if result.restarts > MAX_RESTARTS:
            crashlooped = True
            result.events.append(
                f"t={t:3d}s  restart budget exhausted -> CrashLoopBackOff; "
                "kubelet backs off, Pod never becomes ready"
            )
            return
        result.events.append(f"t={t:3d}s  RESTART #{result.restarts} ({why})")
        boot_started, boot_len = t, reboot_seconds
        booted = ready = False
        startup_fail = ready_fail = ready_ok = live_fail = 0
        deadlock_cleared = True

    def set_ready(t: int, value: bool, why: str) -> None:
        nonlocal ready
        if ready != value:
            ready = value
            action = "ADDED TO" if value else "REMOVED FROM"
            result.events.append(
                f"t={t:3d}s  endpoints: Pod {action} Service rotation ({why})"
            )

    for t in range(1, SIM_SECONDS + 1):
        if crashlooped:
            break
        mode = mode_at(t)

        # --- startup probe (gates the other two) -------------------------
        if use_startup_probe and not booted and t % STARTUP.period_seconds == 0:
            if mode is not Mode.BOOTING:
                booted = True
                startup_fail = 0
                result.events.append(
                    f"t={t:3d}s  startup probe: first success -> "
                    "liveness/readiness probes begin"
                )
            else:
                startup_fail += 1
                if startup_fail >= STARTUP.failure_threshold:
                    restart(t, "startup probe exhausted its budget")

        probes_active = booted if use_startup_probe else True

        # --- readiness probe: endpoint membership only --------------------
        if probes_active and t % READINESS.period_seconds == 0:
            if mode is Mode.HEALTHY:
                ready_fail = 0
                ready_ok += 1
                if ready_ok >= READINESS.success_threshold:
                    set_ready(t, True, "readiness success")
            else:
                ready_ok = 0
                ready_fail += 1
                if ready_fail >= READINESS.failure_threshold:
                    set_ready(t, False, "readiness failing -- no restart!")

        # --- liveness probe: restart authority ----------------------------
        if probes_active and t % LIVENESS.period_seconds == 0:
            if mode in (Mode.HEALTHY, Mode.DEP_DOWN):
                live_fail = 0
            else:  # BOOTING (no startup probe) or DEADLOCKED: timeout
                live_fail += 1
                result.events.append(
                    f"t={t:3d}s  liveness probe: failure {live_fail}/"
                    f"{LIVENESS.failure_threshold} (mode={mode.value})"
                )
                if live_fail >= LIVENESS.failure_threshold:
                    why = ("deadlock detected" if mode is Mode.DEADLOCKED
                           else "killed while still booting")
                    restart(t, why)

        if ready:
            result.traffic_seconds += 1

    result.ready_at_end = ready
    return result


def report(result: SimResult) -> None:
    print("=" * 72)
    print(f"SCENARIO {result.label}")
    print("=" * 72)
    for line in result.events:
        print(" ", line)
    print("-" * 72)
    print(f"  restarts                    : {result.restarts}")
    print(f"  seconds receiving traffic   : {result.traffic_seconds} / {SIM_SECONDS}")
    print(f"  ready at end of simulation  : {result.ready_at_end}")
    print()


def main() -> None:
    print("Kubernetes probe-semantics simulator")
    print(f"probes: startup {STARTUP.period_seconds}s x{STARTUP.failure_threshold}, "
          f"readiness {READINESS.period_seconds}s x{READINESS.failure_threshold}, "
          f"liveness {LIVENESS.period_seconds}s x{LIVENESS.failure_threshold}")
    print("faults: 18s boot | dep outage t=60..95 | deadlock at t=150 "
          "(cured by restart)")
    print()

    with_startup = run_scenario(
        "A -- WITH startup probe (boot 18s tolerated)",
        use_startup_probe=True, boot_seconds=18, reboot_seconds=12,
    )
    report(with_startup)

    without_startup = run_scenario(
        "B -- WITHOUT startup probe (liveness doubles as boot check, boot 45s)",
        use_startup_probe=False, boot_seconds=45, reboot_seconds=45,
    )
    report(without_startup)

    print("LESSONS")
    print("  * DEP_DOWN caused readiness removal but ZERO restarts --")
    print("    restarting cannot fix someone else's outage.")
    print("  * DEADLOCKED caused a restart after 3 consecutive liveness")
    print("    failures -- liveness exists for process-local death.")
    print("  * Without a startup probe, a slow boot is indistinguishable from")
    print("    a deadlock, and the liveness budget becomes a boot deadline.")


if __name__ == "__main__":
    main()
