"""Listing 2 extracted from chapters/chapter_17_deployment_infrastructure.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Prove uvicorn's drain semantics: terminate a server mid-request.

Offline and deterministic in behavior: the driver starts
``orders_server.py`` as a child process, launches a slow ``/orders/export``
request (about five seconds), sends the termination signal roughly one
second in, and then verifies the three properties a graceful shutdown must
have, in order:

1. STOP ACCEPTING -- a brand-new request after the signal is refused.
2. DRAIN          -- the in-flight export finishes with HTTP 200.
3. EXIT           -- the server process terminates on its own.

Usage (PowerShell):  python shutdown_demo.py
Exit code 0 means all three properties held; 1 means a drain violation.
"""

from __future__ import annotations

import json
import os
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

HOST, PORT = "127.0.0.1", 8571
BASE = f"http://{HOST}:{PORT}"
SERVER_SCRIPT = Path(__file__).resolve().parent / "orders_server.py"

_step = 0


def log(message: str) -> None:
    """Print a numbered timeline line; numbering makes ordering explicit."""
    global _step
    _step += 1
    print(f"[{_step:02d}] {message}")


def get(path: str) -> tuple[int, dict[str, str], dict]:
    """Plain-stdlib GET returning (status, headers, parsed JSON body).

    Header keys are normalized to lowercase because ASGI servers emit
    lowercase field names on the wire.
    """
    with urllib.request.urlopen(f"{BASE}{path}", timeout=25.0) as resp:
        headers = {k.lower(): v for k, v in resp.headers.items()}
        return resp.status, headers, json.loads(resp.read())


def wait_ready(server: subprocess.Popen, timeout: float = 15.0) -> None:
    """Poll /healthz until the server answers or dies trying."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if server.poll() is not None:
            raise RuntimeError(f"server exited early, code {server.returncode}")
        try:
            status, _, _ = get("/healthz")
            if status == 200:
                return
        except (urllib.error.URLError, ConnectionError, OSError):
            time.sleep(0.25)
    raise TimeoutError("server did not become ready in time")


def main() -> int:
    creationflags = 0
    if os.name == "nt":
        # Give the child its own console process group so CTRL_BREAK_EVENT
        # reaches it (and only it) on Windows.
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP
    server = subprocess.Popen(
        [sys.executable, str(SERVER_SCRIPT)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=creationflags,
    )
    try:
        wait_ready(server)
        log("server ready; /healthz answers 200")

        outcome: dict[str, object] = {}

        def slow_call() -> None:
            try:
                status, headers, body = get("/orders/export")
                outcome["status"] = status
                outcome["elapsed_ms"] = headers.get("x-elapsed-ms", "?")
                outcome["chunks"] = body.get("chunks_completed")
            except (urllib.error.URLError, ConnectionError, OSError) as exc:
                outcome["error"] = f"{type(exc).__name__}: {exc}"

        worker = threading.Thread(target=slow_call, daemon=True)
        worker.start()
        time.sleep(1.2)  # the five-second export is now mid-flight

        if os.name == "nt":
            sig_name, sig = "CTRL_BREAK_EVENT", signal.CTRL_BREAK_EVENT
        else:
            sig_name, sig = "SIGTERM", signal.SIGTERM
        log(f"sending {sig_name} while the export is in flight")
        os.kill(server.pid, sig)

        time.sleep(0.3)
        log("attempting a NEW request after the signal")
        try:
            get("/healthz")
            new_blocked = False
            log("UNEXPECTED: a new request was accepted after the signal")
        except (urllib.error.URLError, ConnectionError, OSError) as exc:
            new_blocked = True
            log(f"new request refused as expected ({type(exc).__name__})")

        worker.join(timeout=25.0)
        if "error" in outcome:
            log(f"in-flight export FAILED: {outcome['error']}")
        else:
            log(
                "in-flight export completed: "
                f"HTTP {outcome.get('status')}, "
                f"elapsed {outcome.get('elapsed_ms')} ms, "
                f"chunks {outcome.get('chunks')}/5"
            )

        returncode = server.wait(timeout=25.0)
        log(f"server process exited on its own (code {returncode})")

        drained = outcome.get("status") == 200 and outcome.get("chunks") == 5
        print()
        print("VERDICT")
        print(f"  1. stop accepting first : {'PASS' if new_blocked else 'FAIL'}")
        print(f"  2. drain in-flight work : {'PASS' if drained else 'FAIL'}")
        print(f"  3. clean process exit   : {'PASS' if returncode is not None else 'FAIL'}")
        return 0 if (new_blocked and drained) else 1
    finally:
        if server.poll() is None:  # never leave an orphaned server behind
            server.kill()
            server.wait(timeout=10)


if __name__ == "__main__":
    raise SystemExit(main())
