"""Listing 1 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.1 -- SQLite-backed Idempotency-Key middleware for FastAPI.

Northwind Robotics Payments API. Offline-first, typed Python 3.11+.
Implements the IETF `Idempotency-Key` draft semantics:

* first request with a key executes and snapshots the response,
* same key + same payload replays the stored response,
* same key + different payload is rejected with 422,
* a concurrent duplicate while the first is in flight gets 409,
* keys expire after a configurable TTL (default: 24 hours, Stripe-style),
* keys are scoped per account (header ``X-Account-Id``).
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
import threading
import time
from dataclasses import dataclass
from typing import Optional

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field
from starlette.middleware.base import (
    BaseHTTPMiddleware,
    RequestResponseEndpoint,
)

IDEMPOTENCY_KEY_HEADER = "idempotency-key"
REPLAYED_HEADER = "idempotency-replayed"
DEFAULT_TTL_SECONDS = 24 * 60 * 60  # Stripe-style 24-hour key expiry
IDEMPOTENT_METHODS = frozenset({"POST", "PUT", "PATCH"})


# --------------------------------------------------------------------------
# Persistence: the idempotency key store
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class StoredResponse:
    """Immutable snapshot of a completed response."""

    status_code: int
    body: bytes
    content_type: str


class IdempotencyStore:
    """SQLite-backed key store.

    One row per (scope, key). Rows transition ``in_flight`` -> ``completed``.
    A single connection guarded by an RLock keeps concurrent handler
    threads serialized, so ``begin`` is an atomic check-and-insert.
    """

    def __init__(self, path: str = ":memory:", ttl_seconds: float = DEFAULT_TTL_SECONDS) -> None:
        self.ttl_seconds = ttl_seconds
        self._lock = threading.RLock()
        self._conn = sqlite3.connect(path, check_same_thread=False)
        self._conn.execute(
            """
            CREATE TABLE IF NOT EXISTS idempotency_keys (
                scope        TEXT NOT NULL,
                idem_key     TEXT NOT NULL,
                fingerprint  TEXT NOT NULL,
                state        TEXT NOT NULL CHECK (state IN ('in_flight', 'completed')),
                status_code  INTEGER,
                response_body BLOB,
                content_type TEXT,
                created_at   REAL NOT NULL,
                PRIMARY KEY (scope, idem_key)
            )
            """
        )
        self._conn.commit()

    def _prune_expired(self, now: float) -> None:
        self._conn.execute(
            "DELETE FROM idempotency_keys WHERE created_at + ? < ?",
            (self.ttl_seconds, now),
        )

    def begin(
        self, scope: str, key: str, fingerprint: str, now: Optional[float] = None
    ) -> tuple[str, Optional[StoredResponse]]:
        """Atomically claim a key or classify the collision.

        Returns one of:
          ("started",  None)   -- caller won the race and must execute,
          ("replay",   stored) -- same fingerprint, completed: replay it,
          ("mismatch", None)   -- same key, different payload: 422,
          ("in_flight", None)  -- same key in flight concurrently: 409.
        """
        now = time.time() if now is None else now
        with self._lock:
            self._prune_expired(now)
            try:
                self._conn.execute(
                    "INSERT INTO idempotency_keys"
                    " (scope, idem_key, fingerprint, state, created_at)"
                    " VALUES (?, ?, ?, 'in_flight', ?)",
                    (scope, key, fingerprint, now),
                )
                self._conn.commit()
                return ("started", None)
            except sqlite3.IntegrityError:
                row = self._conn.execute(
                    "SELECT fingerprint, state, status_code, response_body,"
                    "       content_type"
                    " FROM idempotency_keys WHERE scope = ? AND idem_key = ?",
                    (scope, key),
                ).fetchone()
            if row is None:  # pragma: no cover - defensive
                raise RuntimeError("idempotency row vanished mid-transaction")
            if row[0] != fingerprint:
                return ("mismatch", None)
            if row[1] == "in_flight":
                return ("in_flight", None)
            return ("replay", StoredResponse(row[2], bytes(row[3]), row[4]))

    def complete(
        self, scope: str, key: str, stored: StoredResponse
    ) -> None:
        """Attach the finished response snapshot to the claimed key."""
        with self._lock:
            self._conn.execute(
                "UPDATE idempotency_keys"
                " SET state = 'completed', status_code = ?,"
                "     response_body = ?, content_type = ?"
                " WHERE scope = ? AND idem_key = ? AND state = 'in_flight'",
                (stored.status_code, stored.body, stored.content_type, scope, key),
            )
            self._conn.commit()

    def abandon(self, scope: str, key: str) -> None:
        """Release the key after a 5xx/exception so the client may retry."""
        with self._lock:
            self._conn.execute(
                "DELETE FROM idempotency_keys"
                " WHERE scope = ? AND idem_key = ? AND state = 'in_flight'",
                (scope, key),
            )
            self._conn.commit()

    def close(self) -> None:
        with self._lock:
            self._conn.close()


def fingerprint_request(method: str, path: str, body: bytes) -> str:
    """SHA-256 over method + route + canonical body.

    Hashing only the body is a classic bug: the same JSON payload sent to
    two different endpoints must not collide, so the route is part of the
    fingerprint. JSON bodies are canonicalized so key order is irrelevant.
    """
    try:
        canonical = json.dumps(
            json.loads(body.decode("utf-8")), sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
    except (ValueError, UnicodeDecodeError):
        canonical = body
    digest = hashlib.sha256()
    digest.update(method.upper().encode("ascii"))
    digest.update(b"\x00")
    digest.update(path.encode("utf-8"))
    digest.update(b"\x00")
    digest.update(canonical)
    return digest.hexdigest()


def _problem(status: int, title: str, detail: str, type_slug: str) -> JSONResponse:
    return JSONResponse(
        status_code=status,
        media_type="application/problem+json",
        content={
            "type": f"https://api.northwind-robotics.example/problems/{type_slug}",
            "title": title,
            "status": status,
            "detail": detail,
        },
    )


class IdempotencyMiddleware(BaseHTTPMiddleware):
    """Applies Idempotency-Key semantics to unsafe methods."""

    def __init__(
        self,
        app: FastAPI,
        store: IdempotencyStore,
        methods: frozenset[str] = IDEMPOTENT_METHODS,
    ) -> None:
        super().__init__(app)
        self.store = store
        self.methods = methods

    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        key = request.headers.get(IDEMPOTENCY_KEY_HEADER)
        if request.method not in self.methods or not key:
            return await call_next(request)

        scope = request.headers.get("x-account-id", "anonymous")
        body = await request.body()
        fingerprint = fingerprint_request(request.method, request.url.path, body)

        outcome, stored = self.store.begin(scope, key, fingerprint)
        if outcome == "mismatch":
            return _problem(
                422,
                "Idempotency-key payload mismatch",
                "This Idempotency-Key was already used with a different request"
                " payload. Keys identify one logical request; mint a new key"
                " for a new operation.",
                "idempotency-key-mismatch",
            )
        if outcome == "in_flight":
            response = _problem(
                409,
                "Request with this idempotency key is in flight",
                "A concurrent request carrying the same Idempotency-Key is"
                " still being processed. Retry after a short backoff.",
                "idempotency-key-in-flight",
            )
            response.headers["Retry-After"] = "1"
            return response
        if outcome == "replay" and stored is not None:
            return Response(
                content=stored.body,
                status_code=stored.status_code,
                media_type=stored.content_type,
                headers={REPLAYED_HEADER: "true"},
            )

        # We claimed the key: execute and snapshot, or abandon on failure.
        try:
            downstream = await call_next(request)
            body_bytes = b""
            async for chunk in downstream.body_iterator:
                body_bytes += chunk
        except Exception:
            self.store.abandon(scope, key)
            raise

        content_type = downstream.headers.get("content-type", "application/json")
        if downstream.status_code < 500:
            self.store.complete(
                scope, key, StoredResponse(downstream.status_code, body_bytes, content_type)
            )
        else:
            # Server-side failures are never replayed; free the key.
            self.store.abandon(scope, key)
        return Response(
            content=body_bytes,
            status_code=downstream.status_code,
            media_type=content_type,
        )


# --------------------------------------------------------------------------
# Demo application: Northwind Robotics payments ledger
# --------------------------------------------------------------------------
class TransferRequest(BaseModel):
    """One funds movement between internal accounts."""

    from_account: str = Field(min_length=1)
    to_account: str = Field(min_length=1)
    amount_cents: int = Field(gt=0)


class TransferReceipt(BaseModel):
    transfer_id: str
    from_account: str
    to_account: str
    amount_cents: int
    sequence: int


class Ledger:
    """Thread-safe in-memory ledger; the observable side effect under test."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._transfers: list[TransferReceipt] = []

    def post(self, request: TransferRequest) -> TransferReceipt:
        with self._lock:
            receipt = TransferReceipt(
                transfer_id=f"tr_{len(self._transfers) + 1:06d}",
                from_account=request.from_account,
                to_account=request.to_account,
                amount_cents=request.amount_cents,
                sequence=len(self._transfers) + 1,
            )
            self._transfers.append(receipt)
            return receipt

    def count(self) -> int:
        with self._lock:
            return len(self._transfers)

    def total_cents(self) -> int:
        with self._lock:
            return sum(t.amount_cents for t in self._transfers)


def create_app(store: Optional[IdempotencyStore] = None) -> FastAPI:
    """Application factory; each test gets an isolated store + ledger."""
    app = FastAPI(title="Northwind Robotics Payments", version="1.0.0")
    app.state.store = store if store is not None else IdempotencyStore()
    app.state.ledger = Ledger()
    app.add_middleware(IdempotencyMiddleware, store=app.state.store)

    @app.post("/api/v1/payments/transfers", status_code=201)
    def create_transfer(payload: TransferRequest) -> TransferReceipt:
        return app.state.ledger.post(payload)

    return app
