"""Listing 3 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.2 -- Conditional requests: strong ETags and the 304 flow.

Northwind Robotics parts-catalog API. The ETag is a strong validator:
SHA-256 over the exact representation bytes, so any byte-level change of
the representation yields a new tag. The demo measures the bandwidth a
304 Not Modified saves on a repeat fetch. Offline, deterministic.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from fastapi import FastAPI, Request
from fastapi.responses import Response


def strong_etag(representation: bytes) -> str:
    """A strong validator: the quoted SHA-256 of the exact response bytes."""
    return '"' + hashlib.sha256(representation).hexdigest() + '"'


@dataclass
class PartRecord:
    sku: str
    name: str
    unit_price_cents: int
    stock: int

    def render(self) -> bytes:
        """Canonical JSON bytes: one state maps to exactly one byte string."""
        return json.dumps(
            {
                "sku": self.sku,
                "name": self.name,
                "unit_price_cents": self.unit_price_cents,
                "stock": self.stock,
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")


CATALOG: dict[str, PartRecord] = {
    "NWR-AXLE-42": PartRecord("NWR-AXLE-42", "Heavy-duty drive axle", 189_99, 35),
    "NWR-SERVO-7": PartRecord("NWR-SERVO-7", "Precision servo motor", 74_50, 212),
}


def create_app() -> FastAPI:
    app = FastAPI(title="Northwind Robotics Catalog", version="1.0.0")

    @app.get("/parts/{sku}")
    def get_part(sku: str, request: Request) -> Response:
        part = CATALOG.get(sku)
        if part is None:
            return Response(status_code=404)
        body = part.render()
        etag = strong_etag(body)
        headers = {
            "ETag": etag,
            "Cache-Control": "public, max-age=60",
        }
        if request.headers.get("if-none-match") == etag:
            # Validator matches: the client's copy is current. Send no body.
            return Response(status_code=304, headers=headers)
        return Response(
            content=body,
            media_type="application/json",
            headers=headers,
        )

    @app.post("/parts/{sku}/restock", status_code=200)
    def restock(sku: str, units: int) -> dict[str, object]:
        part = CATALOG[sku]
        part.stock += units  # state change -> new representation -> new ETag
        return {"sku": sku, "stock": part.stock}

    return app


def measure_conditional_savings() -> dict[str, int | float | bool]:
    """Fetch a part twice; the second fetch is a conditional GET.

    Returns byte counts proving the 304 path transfers no representation.
    """
    from fastapi.testclient import TestClient

    snapshot = CATALOG["NWR-AXLE-42"].stock  # keep the module fixture stable
    try:
        with TestClient(create_app()) as client:
            first = client.get("/parts/NWR-AXLE-42")
            assert first.status_code == 200
            etag = first.headers["etag"]
            first_bytes = len(first.content)

            second = client.get(
                "/parts/NWR-AXLE-42", headers={"If-None-Match": etag}
            )
            assert second.status_code == 304
            assert second.headers["etag"] == etag
            second_bytes = len(second.content)

            # The origin state changes: the old validator no longer matches.
            client.post("/parts/NWR-AXLE-42/restock", params={"units": 5})
            third = client.get(
                "/parts/NWR-AXLE-42", headers={"If-None-Match": etag}
            )
            assert third.status_code == 200
            assert third.headers["etag"] != etag

            saved_pct = 100.0 * (1 - second_bytes / first_bytes)
            return {
                "first_status": first.status_code,
                "first_bytes": first_bytes,
                "second_status": second.status_code,
                "second_bytes": second_bytes,
                "saved_pct": round(saved_pct, 1),
                "etag_rotated_after_restock": third.headers["etag"] != etag,
            }
    finally:
        CATALOG["NWR-AXLE-42"].stock = snapshot


if __name__ == "__main__":
    stats = measure_conditional_savings()
    print("Conditional-request bandwidth measurement")
    print("-----------------------------------------")
    print(f"initial GET      : {stats['first_status']} "
          f"({stats['first_bytes']} bytes)")
    print(f"conditional GET  : {stats['second_status']} "
          f"({stats['second_bytes']} bytes)")
    print(f"bandwidth saved  : {stats['saved_pct']}%")
    print(f"ETag rotated on write: {stats['etag_rotated_after_restock']}")
