"""Listing 2 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.1 test suite -- replay, mismatch, scope, and 50-thread storm.

Concurrency tests assert on final state and response equality only; a
threading.Barrier maximizes overlap without any timing dependence.
"""

from __future__ import annotations

import threading

import pytest
from fastapi.testclient import TestClient

from listing_10_1_idempotency_middleware import (
    REPLAYED_HEADER,
    IdempotencyStore,
    create_app,
    fingerprint_request,
)

PAYLOAD = {
    "from_account": "ops-checking",
    "to_account": "vendor-mecha-parts",
    "amount_cents": 2500,
}
KEY = "9b6f3c1e-6d3a-4a2f-9f6d-0d0f5f3d2a01"


@pytest.fixture()
def client() -> TestClient:
    app = create_app()
    with TestClient(app) as test_client:
        yield test_client


def test_first_request_executes_and_second_replays(client: TestClient) -> None:
    first = client.post(
        "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    assert first.status_code == 201
    assert REPLAYED_HEADER not in first.headers

    replay = client.post(
        "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    assert replay.status_code == 201
    assert replay.headers[REPLAYED_HEADER] == "true"
    assert replay.json() == first.json()
    assert client.app.state.ledger.count() == 1  # exactly-once effect


def test_same_key_different_payload_is_422(client: TestClient) -> None:
    client.post(
        "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    tampered = dict(PAYLOAD, amount_cents=9999)
    response = client.post(
        "/api/v1/payments/transfers", json=tampered, headers={"Idempotency-Key": KEY}
    )
    assert response.status_code == 422
    assert response.headers["content-type"].startswith("application/problem+json")
    assert client.app.state.ledger.count() == 1


def test_same_key_different_route_is_422(client: TestClient) -> None:
    """The fingerprint covers the route, not just the body."""
    client.post(
        "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    response = client.post(
        "/api/v1/payments/refunds", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    assert response.status_code == 422


def test_keys_are_scoped_per_account(client: TestClient) -> None:
    """The same key under another account is a different logical request."""
    client.post(
        "/api/v1/payments/transfers",
        json=PAYLOAD,
        headers={"Idempotency-Key": KEY, "X-Account-Id": "acct-alpha"},
    )
    other = client.post(
        "/api/v1/payments/transfers",
        json=PAYLOAD,
        headers={"Idempotency-Key": KEY, "X-Account-Id": "acct-beta"},
    )
    assert other.status_code == 201
    assert REPLAYED_HEADER not in other.headers
    assert client.app.state.ledger.count() == 2


def test_new_key_means_new_operation(client: TestClient) -> None:
    for key in ("key-a", "key-b"):
        response = client.post(
            "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": key}
        )
        assert response.status_code == 201
    assert client.app.state.ledger.count() == 2


def test_in_flight_key_returns_409(client: TestClient) -> None:
    """Deterministically seed an in-flight row, then collide with it."""
    import json as _json
    import time as _time

    store: IdempotencyStore = client.app.state.store
    body = _json.dumps(PAYLOAD).encode("utf-8")
    fingerprint = fingerprint_request("POST", "/api/v1/payments/transfers", body)
    outcome, _ = store.begin("anonymous", KEY, fingerprint, now=_time.time())
    assert outcome == "started"  # row is now 'in_flight', never completed

    response = client.post(
        "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
    )
    assert response.status_code == 409
    assert response.headers["Retry-After"] == "1"
    assert client.app.state.ledger.count() == 0


def test_expired_key_is_collected_and_reused(client: TestClient) -> None:
    store = IdempotencyStore(ttl_seconds=60)
    app = create_app(store=store)
    with TestClient(app) as expired_client:
        old = expired_client.post(
            "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
        )
        assert old.status_code == 201
        # Simulate time travel: age every row beyond the TTL.
        store._conn.execute("UPDATE idempotency_keys SET created_at = created_at - 120")
        store._conn.commit()
        again = expired_client.post(
            "/api/v1/payments/transfers", json=PAYLOAD, headers={"Idempotency-Key": KEY}
        )
        assert again.status_code == 201
        assert REPLAYED_HEADER not in again.headers  # expired: treated as new
        assert expired_client.app.state.ledger.count() == 2


def test_fifty_concurrent_duplicate_submits_mutate_once(client: TestClient) -> None:
    """50 threads, identical key + payload, released on one barrier.

    Exactly one transfer may exist at the end; every client must observe
    the same receipt body; exactly one response is a non-replayed origin
    response. Duplicates that arrive while the winner is in flight get
    409 and retry until the snapshot is available.
    """
    workers = 50
    barrier = threading.Barrier(workers)
    results: list[tuple[int, bytes, bool]] = []
    results_lock = threading.Lock()

    def submit() -> None:
        barrier.wait()
        attempts = 0
        while True:
            attempts += 1
            assert attempts < 200, "retry storm did not converge"
            response = client.post(
                "/api/v1/payments/transfers",
                json=PAYLOAD,
                headers={"Idempotency-Key": KEY},
            )
            if response.status_code == 409:
                continue  # winner still in flight; poll for the snapshot
            with results_lock:
                results.append(
                    (
                        response.status_code,
                        response.content,
                        response.headers.get(REPLAYED_HEADER) == "true",
                    )
                )
            return

    threads = [threading.Thread(target=submit) for _ in range(workers)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()

    assert client.app.state.ledger.count() == 1  # one observable mutation
    assert client.app.state.ledger.total_cents() == 2500
    assert len(results) == workers
    statuses = {status for status, _, _ in results}
    bodies = {body for _, body, _ in results}
    assert statuses == {201}
    assert len(bodies) == 1  # every caller received the identical receipt
    non_replayed = sum(1 for _, _, replayed in results if not replayed)
    assert non_replayed == 1  # exactly one origin execution
