"""Listing 4 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.2 tests -- ETag stability, 304 flow, rotation on mutation."""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from listing_10_2_conditional_requests import (
    CATALOG,
    create_app,
    measure_conditional_savings,
    strong_etag,
)


@pytest.fixture()
def client() -> TestClient:
    with TestClient(create_app()) as test_client:
        yield test_client
    CATALOG["NWR-AXLE-42"].stock = 35  # restore the seeded fixture


def test_strong_etag_is_content_addressed() -> None:
    assert strong_etag(b"payload") == strong_etag(b"payload")
    assert strong_etag(b"payload") != strong_etag(b"payloae")
    assert strong_etag(b"x").startswith('"') and strong_etag(b"x").endswith('"')


def test_repeat_get_yields_identical_etag(client: TestClient) -> None:
    one = client.get("/parts/NWR-AXLE-42")
    two = client.get("/parts/NWR-AXLE-42")
    assert one.headers["etag"] == two.headers["etag"]
    assert one.headers["cache-control"] == "public, max-age=60"


def test_if_none_match_short_circuits_to_304(client: TestClient) -> None:
    etag = client.get("/parts/NWR-SERVO-7").headers["etag"]
    response = client.get("/parts/NWR-SERVO-7", headers={"If-None-Match": etag})
    assert response.status_code == 304
    assert response.content == b""
    assert response.headers["etag"] == etag  # 304 still carries validators


def test_mutation_rotates_etag_and_invalidates_cache(client: TestClient) -> None:
    before = client.get("/parts/NWR-AXLE-42")
    client.post("/parts/NWR-AXLE-42/restock", params={"units": 10})
    after = client.get(
        "/parts/NWR-AXLE-42", headers={"If-None-Match": before.headers["etag"]}
    )
    assert after.status_code == 200
    assert after.headers["etag"] != before.headers["etag"]
    assert after.json()["stock"] == 45


def test_unknown_part_is_404(client: TestClient) -> None:
    assert client.get("/parts/NOPE-1").status_code == 404


def test_demo_reports_full_savings() -> None:
    stats = measure_conditional_savings()
    assert stats["second_status"] == 304
    assert stats["second_bytes"] == 0
    assert stats["saved_pct"] == 100.0
    assert stats["etag_rotated_after_restock"] is True
