"""Listing 5 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.3 -- Optimistic locking with If-Match on an inventory API.

Northwind Robotics warehouse inventory. Every representation carries a
version-derived ETag (``"v3"``). Writes must present ``If-Match``:

* header missing           -> 428 Precondition Required,
* header does not match    -> 412 Precondition Failed (lost update refused),
* header matches           -> write applied, version incremented.

The version counter is a strong validator here because the representation
is a pure function of the stored state: equal versions imply byte-identical
bodies. Offline, deterministic.
"""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel, Field


@dataclass
class InventoryRecord:
    sku: str
    quantity: int
    version: int

    def render(self) -> bytes:
        return json.dumps(
            {"sku": self.sku, "quantity": self.quantity, "version": self.version},
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")

    @property
    def etag(self) -> str:
        return f'"v{self.version}"'


class InventoryStore:
    """Thread-safe in-memory inventory keyed by SKU."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._records = {
            "NWR-AXLE-42": InventoryRecord("NWR-AXLE-42", quantity=35, version=1),
            "NWR-SERVO-7": InventoryRecord("NWR-SERVO-7", quantity=212, version=1),
        }

    def get(self, sku: str) -> InventoryRecord | None:
        with self._lock:
            record = self._records.get(sku)
            if record is None:
                return None
            return InventoryRecord(record.sku, record.quantity, record.version)

    def compare_and_swap(
        self, sku: str, expected_etag: str, new_quantity: int
    ) -> tuple[str, InventoryRecord | None]:
        """Atomic check-and-set. Returns ('not_found'|'mismatch'|'updated', record)."""
        with self._lock:
            record = self._records.get(sku)
            if record is None:
                return ("not_found", None)
            if record.etag != expected_etag:
                return (
                    "mismatch",
                    InventoryRecord(record.sku, record.quantity, record.version),
                )
            updated = InventoryRecord(sku, new_quantity, record.version + 1)
            self._records[sku] = updated
            return ("updated", updated)


def _problem(status: int, title: str, detail: str, slug: str) -> JSONResponse:
    return JSONResponse(
        status_code=status,
        media_type="application/problem+json",
        content={
            "type": f"https://api.northwind-robotics.example/problems/{slug}",
            "title": title,
            "status": status,
            "detail": detail,
        },
    )


class InventoryUpdate(BaseModel):
    quantity: int = Field(ge=0)


def create_app() -> FastAPI:
    app = FastAPI(title="Northwind Robotics Inventory", version="1.0.0")
    app.state.store = InventoryStore()

    @app.get("/inventory/{sku}")
    def get_inventory(sku: str) -> Response:
        record = app.state.store.get(sku)
        if record is None:
            return Response(status_code=404)
        return Response(
            content=record.render(),
            media_type="application/json",
            headers={"ETag": record.etag},
        )

    @app.put("/inventory/{sku}")
    def put_inventory(
        sku: str, payload: InventoryUpdate, request: Request
    ) -> Response:
        if_match = request.headers.get("if-match")
        if if_match is None:
            return _problem(
                428,
                "Precondition required",
                "Writes to this resource must be conditional: send If-Match"
                " with the ETag of the representation you based your edit on.",
                "precondition-required",
            )
        outcome, record = app.state.store.compare_and_swap(
            sku, if_match, payload.quantity
        )
        if outcome == "not_found":
            return Response(status_code=404)
        if outcome == "mismatch" and record is not None:
            return _problem(
                412,
                "Precondition failed",
                "The resource changed since your copy: current ETag is"
                f" {record.etag}, you sent If-Match: {if_match}. Re-read,"
                " re-decide, and retry.",
                "precondition-failed",
            )
        assert record is not None
        return Response(
            content=record.render(),
            media_type="application/json",
            headers={"ETag": record.etag},
        )

    return app
