"""Listing 7 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.4 -- Double-submit storm harness.

Reproduces the classic checkout bug -- a user double-clicks "Pay", the
load balancer retries a timed-out request, or a mobile client re-sends on
flaky Wi-Fi -- and proves that an Idempotency-Key turns a storm of N
duplicate requests into exactly one observable mutation.

The harness is deterministic: workers are released on one
threading.Barrier, retries on 409 are state-driven (poll until the winner
publishes its snapshot), and every assertion is on final state, never on
timing. Run directly for a printed before/after comparison.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field

from fastapi.testclient import TestClient

from listing_10_1_idempotency_middleware import REPLAYED_HEADER, create_app

TRANSFERS_URL = "/api/v1/payments/transfers"
PAYLOAD = {
    "from_account": "ops-checking",
    "to_account": "vendor-mecha-parts",
    "amount_cents": 2500,
}


@dataclass(frozen=True)
class StormResult:
    """What a storm of duplicate submits produced."""

    workers: int
    status_codes: list[int] = field(default_factory=list)
    bodies: set[bytes] = field(default_factory=set)
    replayed_count: int = 0
    ledger_entries: int = 0
    ledger_total_cents: int = 0


def run_double_submit_storm(
    workers: int = 50, use_idempotency_key: bool = True
) -> StormResult:
    """Fire ``workers`` identical POSTs at the API from a single barrier.

    With ``use_idempotency_key=False`` this simulates the unsafe legacy
    client: every request executes. With the key, exactly one executes.
    """
    app = create_app()
    key = "storm-" + ("keyed" if use_idempotency_key else "naive")

    with TestClient(app) as client:
        barrier = threading.Barrier(workers)
        status_codes: list[int] = []
        bodies: set[bytes] = set()
        replayed = 0
        lock = threading.Lock()

        def submit() -> None:
            nonlocal replayed
            headers = (
                {"Idempotency-Key": key} if use_idempotency_key else {}
            )
            barrier.wait()
            attempts = 0
            while True:
                attempts += 1
                assert attempts < 200, "storm did not converge"
                response = client.post(TRANSFERS_URL, json=PAYLOAD, headers=headers)
                if response.status_code == 409 and use_idempotency_key:
                    continue  # winner in flight; poll for its snapshot
                with lock:
                    status_codes.append(response.status_code)
                    bodies.add(response.content)
                    if response.headers.get(REPLAYED_HEADER) == "true":
                        replayed += 1
                return

        threads = [threading.Thread(target=submit) for _ in range(workers)]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()

        return StormResult(
            workers=workers,
            status_codes=status_codes,
            bodies=bodies,
            replayed_count=replayed,
            ledger_entries=app.state.ledger.count(),
            ledger_total_cents=app.state.ledger.total_cents(),
        )


def main() -> None:
    print("Double-submit storm: 50 identical POST /transfers")
    print("=" * 52)
    naive = run_double_submit_storm(workers=50, use_idempotency_key=False)
    print(f"without Idempotency-Key : {naive.ledger_entries} ledger entries,"
          f" {naive.ledger_total_cents} cents moved  <-- the incident")
    keyed = run_double_submit_storm(workers=50, use_idempotency_key=True)
    print(f"with    Idempotency-Key : {keyed.ledger_entries} ledger entry,"
          f" {keyed.ledger_total_cents} cents moved, "
          f"{keyed.replayed_count} replayed responses")


if __name__ == "__main__":
    main()
