"""Listing 9 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.5 -- Cache-policy simulator (pure stdlib).

Given a response's cache policy (Cache-Control directives + validators)
and a deterministic request timeline against a scripted origin, compute
the outcome of every request: HIT, MISS, revalidation, stale serve, or
bypass. Teaches RFC 9111 freshness semantics without a network.

Time is a logical integer (seconds); the origin is a script of
(t, state) changes, so every run is bit-for-bit reproducible.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Optional

HEURISTIC_FRACTION = 0.1  # RFC 9111 heuristic: 10% of (Date - Last-Modified)


# --------------------------------------------------------------------------
# Policy parsing
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class CachePolicy:
    """The cache-relevant slice of one origin response."""

    no_store: bool = False
    no_cache: bool = False
    must_revalidate: bool = False
    public: bool = False
    private: bool = False
    max_age: Optional[float] = None
    stale_while_revalidate: Optional[float] = None
    stale_if_error: Optional[float] = None
    etag: Optional[str] = None
    last_modified: Optional[float] = None
    date: float = 0.0

    def freshness_lifetime(self) -> float:
        """Explicit max-age wins; otherwise the RFC 9111 heuristic."""
        if self.max_age is not None:
            return self.max_age
        if self.last_modified is not None:
            return HEURISTIC_FRACTION * max(0.0, self.date - self.last_modified)
        return 0.0


def parse_cache_control(value: str) -> dict[str, Optional[str]]:
    """'public, max-age=60' -> {'public': None, 'max-age': '60'}."""
    directives: dict[str, Optional[str]] = {}
    for token in value.split(","):
        name, _, arg = token.strip().partition("=")
        if name:
            directives[name.lower()] = arg.strip('"') if arg else None
    return directives


def policy_from_headers(
    cache_control: str,
    *,
    etag: Optional[str] = None,
    last_modified: Optional[float] = None,
    date: float = 0.0,
) -> CachePolicy:
    d = parse_cache_control(cache_control)
    return CachePolicy(
        no_store="no-store" in d,
        no_cache="no-cache" in d,
        must_revalidate="must-revalidate" in d,
        public="public" in d,
        private="private" in d,
        max_age=float(d["max-age"]) if d.get("max-age") is not None else None,
        stale_while_revalidate=(
            float(d["stale-while-revalidate"])
            if d.get("stale-while-revalidate") is not None
            else None
        ),
        stale_if_error=(
            float(d["stale-if-error"])
            if d.get("stale-if-error") is not None
            else None
        ),
        etag=etag,
        last_modified=last_modified,
        date=date,
    )


# --------------------------------------------------------------------------
# Scripted origin
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class OriginState:
    status: int  # 200 or 500
    etag: str
    body_version: int


class ScriptedOrigin:
    """A deterministic origin: a sorted script of (t, OriginState) changes."""

    def __init__(self, script: list[tuple[float, OriginState]]) -> None:
        if not script:
            raise ValueError("origin script needs at least one state")
        self._script = sorted(script, key=lambda item: item[0])
        self.fetch_count = 0

    def state_at(self, t: float) -> OriginState:
        state = self._script[0][1]
        for change_at, candidate in self._script:
            if change_at <= t:
                state = candidate
            else:
                break
        return state

    def fetch(self, t: float) -> OriginState:
        self.fetch_count += 1
        return self.state_at(t)


# --------------------------------------------------------------------------
# The cache
# --------------------------------------------------------------------------
@dataclass
class StoredEntry:
    policy: CachePolicy
    etag: str
    body_version: int
    stored_at: float


HIT = "HIT"
MISS = "MISS"
REVALIDATED_HIT = "REVALIDATED_HIT"    # conditional GET -> 304
REVALIDATED_MISS = "REVALIDATED_MISS"  # conditional GET -> 200 (new ETag)
STALE_WHILE_REVALIDATE = "STALE_WHILE_REVALIDATE"
STALE_IF_ERROR = "STALE_IF_ERROR"
ERROR = "ERROR"     # origin down, nothing servable
BYPASS = "BYPASS"   # no-store: never reused


class SimulatedCache:
    """Single-entry shared cache executing RFC 9111 freshness decisions."""

    def __init__(self, origin: ScriptedOrigin) -> None:
        self.origin = origin
        self.stored: Optional[StoredEntry] = None
        self.stats: Counter[str] = Counter()

    def request(self, t: float) -> str:
        outcome = self._serve(t)
        self.stats[outcome] += 1
        return outcome

    def _serve(self, t: float) -> str:
        entry = self.stored
        if entry is None or entry.policy.no_store:
            return self._fetch_and_store(t, miss_label=MISS if entry is None else BYPASS)

        policy = entry.policy
        age = t - entry.stored_at
        lifetime = policy.freshness_lifetime()
        fresh = age <= lifetime and not policy.no_cache

        if fresh:
            return HIT

        # Stale-while-revalidate: serve stale now, refresh in the background.
        if (
            policy.stale_while_revalidate is not None
            and not policy.no_cache
            and not policy.must_revalidate
            and age <= lifetime + policy.stale_while_revalidate
        ):
            self._background_revalidate(t, entry)
            return STALE_WHILE_REVALIDATE

        return self._revalidate(t, entry, age, lifetime)

    def _revalidate(
        self, t: float, entry: StoredEntry, age: float, lifetime: float
    ) -> str:
        policy = entry.policy
        origin_state = self.origin.fetch(t)
        if origin_state.status >= 500:
            if (
                policy.stale_if_error is not None
                and not policy.must_revalidate
                and age <= lifetime + policy.stale_if_error
            ):
                return STALE_IF_ERROR
            return ERROR
        if origin_state.etag == entry.etag:
            # 304: freshen the stored entry in place.
            entry.stored_at = t
            return REVALIDATED_HIT
        # 200: a new representation replaces the entry.
        self.stored = StoredEntry(
            policy=entry.policy,
            etag=origin_state.etag,
            body_version=origin_state.body_version,
            stored_at=t,
        )
        return REVALIDATED_MISS

    def _background_revalidate(self, t: float, entry: StoredEntry) -> None:
        """Model the async refresh synchronously for determinism."""
        origin_state = self.origin.fetch(t)
        if origin_state.status < 500:
            self.stored = StoredEntry(
                policy=entry.policy,
                etag=origin_state.etag,
                body_version=origin_state.body_version,
                stored_at=t,
            )

    def _fetch_and_store(self, t: float, miss_label: str) -> str:
        origin_state = self.origin.fetch(t)
        if origin_state.status >= 500:
            return ERROR
        policy = CachePolicy(
            max_age=60, etag=origin_state.etag, date=t
        )  # demo default; scenarios override via inject()
        if self.stored is not None and self.stored.policy.no_store:
            return miss_label  # BYPASS: policy forbids storage entirely
        self.stored = StoredEntry(
            policy=policy,
            etag=origin_state.etag,
            body_version=origin_state.body_version,
            stored_at=t,
        )
        return miss_label

    def inject(self, policy: CachePolicy, t: float) -> None:
        """Prime the cache with an entry under an explicit policy."""
        state = self.origin.state_at(t)
        self.stored = StoredEntry(
            policy=policy,
            etag=state.etag,
            body_version=state.body_version,
            stored_at=t,
        )


def run_timeline(cache: SimulatedCache, times: list[float]) -> list[str]:
    return [cache.request(t) for t in times]


if __name__ == "__main__":
    origin = ScriptedOrigin(
        [
            (0, OriginState(200, '"v1"', 1)),
            (70, OriginState(200, '"v2"', 2)),
            (130, OriginState(500, '"v2"', 2)),
        ]
    )
    cache = SimulatedCache(origin)
    cache.request(0)  # MISS, stores v1 with max-age=60
    print("t=10  :", cache.request(10))    # HIT
    print("t=80  :", cache.request(80))    # revalidate -> new etag v2
    print("t=150 :", cache.request(150))   # stale, origin down
    print("stats :", dict(cache.stats))
