"""Listing 8 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.4 tests -- the storm harness proves effectively-once."""

from __future__ import annotations

from listing_10_4_double_submit_storm import run_double_submit_storm


def test_naive_client_executes_every_duplicate() -> None:
    """The unsafe baseline: no key, so all 50 duplicates charge through."""
    result = run_double_submit_storm(workers=50, use_idempotency_key=False)
    assert result.ledger_entries == 50
    assert result.ledger_total_cents == 50 * 2500
    assert set(result.status_codes) == {201}
    assert result.replayed_count == 0


def test_keyed_storm_mutates_exactly_once() -> None:
    result = run_double_submit_storm(workers=50, use_idempotency_key=True)
    assert result.ledger_entries == 1
    assert result.ledger_total_cents == 2500
    assert set(result.status_codes) == {201}
    assert len(result.bodies) == 1  # identical receipt for every caller
    # Exactly one origin execution; the other 49 observed the replay.
    assert result.replayed_count == 49


def test_small_storms_also_collapse_to_one_mutation() -> None:
    for workers in (2, 3, 7):
        result = run_double_submit_storm(workers=workers, use_idempotency_key=True)
        assert result.ledger_entries == 1
        assert result.replayed_count == workers - 1
