"""Listing 6 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.3 tests -- 428/412 selection and lost-update prevention.

The concurrency test drives a deterministic read-modify-write storm:
every writer retries with a fresh read until its compare-and-set wins,
so the final state must equal the sum of all intended increments.
"""

from __future__ import annotations

import threading

import pytest
from fastapi.testclient import TestClient

from listing_10_3_optimistic_locking import create_app

SKU = "NWR-AXLE-42"


@pytest.fixture()
def client() -> TestClient:
    with TestClient(create_app()) as test_client:
        yield test_client


def test_write_without_if_match_is_428(client: TestClient) -> None:
    response = client.put(f"/inventory/{SKU}", json={"quantity": 30})
    assert response.status_code == 428
    assert response.headers["content-type"].startswith("application/problem+json")
    assert client.get(f"/inventory/{SKU}").json()["quantity"] == 35


def test_stale_if_match_is_412_and_state_is_untouched(client: TestClient) -> None:
    etag_v1 = client.get(f"/inventory/{SKU}").headers["etag"]
    # Someone else writes first.
    winner = client.put(
        f"/inventory/{SKU}", json={"quantity": 30}, headers={"If-Match": etag_v1}
    )
    assert winner.status_code == 200
    # Our stale write must be rejected.
    loser = client.put(
        f"/inventory/{SKU}", json={"quantity": 25}, headers={"If-Match": etag_v1}
    )
    assert loser.status_code == 412
    state = client.get(f"/inventory/{SKU}").json()
    assert state["quantity"] == 30  # the winner's value, not the stale one
    assert state["version"] == 2


def test_lost_update_scenario_is_prevented(client: TestClient) -> None:
    """The textbook interleaving: A and B both read v1; A writes; B must lose."""
    read_a = client.get(f"/inventory/{SKU}")
    read_b = client.get(f"/inventory/{SKU}")
    assert read_a.headers["etag"] == read_b.headers["etag"] == '"v1"'

    # A decides from its copy: reserve 5 of 35 -> 30.
    ok = client.put(
        f"/inventory/{SKU}",
        json={"quantity": 35 - 5},
        headers={"If-Match": read_a.headers["etag"]},
    )
    assert ok.status_code == 200
    assert ok.headers["etag"] == '"v2"'

    # B decides from the same stale copy: reserve 8 of 35 -> 27. Refused.
    refused = client.put(
        f"/inventory/{SKU}",
        json={"quantity": 35 - 8},
        headers={"If-Match": read_b.headers["etag"]},
    )
    assert refused.status_code == 412

    # B re-reads, re-decides against current truth, and retries.
    fresh = client.get(f"/inventory/{SKU}")
    retried = client.put(
        f"/inventory/{SKU}",
        json={"quantity": fresh.json()["quantity"] - 8},
        headers={"If-Match": fresh.headers["etag"]},
    )
    assert retried.status_code == 200
    final = client.get(f"/inventory/{SKU}").json()
    assert final["quantity"] == 35 - 5 - 8  # both reservations, none lost
    assert final["version"] == 3


def test_unknown_sku_is_404(client: TestClient) -> None:
    assert client.get("/inventory/NOPE").status_code == 404
    assert (
        client.put(
            "/inventory/NOPE", json={"quantity": 1}, headers={"If-Match": '"v1"'}
        ).status_code
        == 404
    )


def test_negative_quantity_is_rejected(client: TestClient) -> None:
    etag = client.get(f"/inventory/{SKU}").headers["etag"]
    response = client.put(
        f"/inventory/{SKU}", json={"quantity": -1}, headers={"If-Match": etag}
    )
    assert response.status_code == 422


def test_concurrent_read_modify_write_storm_loses_nothing(client: TestClient) -> None:
    """20 threads each increment by one under optimistic retry.

    A writer loops: read -> compute -> conditional write; on 412 it
    re-reads and retries. Loop termination is state-driven (a successful
    compare-and-set), never timing-driven.
    """
    workers = 20
    barrier = threading.Barrier(workers)
    attempts: list[int] = []
    attempts_lock = threading.Lock()

    def increment_once() -> None:
        barrier.wait()
        tries = 0
        while True:
            tries += 1
            assert tries < 500, "optimistic retry loop did not converge"
            current = client.get(f"/inventory/{SKU}")
            etag = current.headers["etag"]
            target = current.json()["quantity"] + 1
            written = client.put(
                f"/inventory/{SKU}",
                json={"quantity": target},
                headers={"If-Match": etag},
            )
            if written.status_code == 200:
                with attempts_lock:
                    attempts.append(tries)
                return
            assert written.status_code == 412  # only contention may fail us

    threads = [threading.Thread(target=increment_once) for _ in range(workers)]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()

    final = client.get(f"/inventory/{SKU}").json()
    assert final["quantity"] == 35 + workers  # every increment landed
    assert final["version"] == 1 + workers    # one version per accepted write
    assert len(attempts) == workers
