"""Listing 10 extracted from chapters/chapter_10_idempotency_caching_concurrency.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 10.5 tests -- directive semantics, proven on scripted timelines."""

from __future__ import annotations

from listing_10_5_cache_simulator import (
    BYPASS,
    ERROR,
    HIT,
    MISS,
    OriginState,
    REVALIDATED_HIT,
    REVALIDATED_MISS,
    STALE_IF_ERROR,
    STALE_WHILE_REVALIDATE,
    SimulatedCache,
    ScriptedOrigin,
    parse_cache_control,
    policy_from_headers,
    run_timeline,
)


def make_cache(
    script: list[tuple[float, OriginState]] | None = None,
) -> SimulatedCache:
    if script is None:
        script = [(0, OriginState(200, '"v1"', 1))]
    return SimulatedCache(ScriptedOrigin(script))


def test_parse_cache_control() -> None:
    d = parse_cache_control('public, max-age=60, stale-while-revalidate=30')
    assert d == {"public": None, "max-age": "60", "stale-while-revalidate": "30"}


def test_max_age_governs_freshness() -> None:
    cache = make_cache()
    cache.inject(policy_from_headers("public, max-age=60", etag='"v1"'), t=0)
    assert run_timeline(cache, [10, 60]) == [HIT, HIT]
    assert cache.request(61) == REVALIDATED_HIT  # stale -> conditional GET -> 304
    assert cache.request(70) == HIT  # freshened by the 304


def test_no_store_never_caches() -> None:
    cache = make_cache()
    cache.inject(policy_from_headers("no-store", etag='"v1"'), t=0)
    assert run_timeline(cache, [1, 2, 3]) == [BYPASS, BYPASS, BYPASS]
    assert cache.origin.fetch_count == 3  # every request hits the origin


def test_no_cache_revalidates_every_time() -> None:
    cache = make_cache()
    cache.inject(
        policy_from_headers("no-cache", etag='"v1"', date=0), t=0
    )
    # Validators make each revalidation cheap (304), but nothing is served
    # without contacting the origin first.
    assert run_timeline(cache, [1, 2]) == [REVALIDATED_HIT, REVALIDATED_HIT]
    assert cache.origin.fetch_count == 2


def test_heuristic_freshness_without_max_age() -> None:
    cache = make_cache()
    # Last-Modified 1000s before Date -> heuristic freshness = 100s.
    policy = policy_from_headers(
        "public", etag='"v1"', last_modified=0.0, date=1000.0
    )
    cache.inject(policy, t=1000.0)
    assert cache.request(1050.0) == HIT
    assert cache.request(1200.0) == REVALIDATED_HIT


def test_changed_etag_yields_revalidated_miss() -> None:
    cache = make_cache(
        [
            (0, OriginState(200, '"v1"', 1)),
            (50, OriginState(200, '"v2"', 2)),
        ]
    )
    cache.inject(policy_from_headers("public, max-age=10", etag='"v1"'), t=0)
    assert cache.request(60) == REVALIDATED_MISS  # 200 with new body
    assert cache.stored is not None and cache.stored.etag == '"v2"'
    assert cache.request(65) == HIT  # the fresh replacement now serves


def test_stale_while_revalidate_serves_stale_then_refreshes() -> None:
    cache = make_cache(
        [
            (0, OriginState(200, '"v1"', 1)),
            (40, OriginState(200, '"v2"', 2)),
        ]
    )
    cache.inject(
        policy_from_headers(
            "public, max-age=30, stale-while-revalidate=60", etag='"v1"'
        ),
        t=0,
    )
    assert cache.request(50) == STALE_WHILE_REVALIDATE  # stale served...
    assert cache.stored is not None and cache.stored.etag == '"v2"'  # ...refreshed
    assert cache.request(55) == HIT


def test_stale_if_error_rescues_an_origin_outage() -> None:
    cache = make_cache(
        [
            (0, OriginState(200, '"v1"', 1)),
            (100, OriginState(500, '"v1"', 1)),
        ]
    )
    cache.inject(
        policy_from_headers("public, max-age=30, stale-if-error=300", etag='"v1"'),
        t=0,
    )
    assert cache.request(120) == STALE_IF_ERROR  # origin down, stale saved us


def test_must_revalidate_forbids_stale_if_error() -> None:
    cache = make_cache(
        [
            (0, OriginState(200, '"v1"', 1)),
            (100, OriginState(500, '"v1"', 1)),
        ]
    )
    cache.inject(
        policy_from_headers(
            "public, max-age=30, must-revalidate, stale-if-error=300", etag='"v1"'
        ),
        t=0,
    )
    assert cache.request(120) == ERROR  # must-revalidate wins: no stale serve


def test_full_demo_timeline_is_deterministic() -> None:
    def run() -> tuple[list[str], dict[str, int]]:
        origin = ScriptedOrigin(
            [
                (0, OriginState(200, '"v1"', 1)),
                (70, OriginState(200, '"v2"', 2)),
                (130, OriginState(500, '"v2"', 2)),
            ]
        )
        cache = SimulatedCache(origin)
        outcomes = run_timeline(cache, [0, 10, 80, 100, 150])
        return outcomes, dict(cache.stats)

    first_outcomes, first_stats = run()
    second_outcomes, second_stats = run()
    assert first_outcomes == second_outcomes  # bit-for-bit reproducible
    assert first_stats == second_stats
    assert first_outcomes == [MISS, HIT, REVALIDATED_MISS, HIT, ERROR]
