"""Listing 2 extracted from chapters/chapter_06_building_apis_fastapi.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Pure-ASGI middleware: correlation IDs and request timing.

Both classes implement the ASGI callable protocol directly --
``__call__(scope, receive, send)`` -- so nothing here depends on FastAPI
or Starlette. Registration order matters: the LAST middleware added is the
OUTERMOST (runs first on the request path, last on the response path):

    app.add_middleware(TimingMiddleware)          # added 1st -> inner
    app.add_middleware(CorrelationIdMiddleware)   # added 2nd -> outer

Because CorrelationIdMiddleware is outermost, the request-id context
variable is already bound when TimingMiddleware logs, so every access-log
line carries the correlation ID.
"""
from __future__ import annotations

import logging
import time
import uuid
from contextvars import ContextVar
from typing import Any, Awaitable, Callable, MutableMapping

# The three callables that make up the ASGI protocol surface.
ASGIScope = MutableMapping[str, Any]
ASGIMessage = MutableMapping[str, Any]
ASGIReceive = Callable[[], Awaitable[ASGIMessage]]
ASGISend = Callable[[ASGIMessage], Awaitable[None]]
ASGIApp = Callable[[ASGIScope, ASGIReceive, ASGISend], Awaitable[None]]

# Bound once per request by CorrelationIdMiddleware; read by the JSON log
# formatter so every log line inside the request carries the same ID.
request_id_var: ContextVar[str] = ContextVar("request_id", default="-")

logger = logging.getLogger("northwind.access")


class CorrelationIdMiddleware:
    """Extract (or mint) X-Request-Id, bind it, and echo it on the response."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(
        self, scope: ASGIScope, receive: ASGIReceive, send: ASGISend
    ) -> None:
        if scope["type"] != "http":  # pass lifespan/websocket through untouched
            await self.app(scope, receive, send)
            return

        headers = {k.lower(): v for k, v in scope.get("headers", [])}
        request_id = (
            headers.get(b"x-request-id", b"").decode("latin-1")
            or uuid.uuid4().hex[:16]
        )
        token = request_id_var.set(request_id)
        scope["request_id"] = request_id  # visible to the app via request.scope

        async def send_with_request_id(message: ASGIMessage) -> None:
            if message["type"] == "http.response.start":
                message.setdefault("headers", [])
                message["headers"].append(
                    (b"x-request-id", request_id.encode("latin-1"))
                )
            await send(message)

        try:
            await self.app(scope, receive, send_with_request_id)
        finally:
            request_id_var.reset(token)  # never leak IDs across requests


class TimingMiddleware:
    """Measure downstream wall time, add X-Process-Time-Ms, log one JSON line."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(
        self, scope: ASGIScope, receive: ASGIReceive, send: ASGISend
    ) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        started = time.perf_counter()
        status_code = 0

        async def send_with_timing(message: ASGIMessage) -> None:
            nonlocal status_code
            if message["type"] == "http.response.start":
                status_code = message["status"]
                elapsed_ms = (time.perf_counter() - started) * 1000.0
                message.setdefault("headers", [])
                message["headers"].append(
                    (b"x-process-time-ms", f"{elapsed_ms:.2f}".encode("ascii"))
                )
            await send(message)

        try:
            await self.app(scope, receive, send_with_timing)
        finally:
            # Logs even on unhandled exceptions (status_code stays 0).
            elapsed_ms = (time.perf_counter() - started) * 1000.0
            logger.info(
                "request completed",
                extra={
                    "method": scope["method"],
                    "path": scope["path"],
                    "status_code": status_code,
                    "elapsed_ms": round(elapsed_ms, 2),
                    "request_id": request_id_var.get(),
                },
            )
