"""Listing 4 extracted from chapters/chapter_06_building_apis_fastapi.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""TestClient suite for the Orders API: fully offline, fully deterministic."""
from __future__ import annotations

import json

import pytest
from fastapi.testclient import TestClient

import di_showcase
from orders_api import (
    InMemoryOrderRepository,
    OrderNotFoundError,
    Settings,
    create_app,
    get_repository,
)

VALID_ORDER = {
    "customer_id": "Acme-Robotics",
    "lines": [{"sku": "NWR-1001", "quantity": 2, "unit_price_cents": 4999}],
}


@pytest.fixture()
def client() -> TestClient:
    # The context manager drives the lifespan: startup runs, readiness flips,
    # and shutdown/close is exercised on exit.
    app = create_app(Settings(repository_backend="memory"))
    with TestClient(app) as test_client:
        yield test_client


# -- operational endpoints ----------------------------------------------------


def test_health_and_readiness(client: TestClient) -> None:
    assert client.get("/health").json() == {"status": "ok"}
    assert client.get("/ready").json() == {"status": "ready"}


def test_readiness_fails_closed(client: TestClient) -> None:
    client.app.state.ready = False  # simulate mid-shutdown / failed warmup
    response = client.get("/ready")
    assert response.status_code == 503
    assert response.json() == {"status": "unavailable"}


# -- CRUD happy paths ----------------------------------------------------------


def test_create_order_filters_internal_fields(client: TestClient) -> None:
    response = client.post("/orders", json=VALID_ORDER)
    assert response.status_code == 201
    body = response.json()
    assert body["id"] == "ord-0001"  # deterministic IDs
    assert body["status"] == "pending"
    assert body["total_cents"] == 9998
    assert body["customerId"] == "acme-robotics"  # alias + normalization
    assert "customer_id" not in body
    # response_model=OrderRead strips internal-only fields:
    assert "warehouse_hint" not in body
    assert "fraud_score" not in body


def test_get_and_list_orders(client: TestClient) -> None:
    client.post("/orders", json=VALID_ORDER)
    client.post(
        "/orders",
        json={
            "customer_id": "globex",
            "lines": [{"sku": "NWR-2002", "quantity": 1, "unit_price_cents": 100}],
        },
    )
    fetched = client.get("/orders/ord-0002")
    assert fetched.status_code == 200
    assert fetched.json()["customerId"] == "globex"

    page = client.get("/orders", params={"limit": 1, "offset": 1})
    assert [o["id"] for o in page.json()] == ["ord-0002"]


def test_status_transition_happy_path(client: TestClient) -> None:
    client.post("/orders", json=VALID_ORDER)
    confirmed = client.patch("/orders/ord-0001", json={"status": "confirmed"})
    assert confirmed.status_code == 200
    assert confirmed.json()["status"] == "confirmed"
    assert confirmed.json()["version"] == 2
    shipped = client.patch("/orders/ord-0001", json={"status": "shipped"})
    assert shipped.json()["status"] == "shipped"


def test_delete_order_then_404(client: TestClient) -> None:
    client.post("/orders", json=VALID_ORDER)
    assert client.delete("/orders/ord-0001").status_code == 204
    assert client.get("/orders/ord-0001").status_code == 404


# -- validation and domain errors ----------------------------------------------


def test_invalid_sku_is_a_422_with_sanitized_errors(client: TestClient) -> None:
    bad = {"customer_id": "acme", "lines": [
        {"sku": "not-a-sku", "quantity": 1, "unit_price_cents": 100}]}
    response = client.post("/orders", json=bad)
    assert response.status_code == 422
    body = response.json()
    assert response.headers["content-type"].startswith("application/problem+json")
    assert body["title"] == "Validation failed"
    assert body["errors"][0]["loc"] == "body.lines.0.sku"
    assert "ctx" not in body["errors"][0]  # no raw internals leak


def test_duplicate_skus_rejected_by_model_validator(client: TestClient) -> None:
    dup = {"customer_id": "acme", "lines": [
        {"sku": "NWR-1001", "quantity": 1, "unit_price_cents": 100},
        {"sku": "NWR-1001", "quantity": 3, "unit_price_cents": 100}]}
    response = client.post("/orders", json=dup)
    assert response.status_code == 422
    assert "duplicate SKU" in response.json()["errors"][0]["msg"]


def test_missing_order_is_a_404_problem(client: TestClient) -> None:
    response = client.get("/orders/ord-9999")
    assert response.status_code == 404
    body = response.json()
    assert body["title"] == "Order not found"
    assert body["order_id"] == "ord-9999"


def test_invalid_transition_is_a_409(client: TestClient) -> None:
    client.post("/orders", json=VALID_ORDER)
    response = client.patch("/orders/ord-0001", json={"status": "shipped"})
    assert response.status_code == 409
    body = response.json()
    assert body["current"] == "pending"
    assert body["target"] == "shipped"


# -- middleware -----------------------------------------------------------------


def test_correlation_id_echoed(client: TestClient) -> None:
    response = client.get("/health", headers={"X-Request-Id": "req-abc-123"})
    assert response.headers["x-request-id"] == "req-abc-123"


def test_correlation_id_minted_when_absent(client: TestClient) -> None:
    response = client.get("/health")
    assert len(response.headers["x-request-id"]) == 16
    assert "x-process-time-ms" in response.headers


# -- OpenAPI contract ------------------------------------------------------------


def test_openapi_schema_is_customized_and_complete(client: TestClient) -> None:
    schema = client.get("/openapi.json").json()
    assert schema["info"]["title"] == "Northwind Robotics Orders API"
    assert schema["info"]["x-audience"] == "internal"
    assert {p for p in schema["paths"]} >= {
        "/orders", "/orders/{order_id}", "/health", "/ready", "/orders-stream"}
    assert schema["components"]["securitySchemes"]["ApiKeyAuth"] == {
        "type": "apiKey", "in": "header", "name": "X-API-Key"}
    assert schema["servers"][0]["url"] == "http://localhost:8000"
    create_op = schema["paths"]["/orders"]["post"]
    assert "201" in create_op["responses"]  # status codes documented for free
    assert "422" in create_op["responses"]


# -- streaming --------------------------------------------------------------------


def test_stream_orders_as_ndjson(client: TestClient) -> None:
    client.post("/orders", json=VALID_ORDER)
    client.post("/orders", json={
        "customer_id": "globex",
        "lines": [{"sku": "NWR-2002", "quantity": 5, "unit_price_cents": 50}]})
    response = client.get("/orders-stream")
    assert response.headers["content-type"].startswith("application/x-ndjson")
    lines = [json.loads(line) for line in response.text.splitlines()]
    assert [line["id"] for line in lines] == ["ord-0001", "ord-0002"]
    assert all("fraud_score" not in line for line in lines)


# -- the SQLite backend -------------------------------------------------------------


def test_sqlite_repository_roundtrip(tmp_path) -> None:
    settings = Settings(
        repository_backend="sqlite", sqlite_path=str(tmp_path / "orders.db")
    )
    with TestClient(create_app(settings)) as client:
        assert client.post("/orders", json=VALID_ORDER).status_code == 201
        body = client.get("/orders/ord-0001").json()
        assert body["total_cents"] == 9998
        # lifecycle: shutdown closed the DB, readiness now fails closed
    assert client.app.state.ready is False


# -- dependency overrides --------------------------------------------------------


class EmptyRepository(InMemoryOrderRepository):
    def get(self, order_id: str):  # every lookup misses
        raise OrderNotFoundError(order_id)


def test_dependency_override_swaps_the_repository() -> None:
    app = create_app(Settings(repository_backend="memory"))
    app.dependency_overrides[get_repository] = EmptyRepository
    with TestClient(app) as client:
        assert client.get("/orders/ord-0001").status_code == 404
    app.dependency_overrides.clear()


def test_di_showcase_caching_and_override() -> None:
    app = di_showcase.create_app()
    with TestClient(app) as client:
        first = client.get("/demo").json()
    assert first["quote_resolutions"] == 1  # resolved once per request

    app = di_showcase.create_app()
    app.dependency_overrides[di_showcase.get_quote_source] = (
        di_showcase.FallbackQuoteSource)
    with TestClient(app) as client:
        assert client.get("/demo").json()["quote"] == "synthetic fallback quote"
