"""Listing 3 extracted from chapters/chapter_06_building_apis_fastapi.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Dependency-injection showcase: chains, yield cleanup, caching, overrides.

Self-checking demo (offline, in-process):
    python di_showcase.py
"""
from __future__ import annotations

import sqlite3
from collections.abc import Iterator
from typing import Annotated, Protocol

from fastapi import Depends, FastAPI
from fastapi.testclient import TestClient


# --- a tiny domain: a quote-of-the-day service --------------------------------


class QuoteSource(Protocol):
    def quote(self) -> str: ...


class HandbookQuoteSource:
    """The 'real' implementation: reads the Northwind SRE handbook."""

    def quote(self) -> str:
        return "Robots do not panic. -- Northwind SRE handbook"


QUOTE_RESOLUTIONS = {"count": 0}  # observable side effect for the caching demo


def get_quote_source() -> HandbookQuoteSource:
    QUOTE_RESOLUTIONS["count"] += 1
    return HandbookQuoteSource()


QuoteDep = Annotated[QuoteSource, Depends(get_quote_source)]


def get_audit_trail(source: QuoteDep) -> list[str]:
    """Sub-dependency: depends on the SAME QuoteSource the handler requests."""
    return [f"audit: served quote of length {len(source.quote())}"]


# --- a yield dependency with guaranteed cleanup --------------------------------


def get_connection() -> Iterator[sqlite3.Connection]:
    """One in-memory SQLite connection per request, closed afterwards."""
    conn = sqlite3.connect(":memory:", check_same_thread=False)
    conn.execute("CREATE TABLE visits (path TEXT)")
    conn.execute("INSERT INTO visits (path) VALUES ('/demo')")
    try:
        yield conn  # the endpoint (and sub-dependencies) run here
    finally:
        conn.close()  # runs even when the endpoint raises


ConnectionDep = Annotated[sqlite3.Connection, Depends(get_connection)]


def create_app() -> FastAPI:
    app = FastAPI(title="di-showcase")

    @app.get("/demo")
    def demo(
        direct: QuoteDep,  # requested here AND inside get_audit_trail ...
        audit: Annotated[list[str], Depends(get_audit_trail)],
        conn: ConnectionDep,
    ) -> dict[str, object]:
        rows = conn.execute("SELECT COUNT(*) FROM visits").fetchone()[0]
        return {
            "quote": direct.quote(),
            "audit": audit,
            "visits": rows,
            "quote_resolutions": QUOTE_RESOLUTIONS["count"],
        }

    return app


class FallbackQuoteSource:
    """Test double injected via dependency_overrides."""

    def quote(self) -> str:
        return "synthetic fallback quote"


if __name__ == "__main__":
    # 1) Per-request caching: the dependency graph requests QuoteSource twice
    #    (directly + via the audit sub-dependency) yet resolves it ONCE.
    with TestClient(create_app()) as client:
        first = client.get("/demo").json()
        second = client.get("/demo").json()
    assert first["quote_resolutions"] == 1, first
    assert second["quote_resolutions"] == 2, second
    print("per-request caching OK:", first["quote_resolutions"],
          "->", second["quote_resolutions"])

    # 2) Overrides: swap the implementation without touching route code.
    app = create_app()
    app.dependency_overrides[get_quote_source] = FallbackQuoteSource
    with TestClient(app) as client:
        body = client.get("/demo").json()
    assert body["quote"] == "synthetic fallback quote", body
    print("override OK:", body["quote"])
