"""Listing 1 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""In-memory repository for the Northwind Robotics catalog.

Synthetic, deterministic, offline: the same seed data on every run.
The repository exposes an instrumentation counter so the N+1 problem is
measurable rather than anecdotal.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CategoryRow:
    id: int
    name: str
    description: str


@dataclass(frozen=True)
class ProductRow:
    id: int
    sku: str
    name: str
    category_id: int
    unit_price_cents: int
    unit_cost_cents: int | None  # None = cost data missing (drives null-propagation demo)
    stock: int
    discontinued: bool


@dataclass(frozen=True)
class ReviewRow:
    id: int
    product_id: int
    rating: int
    headline: str


_CATEGORIES: tuple[CategoryRow, ...] = (
    CategoryRow(1, "Actuators", "Linear and rotary motion components"),
    CategoryRow(2, "Sensors", "LIDAR, vision, and tactile sensing"),
    CategoryRow(3, "Controllers", "Real-time motor and fleet controllers"),
)

_PRODUCTS: tuple[ProductRow, ...] = (
    ProductRow(1, "NWR-ACT-100", "Servo Linear Actuator 100mm", 1, 459_00, 210_00, 34, False),
    ProductRow(2, "NWR-ACT-200", "Rotary Torque Actuator 12Nm", 1, 899_00, 401_00, 12, False),
    ProductRow(3, "NWR-SEN-310", "Solid-State LIDAR Unit", 2, 1_299_00, 620_00, 8, False),
    ProductRow(4, "NWR-SEN-410", "Tactile Gripper Sensor Array", 2, 349_00, None, 0, True),
    ProductRow(5, "NWR-CTL-900", "Fleet Motion Controller X9", 3, 2_499_00, 1_150_00, 5, False),
)

_REVIEWS: tuple[ReviewRow, ...] = (
    ReviewRow(1, 1, 5, "Silky smooth travel"),
    ReviewRow(2, 1, 4, "Solid, runs warm under load"),
    ReviewRow(3, 2, 5, "Best torque-per-dollar we tested"),
    ReviewRow(4, 3, 4, "Great range, tricky mounting"),
    ReviewRow(5, 5, 5, "Runs our whole warehouse fleet"),
)


class CatalogRepository:
    """In-memory catalog store with a query counter for N+1 measurement."""

    def __init__(self) -> None:
        self._categories = {c.id: c for c in _CATEGORIES}
        self._products = {p.id: p for p in _PRODUCTS}
        self._reviews: dict[int, list[ReviewRow]] = {}
        for review in _REVIEWS:
            self._reviews.setdefault(review.product_id, []).append(review)
        self._next_review_id = max(r.id for r in _REVIEWS) + 1
        self.query_count = 0  # incremented on every store read

    def reset_counter(self) -> None:
        self.query_count = 0

    # --- single-record reads (the naive path uses these in a loop) ---

    def product_by_id(self, product_id: int) -> ProductRow | None:
        self.query_count += 1
        return self._products.get(product_id)

    def category_by_id(self, category_id: int) -> CategoryRow | None:
        self.query_count += 1
        return self._categories.get(category_id)

    def reviews_for_product(self, product_id: int) -> list[ReviewRow]:
        self.query_count += 1
        return list(self._reviews.get(product_id, []))

    # --- batched reads (the DataLoader path calls these once per tick) ---

    def categories_by_ids(self, ids: list[int]) -> list[CategoryRow | None]:
        self.query_count += 1
        return [self._categories.get(i) for i in ids]

    def reviews_for_products(self, ids: list[int]) -> list[list[ReviewRow]]:
        self.query_count += 1
        return [list(self._reviews.get(i, [])) for i in ids]

    # --- connection page read ---

    def products_page(
        self, after_id: int, first: int
    ) -> tuple[list[ProductRow], bool]:
        """Return up to ``first`` products with id > after_id, plus has-next."""
        self.query_count += 1
        ordered = sorted(self._products.values(), key=lambda p: p.id)
        page = [p for p in ordered if p.id > after_id][: first + 1]
        return page[:first], len(page) > first

    def total_products(self) -> int:
        self.query_count += 1
        return len(self._products)

    # --- mutation ---

    def add_review(self, product_id: int, rating: int, headline: str) -> ReviewRow | None:
        """Insert a review; returns None when the product does not exist."""
        if product_id not in self._products:
            return None
        self._next_review_id += 1
        row = ReviewRow(self._next_review_id, product_id, rating, headline)
        self._reviews.setdefault(product_id, []).append(row)
        return row
