"""Listing 2 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Strawberry schema for the Northwind Robotics catalog.

Demonstrates: object types, enums, input types, union-typed mutation
results, Relay-style connections, context injection, per-request
DataLoaders, field-level errors with extensions, and null propagation.
"""

from __future__ import annotations

import base64
import enum
from typing import Annotated, Optional

import strawberry
from graphql import GraphQLError
from strawberry.dataloader import DataLoader
from strawberry.types import Info

from catalog_repository import CatalogRepository, CategoryRow, ProductRow, ReviewRow

MAX_PAGE_SIZE = 50


# ---------------------------------------------------------------------------
# Enum and context
# ---------------------------------------------------------------------------


@strawberry.enum
class ProductStatus(enum.Enum):
    ACTIVE = "active"
    DISCONTINUED = "discontinued"


class Context:
    """Per-request context: one repository, one set of DataLoaders.

    NOT a Strawberry type: it is constructed once per request and handed
    to resolvers via ``info.context``. ``use_loaders`` exists only so the
    N+1 demo can switch resolvers between naive and batched reads.
    """

    def __init__(self, repo: CatalogRepository, use_loaders: bool = True) -> None:
        self.repo = repo
        self.use_loaders = use_loaders
        self.category_loader = make_category_loader(repo)
        self.review_loader = make_review_loader(repo)


def get_context() -> Context:
    return Context(CatalogRepository())


# ---------------------------------------------------------------------------
# Object types
# ---------------------------------------------------------------------------


@strawberry.type
class Category:
    id: int
    name: str
    description: str


@strawberry.type
class Review:
    id: int
    rating: int
    headline: str


@strawberry.type
class Product:
    id: int
    sku: str
    name: str
    unit_price_cents: int
    stock: int
    discontinued: bool
    _category_id: strawberry.Private[int]

    @strawberry.field
    async def category(self, info: Info[Context, None]) -> Optional[Category]:
        ctx = info.context
        if ctx.use_loaders:
            row = await ctx.category_loader.load(self._category_id)
        else:  # naive path: one store read per product (the N in N+1)
            row = ctx.repo.category_by_id(self._category_id)
        if row is None:
            return None
        return Category(id=row.id, name=row.name, description=row.description)

    @strawberry.field
    async def reviews(self, info: Info[Context, None]) -> list[Review]:
        ctx = info.context
        if ctx.use_loaders:
            rows = await ctx.review_loader.load(self.id)
        else:  # naive path
            rows = ctx.repo.reviews_for_product(self.id)
        return [Review(id=r.id, rating=r.rating, headline=r.headline) for r in rows]

    @strawberry.field
    def margin_percent(self, info: Info[Context, None]) -> int:
        """NON-NULL field that errors when cost data is missing.

        Raising here nulls the entire Product (null propagation), because
        the schema promises this field is never null.
        """
        row = info.context.repo.product_by_id(self.id)
        if row is None or row.unit_cost_cents is None:
            raise GraphQLError(
                "cost data unavailable for product",
                extensions={"code": "COST_DATA_UNAVAILABLE"},
            )
        margin = row.unit_price_cents - row.unit_cost_cents
        return round(100 * margin / row.unit_price_cents)


def _to_product(row: ProductRow) -> Product:
    return Product(
        id=row.id,
        sku=row.sku,
        name=row.name,
        unit_price_cents=row.unit_price_cents,
        stock=row.stock,
        discontinued=row.discontinued,
        _category_id=row.category_id,
    )


# ---------------------------------------------------------------------------
# Relay-style connection
# ---------------------------------------------------------------------------


def encode_cursor(product_id: int) -> str:
    raw = f"product:{product_id}".encode("ascii")
    return base64.urlsafe_b64encode(raw).decode("ascii")


def decode_cursor(cursor: str) -> int:
    try:
        raw = base64.urlsafe_b64decode(cursor.encode("ascii")).decode("ascii")
        prefix, sep, digits = raw.partition(":")
        if prefix != "product" or sep == "":
            raise ValueError("bad prefix")
        return int(digits)
    except (ValueError, UnicodeDecodeError) as exc:
        raise GraphQLError(
            "invalid cursor", extensions={"code": "BAD_CURSOR"}
        ) from exc


@strawberry.type
class PageInfo:
    has_next_page: bool
    has_previous_page: bool
    start_cursor: Optional[str]
    end_cursor: Optional[str]


@strawberry.type
class ProductEdge:
    cursor: str
    node: Optional[Product]  # nullable: a nulled node must not void the page


@strawberry.type
class ProductConnection:
    edges: list[ProductEdge]
    page_info: PageInfo

    @strawberry.field
    def total_count(self, info: Info[Context, None]) -> int:
        # Lazy: only costs a store read when the client asks for it.
        return info.context.repo.total_products()


# ---------------------------------------------------------------------------
# Mutation payloads: typed errors via unions
# ---------------------------------------------------------------------------


@strawberry.input
class AddReviewInput:
    product_id: int
    rating: int
    headline: str


@strawberry.type
class AddReviewSuccess:
    review: Review


@strawberry.type
class AddReviewError:
    message: str
    code: str


AddReviewResult = Annotated[
    AddReviewSuccess | AddReviewError, strawberry.union("AddReviewResult")
]


# ---------------------------------------------------------------------------
# Root operations
# ---------------------------------------------------------------------------


@strawberry.type
class Query:
    @strawberry.field
    async def products(
        self,
        info: Info[Context, None],
        first: int = 10,
        after: Optional[str] = None,
        status: Optional[ProductStatus] = None,
    ) -> Optional[ProductConnection]:  # nullable root: errors stay partial
        if not 1 <= first <= MAX_PAGE_SIZE:
            raise GraphQLError(
                f"first must be between 1 and {MAX_PAGE_SIZE}",
                extensions={"code": "BAD_PAGINATION_ARGUMENT"},
            )
        after_id = decode_cursor(after) if after else 0
        repo = info.context.repo
        rows, has_next = repo.products_page(after_id, first)
        if status is ProductStatus.ACTIVE:
            rows = [r for r in rows if not r.discontinued]
        elif status is ProductStatus.DISCONTINUED:
            rows = [r for r in rows if r.discontinued]
        edges = [
            ProductEdge(cursor=encode_cursor(r.id), node=_to_product(r)) for r in rows
        ]
        return ProductConnection(
            edges=edges,
            page_info=PageInfo(
                has_next_page=has_next,
                has_previous_page=after_id > 0,
                start_cursor=edges[0].cursor if edges else None,
                end_cursor=edges[-1].cursor if edges else None,
            ),
        )

    @strawberry.field
    async def product(self, info: Info[Context, None], product_id: int) -> Optional[Product]:
        row = info.context.repo.product_by_id(product_id)
        return _to_product(row) if row else None


@strawberry.type
class Mutation:
    @strawberry.mutation
    def add_review(
        self, info: Info[Context, None], input: AddReviewInput
    ) -> AddReviewResult:
        if not 1 <= input.rating <= 5:
            return AddReviewError(
                message="rating must be between 1 and 5",
                code="RATING_OUT_OF_RANGE",
            )
        headline = input.headline.strip()
        if not headline:
            return AddReviewError(
                message="headline must not be empty", code="EMPTY_HEADLINE"
            )
        row = info.context.repo.add_review(input.product_id, input.rating, headline)
        if row is None:
            return AddReviewError(
                message=f"product {input.product_id} not found",
                code="PRODUCT_NOT_FOUND",
            )
        return AddReviewSuccess(
            review=Review(id=row.id, rating=row.rating, headline=row.headline)
        )


# ---------------------------------------------------------------------------
# DataLoaders: one instance per request, batch + per-request cache
# ---------------------------------------------------------------------------


def make_category_loader(repo: CatalogRepository) -> DataLoader:
    async def batch(keys: list[int]) -> list[Optional[CategoryRow]]:
        # ONE store read per tick, for all keys queued this tick.
        return repo.categories_by_ids(keys)

    return DataLoader(load_fn=batch)


def make_review_loader(repo: CatalogRepository) -> DataLoader:
    async def batch(keys: list[int]) -> list[list[ReviewRow]]:
        return repo.reviews_for_products(keys)

    return DataLoader(load_fn=batch)


schema = strawberry.Schema(query=Query, mutation=Mutation)
