"""Listing 5 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""FastAPI host for the catalog schema.

The HTTP layer is deliberately thin: all GraphQL policy (persisted-query
resolution, depth/complexity budgets, execution) lives in cost_control.py
so it is testable without a web framework. Introspection is gated by an
explicit policy flag, never by "we forgot".

Run (dev only):  uvicorn server:app --port 8000
"""

from __future__ import annotations

import os
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from catalog_repository import CatalogRepository
from catalog_schema import Context, schema
from cost_control import PersistedQueryRegistry, execute_graphql_http

INTROSPECTION_ENABLED = os.environ.get("NWR_INTROSPECTION", "off") == "on"

_registry = PersistedQueryRegistry()
# Pre-register the operations the mobile app ships with (allow-list seed).
_CATALOG_OP = """
query CatalogPage($first: Int!) {
  products(first: $first) {
    edges { node { name category { name } } }
    pageInfo { hasNextPage endCursor }
  }
}
"""
CATALOG_OP_HASH = _registry.register(_CATALOG_OP)


def _context_factory() -> Context:
    # One repository + one set of DataLoaders per request.
    return Context(CatalogRepository())


def create_app() -> FastAPI:
    app = FastAPI(title="Northwind Robotics Catalog", version="1.0.0")

    @app.post("/graphql")
    async def graphql_endpoint(request: Request) -> JSONResponse:
        payload: dict[str, Any] = await request.json()
        status, body = await execute_graphql_http(
            payload,
            schema=schema,
            registry=_registry,
            context_factory=_context_factory,
            allow_introspection=INTROSPECTION_ENABLED,
        )
        return JSONResponse(body, status_code=status)

    @app.get("/health")
    async def health() -> dict[str, str]:
        return {"status": "ok"}

    return app


app = create_app()
