"""Listing 6 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""GraphQL-over-HTTP client with variables, error handling, and APQ.

Transport is injected, so the demo below runs fully offline against the
in-process FastAPI app (httpx.ASGITransport) -- no socket is opened.

Run:  python graphql_client.py
"""

from __future__ import annotations

import asyncio
import hashlib
import json
from dataclasses import dataclass
from typing import Any, Optional

import httpx

GRAPHQL_PATH = "/graphql"


class GraphQLTransportError(Exception):
    """Network failure or non-GraphQL HTTP error (5xx, timeouts)."""


class GraphQLFieldErrors(Exception):
    """The response carried a populated ``errors`` array (HTTP 200)."""

    def __init__(self, errors: list[dict[str, Any]], data: Any) -> None:
        messages = [e.get("message", "?") for e in errors]
        super().__init__("; ".join(messages))
        self.errors = errors
        self.data = data  # partial data may still be present


@dataclass(frozen=True)
class GraphQLResponse:
    data: Any
    errors: list[dict[str, Any]]


class GraphQLClient:
    def __init__(self, base_url: str, transport: Optional[httpx.AsyncBaseTransport] = None,
                 timeout: float = 10.0) -> None:
        self._client = httpx.AsyncClient(
            base_url=base_url, transport=transport, timeout=timeout
        )

    async def close(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> "GraphQLClient":
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.close()

    async def execute(
        self,
        query: str,
        variables: Optional[dict[str, Any]] = None,
        operation_name: Optional[str] = None,
    ) -> GraphQLResponse:
        payload: dict[str, Any] = {"query": query}
        if variables is not None:
            payload["variables"] = variables
        if operation_name is not None:
            payload["operationName"] = operation_name
        return await self._post(payload)

    async def execute_persisted(
        self, query: str, variables: Optional[dict[str, Any]] = None
    ) -> GraphQLResponse:
        """Automatic Persisted Queries: hash first, retry with full text
        only when the server answers PersistedQueryNotFound."""
        digest = hashlib.sha256(query.encode("utf-8")).hexdigest()
        ext = {"persistedQuery": {"version": 1, "sha256Hash": digest}}
        first = await self._post({"extensions": ext, "variables": variables or {}})
        if not self._is_apq_miss(first):
            return first
        # Retry once, sending query text + hash so the server can register it.
        return await self._post(
            {"query": query, "extensions": ext, "variables": variables or {}}
        )

    @staticmethod
    def _is_apq_miss(response: GraphQLResponse) -> bool:
        return any(
            (e.get("extensions") or {}).get("code") == "PersistedQueryNotFound"
            for e in response.errors
        )

    async def _post(self, payload: dict[str, Any]) -> GraphQLResponse:
        try:
            response = await self._client.post(
                GRAPHQL_PATH,
                content=json.dumps(payload),
                headers={"Content-Type": "application/json"},
            )
        except httpx.HTTPError as exc:
            raise GraphQLTransportError(f"transport failure: {exc}") from exc
        if response.status_code >= 500:
            raise GraphQLTransportError(f"server error: HTTP {response.status_code}")
        body = response.json()
        errors = body.get("errors") or []
        # 4xx here means the request never executed (parse/cost rejection).
        if response.status_code >= 400:
            raise GraphQLFieldErrors(errors, data=None)
        return GraphQLResponse(data=body.get("data"), errors=errors)


CATALOG_QUERY = """
query CatalogPage($first: Int!) {
  products(first: $first) {
    edges { node { name category { name } } }
    pageInfo { hasNextPage endCursor }
  }
}
"""


async def demo() -> None:
    import logging

    from server import create_app  # in-process app: zero network

    # Strawberry logs every field error; keep the demo output readable.
    logging.getLogger("strawberry.execution").setLevel(logging.CRITICAL)

    transport = httpx.ASGITransport(app=create_app())
    async with GraphQLClient("http://testserver", transport=transport) as client:
        # 1. Plain query with variables.
        page = await client.execute(CATALOG_QUERY, variables={"first": 2})
        edges = page.data["products"]["edges"]
        print(f"plain query   : {len(edges)} products, "
              f"hasNextPage={page.data['products']['pageInfo']['hasNextPage']}")

        # 2. APQ: first call misses, second is served hash-only.
        await client.execute_persisted(CATALOG_QUERY, variables={"first": 2})
        cached = await client.execute_persisted(CATALOG_QUERY, variables={"first": 3})
        print(f"APQ round trip: {len(cached.data['products']['edges'])} products")

        # 3. Field-level error: partial data + errors, HTTP 200.
        bad = await client.execute(
            "query { product(productId: 4) { name marginPercent } }"
        )
        print(f"field error   : data={bad.data} "
              f"code={bad.errors[0]['extensions']['code']}")

        # 4. Rejected request: over-depth query is refused pre-execution.
        try:
            deep = (
                "query Deep { products { edges { node { "
                + "reviews { " * 12 + "rating" + " }" * 12
                + " } } } }"
            )
            await client.execute(deep)
        except GraphQLFieldErrors as exc:
            print(f"depth rejected: {exc.errors[0]['extensions']['code']}")


if __name__ == "__main__":
    asyncio.run(demo())
