"""Listing 7 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""In-process test suite for the Northwind Robotics GraphQL catalog.

No sockets, no network, deterministic seed data. Async execution is driven
with asyncio.run so no pytest plugins are required.

Run:  pytest test_catalog.py -q
"""

from __future__ import annotations

import asyncio
import logging
from typing import Any, Optional

import pytest

from catalog_repository import CatalogRepository
from catalog_schema import Context, schema
from cost_control import (
    PersistedQueryRegistry,
    analyze_document,
    enforce_cost_budget,
    QueryCostExceeded,
    execute_graphql_http,
)
from graphql import parse

logging.getLogger("strawberry.execution").setLevel(logging.CRITICAL)


def run(
    query: str,
    variables: Optional[dict[str, Any]] = None,
    repo: Optional[CatalogRepository] = None,
):
    """Execute against a fresh repository unless one is supplied."""
    repo = repo or CatalogRepository()
    context = Context(repo)
    result = asyncio.run(
        schema.execute(query, variable_values=variables, context_value=context)
    )
    return result, repo


# ---------------------------------------------------------------------------
# Queries, variables, aliases, fragments
# ---------------------------------------------------------------------------


def test_products_connection_first_page() -> None:
    result, _ = run(
        """
        query Page($first: Int!) {
          products(first: $first) {
            edges { cursor node { sku name } }
            pageInfo { hasNextPage hasPreviousPage startCursor endCursor }
            totalCount
          }
        }
        """,
        variables={"first": 2},
    )
    assert result.errors is None
    data = result.data["products"]
    assert [e["node"]["sku"] for e in data["edges"]] == ["NWR-ACT-100", "NWR-ACT-200"]
    assert data["pageInfo"]["hasNextPage"] is True
    assert data["pageInfo"]["hasPreviousPage"] is False
    assert data["totalCount"] == 5


def test_connection_walk_is_gapless() -> None:
    """Walking by cursor visits every product exactly once."""
    seen: list[str] = []
    after: Optional[str] = None
    for _ in range(10):
        result, _ = run(
            """
            query Walk($first: Int!, $after: String) {
              products(first: $first, after: $after) {
                edges { cursor node { sku } }
                pageInfo { hasNextPage endCursor }
              }
            }
            """,
            variables={"first": 2, "after": after},
        )
        assert result.errors is None
        page = result.data["products"]
        seen.extend(e["node"]["sku"] for e in page["edges"])
        if not page["pageInfo"]["hasNextPage"]:
            break
        after = page["pageInfo"]["endCursor"]
    assert seen == [
        "NWR-ACT-100", "NWR-ACT-200", "NWR-SEN-310", "NWR-SEN-410", "NWR-CTL-900",
    ]


def test_invalid_cursor_returns_field_error() -> None:
    result, _ = run(
        'query { products(first: 2, after: "%%%") { edges { cursor } } }'
    )
    assert result.data == {"products": None}
    assert result.errors is not None
    assert result.errors[0].extensions["code"] == "BAD_CURSOR"


def test_status_filter_and_alias() -> None:
    result, _ = run(
        """
        query {
          active: products(first: 10, status: ACTIVE) { edges { node { sku } } }
          retired: products(first: 10, status: DISCONTINUED) {
            edges { node { sku } }
          }
        }
        """
    )
    assert result.errors is None
    assert [e["node"]["sku"] for e in result.data["active"]["edges"]] == [
        "NWR-ACT-100", "NWR-ACT-200", "NWR-SEN-310", "NWR-CTL-900",
    ]
    assert [e["node"]["sku"] for e in result.data["retired"]["edges"]] == [
        "NWR-SEN-410"
    ]


def test_fragments_and_skip_directive() -> None:
    result, _ = run(
        """
        query F($withReviews: Boolean!) {
          product(productId: 1) {
            ...ProductCard
          }
        }
        fragment ProductCard on Product {
          name
          reviews @skip(if: $withReviews) { rating }
        }
        """,
        variables={"withReviews": True},
    )
    assert result.errors is None
    assert result.data == {"product": {"name": "Servo Linear Actuator 100mm"}}


# ---------------------------------------------------------------------------
# Nullability propagation on errors
# ---------------------------------------------------------------------------


def test_non_null_field_error_nulls_the_product() -> None:
    """marginPercent is Int! and raises for product 4 (no cost data).

    Per the spec's null-propagation rule the error bubbles to the nearest
    nullable position: the whole `product` field becomes null, and the
    response is partial: HTTP 200 with data + errors.
    """
    result, _ = run("query { product(productId: 4) { name marginPercent } }")
    assert result.data == {"product": None}
    assert result.errors is not None
    error = result.errors[0]
    assert error.path == ["product", "marginPercent"]
    assert error.extensions["code"] == "COST_DATA_UNAVAILABLE"


def test_nullable_sibling_survives_in_list() -> None:
    """Inside a nullable list element, only that element nulls out."""
    result, _ = run(
        """
        query {
          products(first: 5) {
            edges { node { sku marginPercent } }
          }
        }
        """
    )
    assert result.errors is not None
    nodes = [e["node"] for e in result.data["products"]["edges"]]
    assert nodes[3] is None  # product 4 nulled by propagation
    assert nodes[0]["marginPercent"] == 54  # siblings intact


# ---------------------------------------------------------------------------
# Mutations: typed errors via union payloads
# ---------------------------------------------------------------------------


ADD_REVIEW = """
mutation Add($input: AddReviewInput!) {
  addReview(input: $input) {
    __typename
    ... on AddReviewSuccess { review { id rating headline } }
    ... on AddReviewError { code message }
  }
}
"""


def test_add_review_success() -> None:
    result, _ = run(
        ADD_REVIEW,
        variables={"input": {"productId": 2, "rating": 4, "headline": "Solid"}},
    )
    assert result.errors is None
    payload = result.data["addReview"]
    assert payload["__typename"] == "AddReviewSuccess"
    assert payload["review"]["rating"] == 4


@pytest.mark.parametrize(
    "input_vars, code",
    [
        ({"productId": 2, "rating": 0, "headline": "Bad"}, "RATING_OUT_OF_RANGE"),
        ({"productId": 2, "rating": 6, "headline": "Bad"}, "RATING_OUT_OF_RANGE"),
        ({"productId": 2, "rating": 5, "headline": "   "}, "EMPTY_HEADLINE"),
        ({"productId": 999, "rating": 5, "headline": "Ghost"}, "PRODUCT_NOT_FOUND"),
    ],
)
def test_add_review_typed_errors(input_vars: dict[str, Any], code: str) -> None:
    result, _ = run(ADD_REVIEW, variables={"input": input_vars})
    assert result.errors is None  # expected failure is data, not an exception
    payload = result.data["addReview"]
    assert payload["__typename"] == "AddReviewError"
    assert payload["code"] == code


# ---------------------------------------------------------------------------
# N+1: measured query counts
# ---------------------------------------------------------------------------


CATALOG_QUERY = """
query CatalogPage($first: Int!) {
  products(first: $first) {
    edges { node { name category { name } reviews { rating } } }
  }
}
"""


def _count_queries(use_loaders: bool) -> int:
    repo = CatalogRepository()
    context = Context(repo, use_loaders=use_loaders)
    result = asyncio.run(
        schema.execute(
            CATALOG_QUERY, variable_values={"first": 5}, context_value=context
        )
    )
    assert result.errors is None
    return repo.query_count


def test_nplus1_naive_explosion() -> None:
    assert _count_queries(use_loaders=False) == 11  # 1 + 5 + 5


def test_dataloader_collapses_nplus1() -> None:
    assert _count_queries(use_loaders=True) == 3  # 1 + 1 + 1


# ---------------------------------------------------------------------------
# Cost control: depth, complexity, persisted queries
# ---------------------------------------------------------------------------


def test_depth_limiter_rejects_deep_query() -> None:
    deep = (
        "query Deep { products { edges { node { "
        + "reviews { " * 12 + "rating" + " }" * 12 + " } } } }"
    )
    with pytest.raises(QueryCostExceeded) as excinfo:
        enforce_cost_budget(parse(deep))
    assert excinfo.value.code == "DEPTH_LIMIT_EXCEEDED"


def test_complexity_scales_with_page_size() -> None:
    small = analyze_document(
        parse("query { products(first: 2) { edges { node { name } } } }")
    )
    large = analyze_document(
        parse("query { products(first: 50) { edges { node { name } } } }")
    )
    assert large.complexity > small.complexity


def test_complexity_limit_rejects_god_query() -> None:
    god = "query { " + " ".join(
        f"p{i}: products(first: 50) {{ edges {{ node {{ name reviews {{ rating }} }} }} }}"
        for i in range(8)
    ) + " }"
    with pytest.raises(QueryCostExceeded) as excinfo:
        enforce_cost_budget(parse(god))
    assert excinfo.value.code == "COMPLEXITY_LIMIT_EXCEEDED"


def test_persisted_query_apq_flow() -> None:
    registry = PersistedQueryRegistry()
    factory = lambda: Context(CatalogRepository())  # noqa: E731

    async def apq_round_trip() -> tuple[int, dict[str, Any]]:
        import hashlib

        digest = hashlib.sha256(CATALOG_QUERY.encode("utf-8")).hexdigest()
        ext = {"persistedQuery": {"version": 1, "sha256Hash": digest}}
        # Step 1: hash only -> PersistedQueryNotFound (HTTP 200)
        status, body = await execute_graphql_http(
            {"extensions": ext, "variables": {"first": 2}},
            schema=schema, registry=registry, context_factory=factory,
        )
        assert status == 200
        assert body["errors"][0]["extensions"]["code"] == "PersistedQueryNotFound"
        # Step 2: query + hash -> executes and registers
        return await execute_graphql_http(
            {"query": CATALOG_QUERY, "extensions": ext, "variables": {"first": 2}},
            schema=schema, registry=registry, context_factory=factory,
        )

    status, body = asyncio.run(apq_round_trip())
    assert status == 200
    assert "errors" not in body
    assert len(body["data"]["products"]["edges"]) == 2


def test_persisted_query_hash_mismatch_rejected() -> None:
    registry = PersistedQueryRegistry()

    async def mismatch() -> tuple[int, dict[str, Any]]:
        return await execute_graphql_http(
            {
                "query": "query { product(productId: 1) { name } }",
                "extensions": {"persistedQuery": {"sha256Hash": "0" * 64}},
            },
            schema=schema,
            registry=registry,
            context_factory=lambda: Context(CatalogRepository()),
        )

    status, body = asyncio.run(mismatch())
    assert status == 200
    assert body["errors"][0]["extensions"]["code"] == "PersistedQueryMismatch"


def test_introspection_blocked_by_default() -> None:
    async def probe() -> tuple[int, dict[str, Any]]:
        return await execute_graphql_http(
            {"query": "{ __schema { types { name } } }"},
            schema=schema,
            registry=PersistedQueryRegistry(),
            context_factory=lambda: Context(CatalogRepository()),
        )

    status, body = asyncio.run(probe())
    assert status == 400
    assert body["errors"][0]["extensions"]["code"] == "INTROSPECTION_DISABLED"


def test_introspection_allowed_when_gated_on() -> None:
    async def probe() -> tuple[int, dict[str, Any]]:
        return await execute_graphql_http(
            {"query": "{ __schema { queryType { name } } }"},
            schema=schema,
            registry=PersistedQueryRegistry(),
            context_factory=lambda: Context(CatalogRepository()),
            allow_introspection=True,
        )

    status, body = asyncio.run(probe())
    assert status == 200
    assert body["data"]["__schema"]["queryType"]["name"] == "Query"
