"""Listing 3 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""N+1 demonstration: naive per-field store reads vs DataLoader batching.

Runs the same GraphQL operation twice against the same repository and
prints measured store-query counts. Deterministic and offline.

Run:  python nplus1_demo.py
"""

from __future__ import annotations

import asyncio

from catalog_repository import CatalogRepository
from catalog_schema import Context, schema

CATALOG_QUERY = """
query CatalogPage($first: Int!) {
  products(first: $first) {
    edges {
      node {
        name
        category { name }
        reviews { rating }
      }
    }
  }
}
"""


async def run_once(use_loaders: bool) -> tuple[int, int]:
    """Execute CATALOG_QUERY; return (store query count, products returned)."""
    repo = CatalogRepository()
    context = Context(repo, use_loaders=use_loaders)
    result = await schema.execute(
        CATALOG_QUERY, variable_values={"first": 5}, context_value=context
    )
    assert result.errors is None, result.errors
    assert result.data is not None
    return repo.query_count, len(result.data["products"]["edges"])


def main() -> None:
    naive_count, n = run_and_count(use_loaders=False)
    batched_count, _ = run_and_count(use_loaders=True)

    print(f"GraphQL operation asks for {n} products + category + reviews")
    print(f"  naive resolvers   : {naive_count:3d} store queries "
          f"(1 page + {n} category + {n} review reads)")
    print(f"  DataLoader path   : {batched_count:3d} store queries "
          "(1 page + 1 batched category read + 1 batched review read)")
    assert naive_count == 1 + 2 * n
    assert batched_count == 3
    print("N+1 reproduced and collapsed. OK")


def run_and_count(use_loaders: bool) -> tuple[int, int]:
    return asyncio.run(run_once(use_loaders))


if __name__ == "__main__":
    main()
