"""Listing 4 extracted from chapters/chapter_12_graphql.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Cost control for GraphQL: depth limiting, complexity estimation, and
persisted queries (allow-list + APQ protocol), plus an HTTP-shaped
execution entry point used by the FastAPI server and the offline tests.

Everything here operates on the *parsed document* before execution, so
expensive operations are rejected without touching a resolver.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Awaitable, Callable, Optional

import strawberry
from graphql import (
    DocumentNode,
    FieldNode,
    FragmentDefinitionNode,
    FragmentSpreadNode,
    InlineFragmentNode,
    IntValueNode,
    OperationDefinitionNode,
    parse,
)
from graphql.error import GraphQLSyntaxError

MAX_DEPTH = 7
MAX_COMPLEXITY = 200
DEFAULT_LIST_MULTIPLIER = 10  # assumed page size when `first` is absent


@dataclass(frozen=True)
class OperationMetrics:
    depth: int
    complexity: int


class QueryCostExceeded(Exception):
    """Raised when an operation breaches the depth or complexity budget."""

    def __init__(self, message: str, code: str) -> None:
        super().__init__(message)
        self.code = code


# ---------------------------------------------------------------------------
# Static analysis: depth + complexity
# ---------------------------------------------------------------------------


def _int_argument(field: FieldNode, name: str) -> Optional[int]:
    for arg in field.arguments:
        if arg.name.value == name and isinstance(arg.value, IntValueNode):
            return int(arg.value.value)
    return None


def _list_multiplier(field: FieldNode) -> int:
    """List-returning fields multiply the cost of their sub-selection.

    Only the *top* list field multiplies (the connection); edges/node are
    structural and cost 1, otherwise nesting multiplies twice.
    """
    page = _int_argument(field, "first") or _int_argument(field, "last")
    if page is not None:
        return max(1, min(page, 50))
    if field.name.value in ("products", "reviews"):
        return DEFAULT_LIST_MULTIPLIER
    return 1


def analyze_document(document: DocumentNode) -> OperationMetrics:
    """Compute (max depth, total complexity) over all operations.

    Depth = longest field path, fragment spreads expanded (cycles rejected).
    Complexity = field count, with list fields multiplying their subtree by
    the requested page size (or a conservative default).
    """
    fragments = {
        d.name.value: d
        for d in document.definitions
        if isinstance(d, FragmentDefinitionNode)
    }

    def walk(
        selections: tuple, depth: int, seen: frozenset[str]
    ) -> tuple[int, int]:
        max_depth, cost = depth, 0
        for sel in selections:
            if isinstance(sel, FieldNode):
                child_depth, child_cost = (
                    walk(sel.selection_set.selections, depth + 1, frozenset())
                    if sel.selection_set
                    else (depth + 1, 0)
                )
                cost += 1 + _list_multiplier(sel) * child_cost
                max_depth = max(max_depth, child_depth)
            elif isinstance(sel, InlineFragmentNode):
                d, c = walk(sel.selection_set.selections, depth, seen)
                cost += c
                max_depth = max(max_depth, d)
            elif isinstance(sel, FragmentSpreadNode):
                name = sel.name.value
                if name in seen or name not in fragments:
                    raise QueryCostExceeded(
                        f"invalid fragment spread: {name}", "BAD_FRAGMENT"
                    )
                d, c = walk(
                    fragments[name].selection_set.selections, depth, seen | {name}
                )
                cost += c
                max_depth = max(max_depth, d)
        return max_depth, cost

    worst = OperationMetrics(depth=0, complexity=0)
    for definition in document.definitions:
        if isinstance(definition, OperationDefinitionNode):
            d, c = walk(definition.selection_set.selections, 0, frozenset())
            worst = OperationMetrics(max(worst.depth, d), max(worst.complexity, c))
    return worst


def enforce_cost_budget(
    document: DocumentNode, max_depth: int = MAX_DEPTH, max_cost: int = MAX_COMPLEXITY
) -> OperationMetrics:
    metrics = analyze_document(document)
    if metrics.depth > max_depth:
        raise QueryCostExceeded(
            f"query depth {metrics.depth} exceeds limit {max_depth}",
            "DEPTH_LIMIT_EXCEEDED",
        )
    if metrics.complexity > max_cost:
        raise QueryCostExceeded(
            f"query complexity {metrics.complexity} exceeds limit {max_cost}",
            "COMPLEXITY_LIMIT_EXCEEDED",
        )
    return metrics


# ---------------------------------------------------------------------------
# Persisted queries: allow-list registry + APQ resolution
# ---------------------------------------------------------------------------


class ApqError(Exception):
    def __init__(self, message: str, code: str) -> None:
        super().__init__(message)
        self.code = code


class PersistedQueryRegistry:
    """Allow-list of pre-registered operation documents keyed by SHA-256."""

    def __init__(self) -> None:
        self._by_hash: dict[str, str] = {}

    def register(self, document: str) -> str:
        digest = hashlib.sha256(document.encode("utf-8")).hexdigest()
        self._by_hash[digest] = document
        return digest

    def get(self, digest: str) -> Optional[str]:
        return self._by_hash.get(digest)


def resolve_document(payload: dict[str, Any], registry: PersistedQueryRegistry) -> str:
    """Resolve the operation text from a GraphQL-over-HTTP payload.

    Implements the APQ flow server side: a hash-only payload must already
    be registered; a query+hash payload is verified against its hash and
    then registered.
    """
    query = payload.get("query")
    extensions = payload.get("extensions") or {}
    persisted = extensions.get("persistedQuery") or {}
    digest = persisted.get("sha256Hash")

    if digest is None:
        if not query:
            raise ApqError("no query provided", "BAD_REQUEST")
        return query
    if not isinstance(digest, str) or len(digest) != 64:
        raise ApqError("malformed persistedQuery hash", "BAD_REQUEST")
    if query is None:
        stored = registry.get(digest)
        if stored is None:
            raise ApqError("persisted query not found", "PersistedQueryNotFound")
        return stored
    actual = hashlib.sha256(query.encode("utf-8")).hexdigest()
    if actual != digest:
        raise ApqError("provided hash does not match query", "PersistedQueryMismatch")
    registry.register(query)
    return query


def uses_introspection(document: DocumentNode) -> bool:
    """True if any selected field is a meta field (__schema / __type).

    AST-based, not substring-based: aliases and fragments cannot hide it.
    (``__typename`` is excluded: it is cheap and used by client caches.)
    """
    def walk(selections: tuple) -> bool:
        for sel in selections:
            if isinstance(sel, FieldNode):
                if sel.name.value in ("__schema", "__type"):
                    return True
                if sel.selection_set and walk(sel.selection_set.selections):
                    return True
            elif isinstance(sel, (InlineFragmentNode, FragmentDefinitionNode)):
                if walk(sel.selection_set.selections):
                    return True
        return False

    for definition in document.definitions:
        if hasattr(definition, "selection_set"):
            if walk(tuple(definition.selection_set.selections)):
                return True
    return False


# ---------------------------------------------------------------------------
# HTTP-shaped execution entry point (used by server.py and tests)
# ---------------------------------------------------------------------------


def _error_body(message: str, code: str) -> dict[str, Any]:
    return {"errors": [{"message": message, "extensions": {"code": code}}]}


async def execute_graphql_http(
    payload: dict[str, Any],
    *,
    schema: strawberry.Schema,
    registry: PersistedQueryRegistry,
    context_factory: Callable[[], Any],
    max_depth: int = MAX_DEPTH,
    max_cost: int = MAX_COMPLEXITY,
    allow_introspection: bool = False,
) -> tuple[int, dict[str, Any]]:
    """Parse -> resolve persisted -> budget-check -> execute.

    Returns (HTTP status, response body) with GraphQL semantics: execution
    errors are HTTP 200 with a populated ``errors`` array; malformed or
    over-budget requests are HTTP 400.
    """
    try:
        document_text = resolve_document(payload, registry)
    except ApqError as exc:
        # APQ misses are HTTP 200 per the protocol: the client retries.
        status = 200 if exc.code.startswith("PersistedQuery") else 400
        return status, _error_body(str(exc), exc.code)

    try:
        document = parse(document_text)
    except GraphQLSyntaxError as exc:
        return 400, _error_body(f"syntax error: {exc.message}", "GRAPHQL_PARSE_FAILED")

    if not allow_introspection and uses_introspection(document):
        return 400, _error_body(
            "introspection is disabled", "INTROSPECTION_DISABLED"
        )

    try:
        enforce_cost_budget(document, max_depth, max_cost)
    except QueryCostExceeded as exc:
        return 400, _error_body(str(exc), exc.code)

    result = await schema.execute(
        document_text,
        variable_values=payload.get("variables"),
        operation_name=payload.get("operationName"),
        context_value=context_factory(),
    )
    body: dict[str, Any] = {"data": result.data}
    if result.errors:
        body["errors"] = [err.formatted for err in result.errors]
    return 200, body
