"""Listing 6 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Deterministic tests for the three-service chaos drill.

Assertions are on COUNTS (how many requests reached the broken inventory),
never on wall-clock latency. The 30 catalog calls run concurrently via
``asyncio.gather``; the failure mode under test (inventory hard-down,
immediate 500) is fully deterministic.
"""
from __future__ import annotations

import asyncio

import httpx

from demo_services import (
    BULKHEAD_PERMITS,
    build_system,
    run_drill,
)


def test_happy_path_catalog_joins_inventory_and_warehouse() -> None:
    async def main() -> None:
        system = build_system(use_breaker=True)  # chaos OFF
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=system.apps["catalog"]),
            base_url="http://catalog.test",
        ) as client:
            response = await client.get("/products/NR-1001")
        assert response.status_code == 200
        body = response.json()
        assert body["name"] == "Warehouse Picker Bot"
        assert body["availability"] == {"sku": "NR-1001", "available": 5}
        assert system.stats.inventory_calls == 1
        assert system.stats.warehouse_calls == 1

    asyncio.run(main())


def test_without_breaker_every_request_reaches_the_broken_inventory() -> None:
    result = asyncio.run(run_drill(requests=30, use_breaker=False))
    assert result.catalog_errors == 30
    assert result.inventory_calls == 30   # full load hits the sick dependency
    assert result.circuit_open_rejections == 0


def test_with_breaker_most_requests_fail_fast() -> None:
    result = asyncio.run(run_drill(requests=30, use_breaker=True))
    assert result.catalog_errors == 30    # still errors: the dependency IS down
    # ...but almost none touch inventory: breaker opens after 4 failures
    # (minimum_calls, 100% failure rate >= 0.5 threshold).
    assert result.inventory_calls < result.requests
    assert result.circuit_open_rejections == 30 - result.inventory_calls
    assert result.circuit_open_rejections >= 30 - BULKHEAD_PERMITS


def test_breaker_state_transitions_are_emitted_during_drill() -> None:
    system = build_system(use_breaker=True)
    system.chaos.always_fail = True

    async def main() -> None:
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=system.apps["catalog"]),
            base_url="http://catalog.test",
        ) as client:
            await asyncio.gather(*(client.get("/products/NR-1001") for _ in range(30)))

    asyncio.run(main())
    transitions = [f for e, f in system.events if e == "state_change"]
    assert {"previous": "closed", "current": "open"} in [
        {"previous": t["previous"], "current": t["current"]} for t in transitions
    ]
    # Inventory hard-down and breaker open-duration (30s) >> drill duration:
    # exactly one transition, and no half-open probes mid-drill.
    assert len(transitions) == 1
