"""Listing 5 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Three-service Northwind Robotics demo: catalog -> inventory -> warehouse.

All services are in-process FastAPI apps wired together with
``httpx.AsyncClient`` over ``ASGITransport``: real ASGI request/response
cycles, real timeouts, zero sockets, zero network.

Resilience posture at the catalog edge:
  * per-hop timeouts (catalog->inventory tighter than the caller's budget),
  * a circuit breaker around the inventory dependency (optional, so the
    chaos drill can measure before/after),
  * a bulkhead: a semaphore bounding concurrent calls into inventory.

The chaos harness flips the inventory hop into a failure or latency mode
and measures how many requests actually reach it, with and without the
breaker.
"""
from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass, field
from typing import Any

import httpx
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from circuit_breaker import (
    BreakerConfig,
    CircuitBreaker,
    CircuitOpenError,
)

CATALOG_TIMEOUT = 0.25      # seconds; the caller's budget is larger
INVENTORY_TIMEOUT = 0.20
WAREHOUSE_TIMEOUT = 0.15
BULKHEAD_PERMITS = 8        # max concurrent catalog -> inventory calls

CATALOG = {
    "NR-1001": {"sku": "NR-1001", "name": "Warehouse Picker Bot", "price": 18499.00},
    "NR-2002": {"sku": "NR-2002", "name": "Conveyor Vision Kit", "price": 3299.50},
}


@dataclass
class ChaosConfig:
    """Mutable fault-injection knobs for the inventory service."""

    always_fail: bool = False
    latency_seconds: float = 0.0


@dataclass
class ServiceStats:
    inventory_calls: int = 0
    warehouse_calls: int = 0


# --------------------------------------------------------------------------
# Warehouse (leaf service)
# --------------------------------------------------------------------------
def build_warehouse_app(stats: ServiceStats) -> FastAPI:
    app = FastAPI(title="warehouse")

    @app.get("/stock/{sku}")
    async def stock(sku: str) -> dict[str, Any]:
        stats.warehouse_calls += 1
        return {"sku": sku, "on_hand": 7, "reserved": 2}

    return app


# --------------------------------------------------------------------------
# Inventory (middle service; chaos target)
# --------------------------------------------------------------------------
def build_inventory_app(
    warehouse_client: httpx.AsyncClient,
    chaos: ChaosConfig,
    stats: ServiceStats,
) -> FastAPI:
    app = FastAPI(title="inventory")

    @app.get("/availability/{sku}")
    async def availability(sku: str) -> dict[str, Any]:
        stats.inventory_calls += 1
        if chaos.latency_seconds > 0:
            await asyncio.sleep(chaos.latency_seconds)
        if chaos.always_fail:
            return JSONResponse(
                status_code=500,
                content={"detail": "chaos: inventory database unreachable"},
            )
        stock = await warehouse_client.get(f"/stock/{sku}", timeout=WAREHOUSE_TIMEOUT)
        body = stock.json()
        return {
            "sku": sku,
            "available": body["on_hand"] - body["reserved"],
        }

    return app


# --------------------------------------------------------------------------
# Catalog (edge service; owns the resilience policies)
# --------------------------------------------------------------------------
def build_catalog_app(
    inventory_client: httpx.AsyncClient,
    breaker: CircuitBreaker | None,
    bulkhead: asyncio.Semaphore,
) -> FastAPI:
    app = FastAPI(title="catalog")

    @app.get("/products/{sku}")
    async def product(sku: str, request: Request) -> Any:
        product_row = CATALOG.get(sku)
        if product_row is None:
            return JSONResponse(status_code=404, content={"detail": "unknown sku"})

        async def fetch_availability() -> dict[str, Any]:
            async with bulkhead:  # bulkhead: bounded concurrency into inventory
                response = await inventory_client.get(
                    f"/availability/{sku}", timeout=CATALOG_TIMEOUT
                )
            response.raise_for_status()
            return response.json()

        try:
            if breaker is not None:
                availability = await breaker.acall(fetch_availability)
            else:
                availability = await fetch_availability()
        except CircuitOpenError:
            return JSONResponse(
                status_code=503,
                content={"detail": "inventory unavailable (circuit open)",
                         "circuit_open": True},
            )
        except (httpx.HTTPError, asyncio.TimeoutError) as exc:
            return JSONResponse(
                status_code=503,
                content={"detail": f"inventory call failed: {type(exc).__name__}",
                         "circuit_open": False},
            )
        return {**product_row, "availability": availability}

    return app


# --------------------------------------------------------------------------
# Wiring + chaos drill harness
# --------------------------------------------------------------------------
@dataclass
class DrillResult:
    requests: int
    catalog_errors: int
    circuit_open_rejections: int
    inventory_calls: int
    warehouse_calls: int
    wall_seconds: float


@dataclass
class DemoSystem:
    apps: dict[str, FastAPI]
    chaos: ChaosConfig
    stats: ServiceStats
    events: list[tuple[str, dict]] = field(default_factory=list)


def build_system(*, use_breaker: bool) -> DemoSystem:
    chaos = ChaosConfig()
    stats = ServiceStats()
    events: list[tuple[str, dict]] = []

    warehouse_app = build_warehouse_app(stats)
    warehouse_client = httpx.AsyncClient(
        transport=httpx.ASGITransport(app=warehouse_app),
        base_url="http://warehouse.test",
    )
    inventory_app = build_inventory_app(warehouse_client, chaos, stats)
    inventory_client = httpx.AsyncClient(
        transport=httpx.ASGITransport(app=inventory_app),
        base_url="http://inventory.test",
        # Bulkhead on the client side too: a small, dedicated pool.
        limits=httpx.Limits(max_connections=BULKHEAD_PERMITS),
    )
    breaker = None
    if use_breaker:
        breaker = CircuitBreaker(
            "inventory",
            BreakerConfig(
                failure_rate_threshold=0.5,
                window_seconds=60.0,
                minimum_calls=4,
                open_duration=30.0,  # >> drill duration: no probes mid-drill
                half_open_max_probes=1,
            ),
            on_event=lambda event, fields: events.append((event, fields)),
        )
    catalog_app = build_catalog_app(
        inventory_client, breaker, asyncio.Semaphore(BULKHEAD_PERMITS)
    )
    return DemoSystem(
        apps={"catalog": catalog_app, "inventory": inventory_app,
              "warehouse": warehouse_app},
        chaos=chaos,
        stats=stats,
        events=events,
    )


async def run_drill(
    requests: int = 30, *, use_breaker: bool, sku: str = "NR-1001"
) -> DrillResult:
    """Fire ``requests`` concurrent catalog calls at a broken inventory."""
    system = build_system(use_breaker=use_breaker)
    system.chaos.always_fail = True  # inventory is hard-down for the drill
    started = time.perf_counter()
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=system.apps["catalog"]),
        base_url="http://catalog.test",
    ) as catalog:
        responses = await asyncio.gather(
            *(catalog.get(f"/products/{sku}") for _ in range(requests))
        )
    elapsed = time.perf_counter() - started
    errors = sum(1 for r in responses if r.status_code >= 500)
    open_rejections = sum(
        1 for r in responses if r.json().get("circuit_open") is True
    )
    return DrillResult(
        requests=requests,
        catalog_errors=errors,
        circuit_open_rejections=open_rejections,
        inventory_calls=system.stats.inventory_calls,
        warehouse_calls=system.stats.warehouse_calls,
        wall_seconds=elapsed,
    )


async def _main() -> None:
    print("Chaos drill: inventory hard-down, 30 concurrent catalog requests")
    for use_breaker in (False, True):
        result = await run_drill(use_breaker=use_breaker)
        label = "WITH breaker " if use_breaker else "WITHOUT breaker"
        print(
            f"{label} | catalog 5xx: {result.catalog_errors:>2}/"
            f"{result.requests} | circuit-open fast-fails: "
            f"{result.circuit_open_rejections:>2} | calls reaching inventory: "
            f"{result.inventory_calls:>2} | wall: {result.wall_seconds:.3f}s"
        )


if __name__ == "__main__":
    asyncio.run(_main())
