"""Listing 1 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Production-grade circuit breaker: full state machine, rolling failure
window, half-open probes, metrics hooks, sync + async support.

Deterministic: time comes from an injected ``Clock``; tests drive a manual
clock. No wall-clock reads inside the state machine.
"""
from __future__ import annotations

import threading
import time
from collections import deque
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from enum import Enum
from typing import Any, Protocol, TypeVar

T = TypeVar("T")


class Clock(Protocol):
    """Monotonic time source, in seconds."""

    def now(self) -> float: ...


class SystemClock:
    """Production clock backed by ``time.monotonic``."""

    def now(self) -> float:
        return time.monotonic()


class BreakerState(str, Enum):
    CLOSED = "closed"        # traffic flows; failures are counted
    OPEN = "open"            # traffic is rejected without touching the dependency
    HALF_OPEN = "half_open"  # a limited number of probe calls are admitted


class CircuitOpenError(RuntimeError):
    """Raised by ``call``/``acall`` when the breaker refuses the call."""


@dataclass(frozen=True, slots=True)
class BreakerConfig:
    """Tuning knobs for one circuit breaker.

    failure_rate_threshold:      open when failures / calls >= this, in (0, 1]
    window_seconds:              rolling observation window length
    minimum_calls:               window is not evaluated until this many calls
    open_duration:               seconds to stay open before the first probe
    half_open_max_probes:        concurrent probe calls admitted in half-open
    half_open_success_threshold: consecutive probe successes required to close
    """

    failure_rate_threshold: float = 0.5
    window_seconds: float = 30.0
    minimum_calls: int = 10
    open_duration: float = 5.0
    half_open_max_probes: int = 1
    half_open_success_threshold: int = 1

    def __post_init__(self) -> None:
        if not 0.0 < self.failure_rate_threshold <= 1.0:
            raise ValueError("failure_rate_threshold must be in (0, 1]")
        if self.window_seconds <= 0 or self.open_duration <= 0:
            raise ValueError("window_seconds and open_duration must be > 0")
        if self.minimum_calls < 1 or self.half_open_max_probes < 1:
            raise ValueError("minimum_calls and half_open_max_probes must be >= 1")
        if self.half_open_success_threshold < 1:
            raise ValueError("half_open_success_threshold must be >= 1")


MetricsHook = Callable[[str, dict[str, Any]], None]


class CircuitBreaker:
    """A circuit breaker guarding exactly ONE dependency.

    States and transitions (Section 3.5 of the chapter):

        CLOSED  --[window failure rate >= threshold]--> OPEN
        OPEN    --[open_duration elapsed]------------> HALF_OPEN
        HALF_OPEN --[probe success x threshold]------> CLOSED
        HALF_OPEN --[probe failure]------------------> OPEN

    Thread-safe for the sync path; the async path is safe on a single
    event loop. Late completions of calls admitted before a state change
    are ignored, which keeps probe accounting exact.
    """

    def __init__(
        self,
        name: str,
        config: BreakerConfig | None = None,
        *,
        clock: Clock | None = None,
        on_event: MetricsHook | None = None,
        is_failure: Callable[[BaseException], bool] | None = None,
    ) -> None:
        if not name:
            raise ValueError("breaker name is required (one breaker per dependency)")
        self._name = name
        self._config = config or BreakerConfig()
        self._clock: Clock = clock if clock is not None else SystemClock()
        self._on_event = on_event
        # Caller-fault exceptions (e.g. ValueError from validation) can be
        # excluded by supplying is_failure; they count as successes here.
        self._is_failure = is_failure or (lambda exc: True)
        self._state = BreakerState.CLOSED
        self._opened_at = 0.0
        self._window: deque[tuple[float, bool]] = deque()
        self._probes_in_flight = 0
        self._probe_successes = 0
        self._lock = threading.Lock()

    # ---- observability -------------------------------------------------
    @property
    def state(self) -> BreakerState:
        with self._lock:
            self._maybe_half_open(self._clock.now())
            return self._state

    def _emit(self, event: str, **fields: Any) -> None:
        if self._on_event is not None:
            self._on_event(event, {"breaker": self._name, **fields})

    # ---- state machine internals (call with self._lock held) ------------
    def _transition(self, to: BreakerState, now: float) -> None:
        if to is self._state:
            return
        previous = self._state
        self._state = to
        if to is BreakerState.OPEN:
            self._opened_at = now
        if to is BreakerState.HALF_OPEN:
            self._probes_in_flight = 0
            self._probe_successes = 0
        self._emit("state_change", previous=previous.value, current=to.value)

    def _maybe_half_open(self, now: float) -> None:
        if (
            self._state is BreakerState.OPEN
            and now - self._opened_at >= self._config.open_duration
        ):
            self._transition(BreakerState.HALF_OPEN, now)

    def _evict(self, now: float) -> None:
        horizon = now - self._config.window_seconds
        while self._window and self._window[0][0] <= horizon:
            self._window.popleft()

    def _admit(self) -> bool:
        """Return True if the admitted call is a half-open probe."""
        with self._lock:
            now = self._clock.now()
            self._maybe_half_open(now)
            if self._state is BreakerState.OPEN:
                self._emit("rejected", state=self._state.value)
                raise CircuitOpenError(
                    f"circuit {self._name!r} is OPEN; call rejected fast"
                )
            if self._state is BreakerState.HALF_OPEN:
                if self._probes_in_flight >= self._config.half_open_max_probes:
                    self._emit("rejected", state=self._state.value)
                    raise CircuitOpenError(
                        f"circuit {self._name!r} is HALF_OPEN; probe limit reached"
                    )
                self._probes_in_flight += 1
                return True
            return False

    def _after_call(self, *, success: bool, probe: bool) -> None:
        with self._lock:
            now = self._clock.now()
            self._emit(
                "call_success" if success else "call_failure",
                probe=probe,
                state=self._state.value,
            )
            if probe:
                self._probes_in_flight -= 1
                if success:
                    self._probe_successes += 1
                    if (
                        self._probe_successes
                        >= self._config.half_open_success_threshold
                    ):
                        self._window.clear()
                        self._transition(BreakerState.CLOSED, now)
                else:
                    # One failed probe is enough: the dependency is still sick.
                    self._transition(BreakerState.OPEN, now)
                return
            if self._state is not BreakerState.CLOSED:
                return  # admitted before a transition; late completion ignored
            self._window.append((now, success))
            self._evict(now)
            if len(self._window) >= self._config.minimum_calls:
                failures = sum(1 for _, ok in self._window if not ok)
                if failures / len(self._window) >= self._config.failure_rate_threshold:
                    self._transition(BreakerState.OPEN, now)

    # ---- public API ------------------------------------------------------
    def call(self, fn: Callable[..., T], *args: Any, **kwargs: Any) -> T:
        """Run ``fn`` through the breaker (synchronous path)."""
        probe = self._admit()
        try:
            result = fn(*args, **kwargs)
        except BaseException as exc:
            self._after_call(success=not self._is_failure(exc), probe=probe)
            raise
        self._after_call(success=True, probe=probe)
        return result

    async def acall(self, fn: Callable[..., Awaitable[T]], *args: Any, **kwargs: Any) -> T:
        """Run an awaitable through the breaker (asyncio path)."""
        probe = self._admit()
        try:
            result = await fn(*args, **kwargs)
        except BaseException as exc:
            self._after_call(success=not self._is_failure(exc), probe=probe)
            raise
        self._after_call(success=True, probe=probe)
        return result
