"""Listing 3 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Retry-budgeted HTTP client: token-bucket retry budget + jittered
backoff + deadline awareness.

Design rules implemented (Section 3.4):
  * The first attempt is free; every RETRY spends one budget token.
  * Tokens refill at a fixed rate, so steady-state retry traffic cannot
    exceed ``budget_refill_per_second`` retries/s process-wide.
  * Backoff is exponential with full jitter from a seeded RNG.
  * A call-level deadline caps total elapsed (virtual) time; a retry that
    would overshoot the deadline is never attempted.
"""
from __future__ import annotations

import random
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Protocol

import httpx


class Clock(Protocol):
    def now(self) -> float: ...
    def sleep(self, seconds: float) -> None: ...


class SystemClock:
    def now(self) -> float:
        return time.monotonic()

    def sleep(self, seconds: float) -> None:
        time.sleep(seconds)


class ManualClock:
    """Virtual clock for deterministic tests; ``sleep`` advances it."""

    def __init__(self, start: float = 0.0) -> None:
        self._now = start

    def now(self) -> float:
        return self._now

    def sleep(self, seconds: float) -> None:
        if seconds < 0:
            raise ValueError("cannot sleep for a negative duration")
        self._now += seconds


class RetryBudgetExhaustedError(RuntimeError):
    """The token bucket is empty: this retry would exceed the retry budget."""


class RetryDeadlineExceededError(RuntimeError):
    """The next backoff sleep would overshoot the call deadline."""


@dataclass(frozen=True, slots=True)
class RetryPolicy:
    max_retries: int = 3                      # retries, not attempts
    base_backoff: float = 0.05                # seconds; delay = base * 2**attempt
    max_backoff: float = 1.0
    deadline_seconds: float = 5.0             # whole-call deadline
    budget_tokens: float = 10.0               # bucket capacity (burst)
    budget_refill_per_second: float = 2.0     # sustained retry allowance
    retry_statuses: frozenset[int] = frozenset({429, 502, 503, 504})

    def __post_init__(self) -> None:
        if self.max_retries < 0:
            raise ValueError("max_retries must be >= 0")
        if self.base_backoff <= 0 or self.max_backoff < self.base_backoff:
            raise ValueError("require 0 < base_backoff <= max_backoff")
        if self.deadline_seconds <= 0:
            raise ValueError("deadline_seconds must be > 0")
        if self.budget_tokens < 0 or self.budget_refill_per_second <= 0:
            raise ValueError("budget parameters must be non-negative/positive")


class TokenBucketRetryBudget:
    """Process-wide retry budget. Tokens are spent ONLY by retries."""

    def __init__(self, capacity: float, refill_per_second: float, clock: Clock) -> None:
        if capacity <= 0 or refill_per_second <= 0:
            raise ValueError("capacity and refill_per_second must be > 0")
        self._capacity = capacity
        self._rate = refill_per_second
        self._clock = clock
        self._tokens = capacity
        self._last = clock.now()

    def _refill(self) -> None:
        now = self._clock.now()
        self._tokens = min(self._capacity, self._tokens + (now - self._last) * self._rate)
        self._last = now

    def consume(self) -> bool:
        self._refill()
        if self._tokens >= 1.0:
            self._tokens -= 1.0
            return True
        return False

    @property
    def tokens(self) -> float:
        self._refill()
        return self._tokens


# Full jitter (AWS Architecture Blog style): uniform in [0, computed cap].
def full_jitter(rng: random.Random) -> Callable[[float], float]:
    def apply(ceiling: float) -> float:
        return rng.uniform(0.0, ceiling)

    return apply


def no_jitter(ceiling: float) -> float:
    return ceiling


@dataclass(slots=True)
class RetryBudgetClient:
    """Wraps an ``httpx.Client``-shaped object with budgeted retries."""

    client: Any  # httpx.Client, or a stub with .request(method, url, **kw)
    budget: TokenBucketRetryBudget
    clock: Clock
    policy: RetryPolicy = field(default_factory=RetryPolicy)
    jitter: Callable[[float], float] = no_jitter
    on_event: Callable[[str, dict[str, Any]], None] | None = None

    def _emit(self, event: str, **fields: Any) -> None:
        if self.on_event is not None:
            self.on_event(event, fields)

    def backoff_ceiling(self, attempt: int) -> float:
        return min(self.policy.max_backoff, self.policy.base_backoff * (2**attempt))

    def request(self, method: str, url: str, **kwargs: Any) -> httpx.Response:
        deadline = self.clock.now() + self.policy.deadline_seconds
        attempt = 0
        while True:
            self._emit("attempt", attempt=attempt, url=url)
            response: httpx.Response | None
            last_error: httpx.TransportError | None = None
            try:
                response = self.client.request(method, url, **kwargs)
            except httpx.TransportError as exc:
                response = None
                last_error = exc
                retryable = True
            else:
                retryable = response.status_code in self.policy.retry_statuses
                if not retryable:
                    return response

            if attempt >= self.policy.max_retries:
                self._emit("retries_exhausted", attempts=attempt + 1, url=url)
                if response is not None:
                    return response  # caller sees the final 5xx
                raise last_error  # type: ignore[misc]

            if not self.budget.consume():
                self._emit("budget_exhausted", attempts=attempt + 1, url=url)
                raise RetryBudgetExhaustedError(
                    "retry budget exhausted; failing fast instead of amplifying"
                ) from last_error

            delay = self.jitter(self.backoff_ceiling(attempt))
            if self.clock.now() + delay > deadline:
                self._emit("deadline_exceeded", attempts=attempt + 1, url=url)
                raise RetryDeadlineExceededError(
                    f"next backoff of {delay:.3f}s would overshoot the deadline"
                ) from last_error

            self._emit("retry", attempt=attempt + 1, delay=delay, url=url)
            self.clock.sleep(delay)
            attempt += 1
