"""Listing 9 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Saga orchestrator for Northwind Robotics order fulfillment.

Flow: reserve inventory -> charge payment -> schedule shipment.
Each step declares a compensating action; on failure the orchestrator runs
compensations for completed steps in REVERSE order and reports the saga as
COMPENSATED (not "rolled back" -- the real world already happened; we
compensate, we do not time-travel).

Failure injection: each domain service takes ``fail_on`` -- a set of
operation names that raise on invocation.
"""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class SagaStatus(str, Enum):
    COMPLETED = "completed"
    COMPENSATED = "compensated"
    COMPENSATION_FAILED = "compensation_failed"


class CompensationError(RuntimeError):
    """A compensating action itself failed; requires operator attention."""


@dataclass(frozen=True, slots=True)
class SagaStep:
    name: str
    action: Callable[[dict[str, Any]], None]
    compensate: Callable[[dict[str, Any]], None] | None = None


@dataclass(frozen=True, slots=True)
class SagaResult:
    status: SagaStatus
    failed_step: str | None
    compensated: tuple[str, ...]
    context: dict[str, Any]


class SagaOrchestrator:
    """Executes steps in order; compensates in reverse on failure."""

    def __init__(
        self,
        steps: list[SagaStep],
        on_event: Callable[[str, dict[str, Any]], None] | None = None,
    ) -> None:
        if not steps:
            raise ValueError("a saga needs at least one step")
        self._steps = steps
        self._on_event = on_event

    def _emit(self, event: str, **fields: Any) -> None:
        if self._on_event is not None:
            self._on_event(event, fields)

    def run(self, context: dict[str, Any] | None = None) -> SagaResult:
        context = dict(context or {})
        completed: list[SagaStep] = []
        for step in self._steps:
            self._emit("step_started", step=step.name)
            try:
                step.action(context)
            except Exception as exc:
                self._emit("step_failed", step=step.name, error=type(exc).__name__)
                return self._compensate(completed, failed=step.name, context=context)
            completed.append(step)
            self._emit("step_completed", step=step.name)
        return SagaResult(
            status=SagaStatus.COMPLETED,
            failed_step=None,
            compensated=(),
            context=context,
        )

    def _compensate(
        self, completed: list[SagaStep], *, failed: str, context: dict[str, Any]
    ) -> SagaResult:
        compensated: list[str] = []
        try:
            for step in reversed(completed):
                if step.compensate is None:
                    continue
                self._emit("compensation_started", step=step.name)
                step.compensate(context)
                compensated.append(step.name)
                self._emit("compensation_completed", step=step.name)
        except Exception as exc:
            self._emit(
                "compensation_failed", step=step.name, error=type(exc).__name__
            )
            return SagaResult(
                status=SagaStatus.COMPENSATION_FAILED,
                failed_step=failed,
                compensated=tuple(compensated),
                context=context,
            )
        return SagaResult(
            status=SagaStatus.COMPENSATED,
            failed_step=failed,
            compensated=tuple(compensated),
            context=context,
        )


# --------------------------------------------------------------------------
# Northwind Robotics domain services (in-memory, deterministic)
# --------------------------------------------------------------------------
class InventoryService:
    def __init__(self, stock: dict[str, int], fail_on: set[str] | None = None) -> None:
        self.stock = dict(stock)
        self.reserved: dict[str, int] = {}
        self.fail_on = fail_on or set()
        self.calls: list[str] = []

    def reserve(self, sku: str, quantity: int) -> None:
        self.calls.append("reserve")
        if "reserve" in self.fail_on:
            raise ConnectionError("inventory service unavailable")
        if self.stock.get(sku, 0) < quantity:
            raise ValueError(f"insufficient stock for {sku}")
        self.stock[sku] -= quantity
        self.reserved[sku] = self.reserved.get(sku, 0) + quantity

    def release(self, sku: str, quantity: int) -> None:
        self.calls.append("release")
        if "release" in self.fail_on:
            raise ConnectionError("inventory service unavailable")
        self.reserved[sku] = self.reserved.get(sku, 0) - quantity
        self.stock[sku] = self.stock.get(sku, 0) + quantity


class PaymentService:
    def __init__(self, fail_on: set[str] | None = None) -> None:
        self.charges: list[tuple[str, float]] = []
        self.refunds: list[tuple[str, float]] = []
        self.fail_on = fail_on or set()
        self.calls: list[str] = []

    def charge(self, order_id: str, amount: float) -> None:
        self.calls.append("charge")
        if "charge" in self.fail_on:
            raise ConnectionError("payment gateway timeout")
        self.charges.append((order_id, amount))

    def refund(self, order_id: str, amount: float) -> None:
        self.calls.append("refund")
        if "refund" in self.fail_on:
            raise ConnectionError("payment gateway timeout")
        self.refunds.append((order_id, amount))


class ShipmentService:
    def __init__(self, fail_on: set[str] | None = None) -> None:
        self.shipments: list[str] = []
        self.cancellations: list[str] = []
        self.fail_on = fail_on or set()
        self.calls: list[str] = []

    def schedule(self, order_id: str) -> None:
        self.calls.append("schedule")
        if "schedule" in self.fail_on:
            raise ConnectionError("carrier API error")
        self.shipments.append(order_id)

    def cancel(self, order_id: str) -> None:
        self.calls.append("cancel")
        if "cancel" in self.fail_on:
            raise ConnectionError("carrier API error")
        self.cancellations.append(order_id)


def build_order_fulfillment_saga(
    inventory: InventoryService,
    payments: PaymentService,
    shipments: ShipmentService,
    on_event: Callable[[str, dict[str, Any]], None] | None = None,
) -> SagaOrchestrator:
    """The canonical three-step order saga with compensations."""
    steps = [
        SagaStep(
            name="reserve_inventory",
            action=lambda ctx: inventory.reserve(ctx["sku"], ctx["quantity"]),
            compensate=lambda ctx: inventory.release(ctx["sku"], ctx["quantity"]),
        ),
        SagaStep(
            name="charge_payment",
            action=lambda ctx: payments.charge(ctx["order_id"], ctx["amount"]),
            compensate=lambda ctx: payments.refund(ctx["order_id"], ctx["amount"]),
        ),
        SagaStep(
            name="schedule_shipment",
            action=lambda ctx: shipments.schedule(ctx["order_id"]),
            compensate=lambda ctx: shipments.cancel(ctx["order_id"]),
        ),
    ]
    return SagaOrchestrator(steps, on_event=on_event)
