"""Listing 10 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Failure-injection tests for the saga orchestrator."""
from __future__ import annotations

from saga import (
    InventoryService,
    PaymentService,
    SagaOrchestrator,
    SagaStatus,
    SagaStep,
    ShipmentService,
    build_order_fulfillment_saga,
)

ORDER = {"order_id": "ORD-7", "sku": "NR-1001", "quantity": 3, "amount": 184.50}


def build(fail_on: dict[str, set[str]] | None = None):
    fail_on = fail_on or {}
    inventory = InventoryService({"NR-1001": 10}, fail_on.get("inventory"))
    payments = PaymentService(fail_on.get("payments"))
    shipments = ShipmentService(fail_on.get("shipments"))
    events: list[tuple[str, dict]] = []
    saga = build_order_fulfillment_saga(
        inventory, payments, shipments,
        on_event=lambda event, fields: events.append((event, fields)),
    )
    return saga, inventory, payments, shipments, events


def test_happy_path_completes_all_steps_in_order() -> None:
    saga, inventory, payments, shipments, events = build()
    result = saga.run(ORDER)
    assert result.status is SagaStatus.COMPLETED
    assert result.failed_step is None
    assert result.compensated == ()
    assert inventory.stock["NR-1001"] == 7
    assert inventory.reserved["NR-1001"] == 3
    assert payments.charges == [("ORD-7", 184.50)]
    assert shipments.shipments == ["ORD-7"]
    started = [f["step"] for e, f in events if e == "step_started"]
    assert started == ["reserve_inventory", "charge_payment", "schedule_shipment"]


def test_payment_failure_compensates_inventory_in_reverse() -> None:
    saga, inventory, payments, shipments, _ = build(
        {"payments": {"charge"}}
    )
    result = saga.run(ORDER)
    assert result.status is SagaStatus.COMPENSATED
    assert result.failed_step == "charge_payment"
    assert result.compensated == ("reserve_inventory",)
    assert inventory.stock["NR-1001"] == 10   # reservation released
    assert inventory.reserved["NR-1001"] == 0
    assert payments.charges == []             # charge never landed
    assert shipments.shipments == []          # never reached


def test_shipment_failure_compensates_payment_then_inventory() -> None:
    saga, inventory, payments, shipments, _ = build(
        {"shipments": {"schedule"}}
    )
    result = saga.run(ORDER)
    assert result.status is SagaStatus.COMPENSATED
    assert result.failed_step == "schedule_shipment"
    # Reverse order of completion: refund BEFORE release.
    assert result.compensated == ("charge_payment", "reserve_inventory")
    assert payments.charges == [("ORD-7", 184.50)]   # happened, then refunded
    assert payments.refunds == [("ORD-7", 184.50)]
    assert inventory.stock["NR-1001"] == 10
    assert shipments.shipments == []


def test_first_step_failure_needs_no_compensation() -> None:
    saga, inventory, payments, shipments, _ = build(
        {"inventory": {"reserve"}}
    )
    result = saga.run(ORDER)
    assert result.status is SagaStatus.COMPENSATED
    assert result.failed_step == "reserve_inventory"
    assert result.compensated == ()
    assert payments.charges == []
    assert shipments.shipments == []


def test_compensation_failure_is_surfaced_not_swallowed() -> None:
    saga, inventory, payments, shipments, events = build(
        {"payments": {"charge", "refund"}}
    )
    # charge fails -> saga compensates reserve (refund is never reached
    # because charge never completed). To exercise a FAILING compensation,
    # fail schedule + refund.
    saga, inventory, payments, shipments, events = build(
        {"shipments": {"schedule"}, "payments": {"refund"}}
    )
    result = saga.run(ORDER)
    assert result.status is SagaStatus.COMPENSATION_FAILED
    assert result.failed_step == "schedule_shipment"
    # Refund failed, so inventory release never ran: partial compensation
    # is explicit in the result for an operator to reconcile.
    assert result.compensated == ()
    assert any(e == "compensation_failed" for e, _ in events)
    assert inventory.stock["NR-1001"] == 7  # still reserved: needs a human


def test_orchestrator_rejects_empty_step_list() -> None:
    import pytest

    with pytest.raises(ValueError):
        SagaOrchestrator([])


def test_saga_steps_without_compensation_are_skipped() -> None:
    log: list[str] = []

    def fail(_ctx) -> None:
        raise ConnectionError("down")

    saga = SagaOrchestrator(
        [
            SagaStep("fire_and_forget_email", lambda ctx: log.append("email")),
            SagaStep("charge", fail, compensate=lambda ctx: log.append("refund")),
        ]
    )
    result = saga.run({})
    assert result.status is SagaStatus.COMPENSATED
    assert result.compensated == ()  # email step has no compensation; charge never completed
    assert log == ["email"]
