"""Listing 7 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Transactional outbox: atomic domain-write + outbox-insert, a relay loop
with at-least-once delivery, and an idempotent consumer.

SQLite-backed, fully in-process. The "broker" is a Python callable, which
keeps the pattern's GUARANTEES visible: the relay marks an event published
only after the publish call returns, so a crash in between replays the
event -- and the consumer must deduplicate (Chapter 10 idempotency).
"""
from __future__ import annotations

import json
import sqlite3
import uuid
from dataclasses import dataclass
from typing import Any, Protocol

PRODUCER_SCHEMA = """
CREATE TABLE IF NOT EXISTS orders (
    order_id  TEXT PRIMARY KEY,
    sku       TEXT NOT NULL,
    quantity  INTEGER NOT NULL CHECK (quantity > 0),
    status    TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS outbox (
    seq          INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id     TEXT NOT NULL UNIQUE,
    aggregate_id TEXT NOT NULL,
    event_type   TEXT NOT NULL,
    payload      TEXT NOT NULL,
    published    INTEGER NOT NULL DEFAULT 0
);
"""

CONSUMER_SCHEMA = """
CREATE TABLE IF NOT EXISTS processed_events (
    event_id TEXT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS stock (
    sku      TEXT PRIMARY KEY,
    on_hand  INTEGER NOT NULL
);
"""


class Publisher(Protocol):
    """Anything that can accept one event. A real deployment: Kafka, etc."""

    def publish(self, event: dict[str, Any]) -> None: ...


class InProcessBroker:
    """Deterministic stand-in broker: records every published event."""

    def __init__(self) -> None:
        self.messages: list[dict[str, Any]] = []

    def publish(self, event: dict[str, Any]) -> None:
        self.messages.append(event)


class CrashAfterPublish:
    """Fault-injection publisher: delivers, THEN crashes before the relay
    can mark the event published -- the classic at-least-once window."""

    def __init__(self, inner: Publisher) -> None:
        self._inner = inner

    def publish(self, event: dict[str, Any]) -> None:
        self._inner.publish(event)
        raise RuntimeError("simulated relay crash after publish")


class OrderService:
    """Producer side: domain write and outbox insert in ONE transaction."""

    def __init__(self, conn: sqlite3.Connection) -> None:
        self._conn = conn
        self._conn.executescript(PRODUCER_SCHEMA)

    def place_order(
        self, order_id: str, sku: str, quantity: int, *, event_id: str | None = None
    ) -> str:
        event_id = event_id or uuid.uuid4().hex
        payload = json.dumps({"sku": sku, "quantity": quantity})
        with self._conn:  # atomic: both rows or neither
            self._conn.execute(
                "INSERT INTO orders (order_id, sku, quantity, status)"
                " VALUES (?, ?, ?, 'PLACED')",
                (order_id, sku, quantity),
            )
            self._conn.execute(
                "INSERT INTO outbox (event_id, aggregate_id, event_type, payload)"
                " VALUES (?, ?, 'order.placed', ?)",
                (event_id, order_id, payload),
            )
        return event_id

    def pending_events(self) -> list[dict[str, Any]]:
        rows = self._conn.execute(
            "SELECT event_id, aggregate_id, event_type, payload"
            " FROM outbox WHERE published = 0 ORDER BY seq"
        ).fetchall()
        return [
            {
                "event_id": row[0],
                "aggregate_id": row[1],
                "event_type": row[2],
                "payload": json.loads(row[3]),
            }
            for row in rows
        ]


@dataclass
class OutboxRelay:
    """Polls the outbox, publishes, marks published. At-least-once: the
    mark happens strictly AFTER publish returns."""

    conn: sqlite3.Connection
    publisher: Publisher
    batch_size: int = 100

    def relay_once(self) -> int:
        rows = self.conn.execute(
            "SELECT event_id, aggregate_id, event_type, payload"
            " FROM outbox WHERE published = 0 ORDER BY seq LIMIT ?",
            (self.batch_size,),
        ).fetchall()
        delivered = 0
        for event_id, aggregate_id, event_type, payload in rows:
            event = {
                "event_id": event_id,
                "aggregate_id": aggregate_id,
                "event_type": event_type,
                "payload": json.loads(payload),
            }
            self.publisher.publish(event)  # crash here -> replay later
            with self.conn:
                self.conn.execute(
                    "UPDATE outbox SET published = 1 WHERE event_id = ?",
                    (event_id,),
                )
            delivered += 1
        return delivered


class InventoryConsumer:
    """Idempotent consumer: effect applied at most once, tracked in the
    same transaction as the dedup record."""

    def __init__(self, conn: sqlite3.Connection) -> None:
        self._conn = conn
        self._conn.executescript(CONSUMER_SCHEMA)

    def seed_stock(self, sku: str, on_hand: int) -> None:
        with self._conn:
            self._conn.execute(
                "INSERT INTO stock (sku, on_hand) VALUES (?, ?)"
                " ON CONFLICT(sku) DO UPDATE SET on_hand = excluded.on_hand",
                (sku, on_hand),
            )

    def on_hand(self, sku: str) -> int:
        row = self._conn.execute(
            "SELECT on_hand FROM stock WHERE sku = ?", (sku,)
        ).fetchone()
        return row[0] if row else 0

    def handle(self, event: dict[str, Any]) -> bool:
        """Apply the event; return False for duplicates (already processed)."""
        if event["event_type"] != "order.placed":
            raise ValueError(f"unsupported event type {event['event_type']!r}")
        with self._conn:
            cursor = self._conn.execute(
                "INSERT OR IGNORE INTO processed_events (event_id) VALUES (?)",
                (event["event_id"],),
            )
            if cursor.rowcount == 0:
                return False  # duplicate delivery: deduped
            self._conn.execute(
                "UPDATE stock SET on_hand = on_hand - ? WHERE sku = ?",
                (event["payload"]["quantity"], event["payload"]["sku"]),
            )
            return True
