"""Listing 2 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Deterministic tests for the circuit breaker (injected manual clock)."""
from __future__ import annotations

import asyncio
import threading

import pytest

from circuit_breaker import (
    BreakerConfig,
    BreakerState,
    CircuitBreaker,
    CircuitOpenError,
)


class ManualClock:
    """Virtual clock: nothing happens unless the test advances it."""

    def __init__(self, start: float = 1_000.0) -> None:
        self._now = start

    def now(self) -> float:
        return self._now

    def advance(self, seconds: float) -> None:
        if seconds < 0:
            raise ValueError("time only moves forward")
        self._now += seconds


def make_breaker(**overrides) -> tuple[CircuitBreaker, ManualClock, list]:
    clock = ManualClock()
    events: list[tuple[str, dict]] = []
    config = BreakerConfig(
        failure_rate_threshold=overrides.get("failure_rate_threshold", 0.5),
        window_seconds=overrides.get("window_seconds", 10.0),
        minimum_calls=overrides.get("minimum_calls", 4),
        open_duration=overrides.get("open_duration", 5.0),
        half_open_max_probes=overrides.get("half_open_max_probes", 1),
        half_open_success_threshold=overrides.get("half_open_success_threshold", 1),
    )
    breaker = CircuitBreaker(
        "inventory",
        config,
        clock=clock,
        on_event=lambda event, fields: events.append((event, fields)),
    )
    return breaker, clock, events


def boom() -> None:
    raise ConnectionError("inventory unreachable")


def test_closed_breaker_passes_calls_through() -> None:
    breaker, _, _ = make_breaker()
    assert breaker.state is BreakerState.CLOSED
    assert breaker.call(lambda: 42) == 42


def test_opens_when_failure_rate_threshold_is_reached() -> None:
    breaker, _, events = make_breaker()
    # 4 calls, 2 failures -> exactly 0.5 failure rate at minimum_calls.
    breaker.call(lambda: "ok")
    with pytest.raises(ConnectionError):
        breaker.call(boom)
    with pytest.raises(ConnectionError):
        breaker.call(boom)
    assert breaker.state is BreakerState.CLOSED  # 2/3 < window minimum
    breaker.call(lambda: "ok")
    assert breaker.state is BreakerState.OPEN  # 2/4 = 0.5 -> open
    assert any(e == "state_change" and f["current"] == "open" for e, f in events)


def test_open_breaker_rejects_without_calling_the_dependency() -> None:
    breaker, _, _ = make_breaker()
    for _ in range(2):
        breaker.call(lambda: "ok")
        with pytest.raises(ConnectionError):
            breaker.call(boom)
    assert breaker.state is BreakerState.OPEN
    calls = 0

    def counted() -> int:
        nonlocal calls
        calls += 1
        return calls

    for _ in range(10):
        with pytest.raises(CircuitOpenError):
            breaker.call(counted)
    assert calls == 0  # fail-fast: the dependency was never touched


def test_half_open_probe_success_closes_breaker() -> None:
    breaker, clock, _ = make_breaker()
    for _ in range(2):
        with pytest.raises(ConnectionError):
            breaker.call(boom)
        with pytest.raises(ConnectionError):
            breaker.call(boom)
    assert breaker.state is BreakerState.OPEN
    clock.advance(4.9)
    with pytest.raises(CircuitOpenError):
        breaker.call(lambda: "too early")
    clock.advance(0.2)  # now past open_duration
    assert breaker.state is BreakerState.HALF_OPEN
    assert breaker.call(lambda: "recovered") == "recovered"
    assert breaker.state is BreakerState.CLOSED


def test_half_open_probe_failure_reopens() -> None:
    breaker, clock, _ = make_breaker(minimum_calls=2, failure_rate_threshold=1.0)
    for _ in range(2):
        with pytest.raises(ConnectionError):
            breaker.call(boom)
    assert breaker.state is BreakerState.OPEN
    clock.advance(5.0)
    with pytest.raises(ConnectionError):
        breaker.call(boom)  # probe fails
    assert breaker.state is BreakerState.OPEN
    # Reopened: the full open_duration restarts from now.
    clock.advance(4.9)
    with pytest.raises(CircuitOpenError):
        breaker.call(lambda: "still closed to traffic")


def test_half_open_admits_only_one_concurrent_probe() -> None:
    breaker, clock, _ = make_breaker(minimum_calls=2, failure_rate_threshold=1.0)
    for _ in range(2):
        with pytest.raises(ConnectionError):
            breaker.call(boom)
    clock.advance(5.0)

    release = threading.Event()
    probe_started = threading.Event()

    def slow_probe() -> str:
        probe_started.set()
        assert release.wait(timeout=5.0)
        return "healed"

    result: list[str] = []
    worker = threading.Thread(
        target=lambda: result.append(breaker.call(slow_probe)), daemon=True
    )
    worker.start()
    assert probe_started.wait(timeout=5.0)  # probe is in flight
    with pytest.raises(CircuitOpenError):
        breaker.call(lambda: "second probe")  # probe limit = 1
    release.set()
    worker.join(timeout=5.0)
    assert result == ["healed"]
    assert breaker.state is BreakerState.CLOSED


def test_rolling_window_ages_out_old_failures() -> None:
    breaker, clock, _ = make_breaker(window_seconds=10.0, minimum_calls=4)
    # Two failures, then the window slides past them.
    for _ in range(2):
        with pytest.raises(ConnectionError):
            breaker.call(boom)
    clock.advance(11.0)
    breaker.call(lambda: "ok")
    breaker.call(lambda: "ok")
    breaker.call(lambda: "ok")
    breaker.call(lambda: "ok")
    assert breaker.state is BreakerState.CLOSED  # failures evicted: 0/4 rate


def test_caller_fault_exceptions_count_as_successes() -> None:
    clock = ManualClock()
    breaker = CircuitBreaker(
        "catalog",
        BreakerConfig(minimum_calls=2, failure_rate_threshold=0.5),
        clock=clock,
        is_failure=lambda exc: isinstance(exc, ConnectionError),
    )
    for _ in range(5):
        with pytest.raises(ValueError):
            breaker.call(lambda: (_ for _ in ()).throw(ValueError("bad input")))
    assert breaker.state is BreakerState.CLOSED


def test_metrics_hook_receives_events_in_order() -> None:
    breaker, _, events = make_breaker(minimum_calls=2, failure_rate_threshold=1.0)
    with pytest.raises(ConnectionError):
        breaker.call(boom)
    with pytest.raises(ConnectionError):
        breaker.call(boom)
    with pytest.raises(CircuitOpenError):
        breaker.call(lambda: "rejected")
    names = [name for name, _ in events]
    assert names == ["call_failure", "call_failure", "state_change", "rejected"]


def test_async_path_uses_the_same_state_machine() -> None:
    clock = ManualClock()

    async def main() -> None:
        breaker = CircuitBreaker(
            "warehouse",
            BreakerConfig(minimum_calls=2, failure_rate_threshold=1.0),
            clock=clock,
        )

        async def ok() -> str:
            return "fine"

        async def bad() -> str:
            raise ConnectionError("down")

        with pytest.raises(ConnectionError):
            await breaker.acall(bad)
        with pytest.raises(ConnectionError):
            await breaker.acall(bad)
        assert breaker.state is BreakerState.OPEN
        with pytest.raises(CircuitOpenError):
            await breaker.acall(ok)
        clock.advance(5.0)
        assert await breaker.acall(ok) == "fine"
        assert breaker.state is BreakerState.CLOSED

    asyncio.run(main())
