"""Listing 8 extracted from chapters/chapter_15_microservices_resilience.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Tests for the transactional outbox, relay crash, and consumer dedup."""
from __future__ import annotations

import sqlite3

import pytest

from outbox import (
    CrashAfterPublish,
    InProcessBroker,
    InventoryConsumer,
    OrderService,
    OutboxRelay,
)


@pytest.fixture()
def producer_conn() -> sqlite3.Connection:
    return sqlite3.connect(":memory:")


@pytest.fixture()
def consumer() -> InventoryConsumer:
    consumer = InventoryConsumer(sqlite3.connect(":memory:"))
    consumer.seed_stock("NR-1001", 100)
    return consumer


def test_domain_write_and_outbox_insert_are_atomic(producer_conn) -> None:
    service = OrderService(producer_conn)
    service.place_order("ORD-1", "NR-1001", 3, event_id="evt-1")
    # Second insert with the same order_id violates the PK; the outbox row
    # from the failed transaction must be rolled back too.
    with pytest.raises(sqlite3.IntegrityError):
        service.place_order("ORD-1", "NR-1001", 5, event_id="evt-2")
    pending = service.pending_events()
    assert [e["event_id"] for e in pending] == ["evt-1"]


def test_relay_delivers_pending_events_and_marks_them(producer_conn) -> None:
    service = OrderService(producer_conn)
    service.place_order("ORD-1", "NR-1001", 3, event_id="evt-1")
    service.place_order("ORD-2", "NR-2002", 1, event_id="evt-2")
    broker = InProcessBroker()
    relay = OutboxRelay(producer_conn, broker)
    assert relay.relay_once() == 2
    assert [m["event_id"] for m in broker.messages] == ["evt-1", "evt-2"]
    assert relay.relay_once() == 0  # nothing left pending


def test_relay_crash_mid_publish_replays_event(producer_conn) -> None:
    service = OrderService(producer_conn)
    service.place_order("ORD-1", "NR-1001", 3, event_id="evt-1")
    broker = InProcessBroker()

    crashing = OutboxRelay(producer_conn, CrashAfterPublish(broker))
    with pytest.raises(RuntimeError, match="simulated relay crash"):
        crashing.relay_once()
    assert len(broker.messages) == 1       # delivered...
    assert len(service.pending_events()) == 1  # ...but NOT marked published

    recovered = OutboxRelay(producer_conn, broker)
    assert recovered.relay_once() == 1     # at-least-once: replayed
    assert len(broker.messages) == 2       # duplicate on the wire
    assert len(service.pending_events()) == 0


def test_idempotent_consumer_dedups_replayed_events(consumer) -> None:
    event = {
        "event_id": "evt-1",
        "aggregate_id": "ORD-1",
        "event_type": "order.placed",
        "payload": {"sku": "NR-1001", "quantity": 3},
    }
    assert consumer.handle(event) is True
    assert consumer.on_hand("NR-1001") == 97
    assert consumer.handle(event) is False  # duplicate: no double decrement
    assert consumer.handle(event) is False
    assert consumer.on_hand("NR-1001") == 97


def test_end_to_end_order_to_stock_under_crash_and_replay(
    producer_conn, consumer
) -> None:
    service = OrderService(producer_conn)
    service.place_order("ORD-1", "NR-1001", 3, event_id="evt-1")
    service.place_order("ORD-2", "NR-1001", 2, event_id="evt-2")
    broker = InProcessBroker()

    crashing = OutboxRelay(producer_conn, CrashAfterPublish(broker))
    with pytest.raises(RuntimeError):
        crashing.relay_once()  # evt-1 delivered, crash before mark

    OutboxRelay(producer_conn, broker).relay_once()  # replays evt-1, adds evt-2
    assert [m["event_id"] for m in broker.messages] == ["evt-1", "evt-1", "evt-2"]

    applied = [consumer.handle(m) for m in broker.messages]
    assert applied == [True, False, True]
    assert consumer.on_hand("NR-1001") == 95  # 3 + 2 deducted exactly once
