"""Listing 4 extracted from chapters/chapter_04_serialization_contracts.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""bench_serializers.py -- JSON vs hand-rolled Protobuf vs MessagePack.

Deterministic fixtures (seeded), fixed iteration counts, illustrative timing.
MessagePack is optional: if msgpack is not installed, its column is skipped.
Run:  python bench_serializers.py
"""
from __future__ import annotations

import json
import random
import time
from dataclasses import dataclass
from typing import Any, Callable

from mini_protobuf import Part  # the hand-rolled codec from Listing 1

try:
    import msgpack  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover - optional dependency
    msgpack = None  # type: ignore[assignment]

ITERATIONS = 5_000


def build_fixtures(seed: int = 42) -> dict[str, dict[str, Any]]:
    rng = random.Random(seed)
    small = {"part_id": "NR-1001", "name": "Servo Motor 42mm",
             "qty": 120, "unit_price_usd": 18.75, "status": "active"}
    nested = {
        "order_id": "9007199254740991",  # string on purpose: see 2^53 rule
        "customer": {"id": "C-88213", "region": "MX-NLE"},
        "lines": [{"part_id": f"NR-{1000 + i}", "qty": rng.randint(1, 50),
                   "unit_price_usd": round(rng.uniform(1, 200), 2)}
                  for i in range(12)],
    }
    wide = {f"metric_{i:02d}": round(rng.uniform(0, 1000), 4) for i in range(64)}
    return {"small_record": small, "nested_order": nested, "wide_flat": wide}


@dataclass(frozen=True)
class Codec:
    name: str
    encode: Callable[[dict[str, Any]], bytes]
    decode: Callable[[bytes], Any]


def _json_codecs() -> Codec:
    return Codec("json",
                 lambda d: json.dumps(d, separators=(",", ":")).encode("utf-8"),
                 lambda b: json.loads(b.decode("utf-8")))


def _msgpack_codecs() -> Codec | None:
    if msgpack is None:
        return None
    return Codec("msgpack",
                 lambda d: msgpack.packb(d, use_bin_type=True),
                 lambda b: msgpack.unpackb(b, raw=False))


def _proto_small_codec() -> Codec:
    """Protobuf comparison for the small-record shape (Part fields only)."""
    def enc(d: dict[str, Any]) -> bytes:
        return Part(part_id=d["part_id"], qty=d["qty"],
                    unit_kg=d["unit_price_usd"]).encode()

    def dec(b: bytes) -> Part:
        return Part.decode(b)
    return Codec("mini-protobuf", enc, dec)


def timed(fn: Callable[[], Any], iterations: int = ITERATIONS) -> float:
    """Median-ish wall time per call in microseconds (illustrative only)."""
    start = time.perf_counter()
    for _ in range(iterations):
        fn()
    return (time.perf_counter() - start) * 1e6 / iterations


def main() -> None:
    fixtures = build_fixtures()
    generic = [c for c in (_json_codecs(), _msgpack_codecs()) if c]
    header = f"{'shape':<14}{'codec':<15}{'bytes':>8}{'enc us':>10}{'dec us':>10}"
    print(header)
    print("-" * len(header))
    for shape, doc in fixtures.items():
        codecs = list(generic)
        if shape == "small_record":
            codecs.append(_proto_small_codec())
        for codec in codecs:
            wire = codec.encode(doc)
            assert codec.decode(wire) is not None
            enc_us = timed(lambda: codec.encode(doc))
            dec_us = timed(lambda: codec.decode(wire))
            print(f"{shape:<14}{codec.name:<15}{len(wire):>8}"
                  f"{enc_us:>10.2f}{dec_us:>10.2f}")


if __name__ == "__main__":
    main()
