"""Listing 5 extracted from chapters/chapter_04_serialization_contracts.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""ndjson_stream.py -- streaming JSON Lines writer/reader (stdlib only)."""
from __future__ import annotations

import io
import json
import logging
from typing import Any, Iterator, TextIO

logger = logging.getLogger("northwind.ndjson")


def write_ndjson(records: Iterator[dict[str, Any]], sink: TextIO) -> int:
    """Write records as NDJSON; returns the number of lines written."""
    count = 0
    for record in records:
        line = json.dumps(record, separators=(",", ":"), ensure_ascii=False)
        if "\n" in line:  # json.dumps never emits raw newlines; guard anyway
            raise ValueError("record would break line framing")
        sink.write(line + "\n")
        count += 1
    sink.flush()
    return count


def read_ndjson(source: TextIO, max_line_bytes: int = 1_000_000) -> Iterator[Any]:
    """Yield one decoded value per line. Bounded lines; bad lines are skipped.

    Backpressure: this is a generator -- if the consumer is slow, no records
    are pulled from `source`, so memory stays O(1) in the number of records.
    """
    for lineno, raw in enumerate(source, start=1):
        if len(raw) > max_line_bytes:
            logger.error("line %d exceeds %d bytes; skipping",
                         lineno, max_line_bytes)
            continue
        line = raw.strip()
        if not line:
            continue
        try:
            yield json.loads(line)
        except json.JSONDecodeError as exc:
            logger.error("line %d is not valid JSON (%s); skipping",
                         lineno, exc.msg)


def _demo() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    records = (
        {"part_id": f"NR-{1000 + i}", "qty": i * 7, "status": "active"}
        for i in range(1, 4)
    )
    buffer = io.StringIO()  # stands in for a socket or a log file
    written = write_ndjson(records, buffer)
    # Simulate one poisoned record appended after the clean batch:
    buffer.write('{"part_id": "BROKEN", "qty": ')
    buffer.seek(0)
    decoded = list(read_ndjson(buffer))
    assert written == 3
    assert [r["part_id"] for r in decoded] == ["NR-1001", "NR-1002", "NR-1003"]
    assert sum(r["qty"] for r in decoded) == 7 + 14 + 21
    print(f"Wrote {written} lines; recovered {len(decoded)} of "
          f"{written + 1} (1 poisoned line skipped).")


if __name__ == "__main__":
    _demo()
