"""Listing 3 extracted from chapters/chapter_04_serialization_contracts.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""negotiation.py -- RFC 9110 proactive content negotiation, pure stdlib."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MediaRange:
    type: str
    subtype: str
    q: float = 1.0

    def specificity(self) -> int:
        """exact(2) > type/* (1) > */* (0); drives tie-breaking."""
        if self.type == "*":
            return 0
        if self.subtype == "*":
            return 1
        return 2

    def matches(self, media_type: str) -> bool:
        t, _, s = media_type.partition("/")
        return (self.type in ("*", t)) and (self.subtype in ("*", s))


def parse_accept(header: str | None) -> list[MediaRange]:
    """Parse an Accept header; absent or blank means '*/*' at q=1.0."""
    if not header or not header.strip():
        return [MediaRange("*", "*")]
    ranges: list[MediaRange] = []
    for raw in header.split(","):
        parts = [p.strip() for p in raw.split(";")]
        type_, _, subtype = parts[0].partition("/")
        if not subtype:
            continue  # malformed entry: skip, do not crash on client junk
        q = 1.0
        for param in parts[1:]:
            key, _, value = param.partition("=")
            if key.strip().lower() == "q":
                try:
                    q = float(value)
                except ValueError:
                    q = 0.0  # a non-numeric q is treated as 'refuse'
        q = min(max(q, 0.0), 1.0)
        ranges.append(MediaRange(type_.strip().lower(),
                                 subtype.strip().lower(), q))
    return ranges or [MediaRange("*", "*")]


def select_representation(
    accept_header: str | None, available: list[str]
) -> str | None:
    """Return the best available media type, or None (-> HTTP 406).

    Score = q of the MOST SPECIFIC matching range; ties break toward
    the server's own preference (the order of `available`).
    """
    if not available:
        raise ValueError("available must contain at least one media type")
    ranges = parse_accept(accept_header)
    scored: list[tuple[float, int, int, str]] = []
    for server_rank, media_type in enumerate(available):
        matches = [r for r in ranges if r.matches(media_type)]
        if not matches:
            scored.append((0.0, 0, -server_rank, media_type))
            continue
        best = max(matches, key=lambda r: (r.specificity(), r.q))
        scored.append((best.q, best.specificity(), -server_rank, media_type))
    scored.sort(reverse=True)
    top_q, _, _, winner = scored[0]
    return winner if top_q > 0.0 else None


def _demo() -> None:
    header = ("application/vnd.northwind.parts+json;v=2, "
              "application/json;q=0.9, text/html;q=0.8, */*;q=0.1")
    server = ["application/json", "text/html"]
    assert select_representation(header, server) == "application/json"
    assert select_representation("text/html", server) == "text/html"
    # q=0 on everything the server can do -> 406 (None)
    assert select_representation("image/png, application/json;q=0",
                                 server) is None
    # No Accept header -> server default (first listed)
    assert select_representation(None, server) == "application/json"
    # Specificity trap: JSON is scored by the MORE SPECIFIC application/*
    # range (q=0.4), not by the */* range (q=0.9) -> HTML wins at 0.9.
    assert select_representation("application/*;q=0.4, */*;q=0.9",
                                 server) == "text/html"
    print("All negotiation selector checks passed.")


if __name__ == "__main__":
    _demo()
