"""Listing 2 extracted from chapters/chapter_04_serialization_contracts.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""validate_parts.py -- JSON Schema 2020-12 validation -> RFC 9457 errors.

Requires: jsonschema>=4.21 (see Python Dependencies Appendix).
Offline: the schema is an embedded fixture; no registry, no network.
"""
from __future__ import annotations

import json
import logging
from typing import Any

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError

logger = logging.getLogger("northwind.validation")

PART_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://schemas.northwind-robotics.example/parts/v2/part.json",
    "title": "Northwind Robotics Part",
    "type": "object",
    "properties": {
        "part_id": {
            "type": "string",
            "pattern": "^NR-[0-9]{4}$",
            "description": "Catalog identifier; string to avoid the 2^53 trap.",
        },
        "name": {"type": "string", "minLength": 1, "maxLength": 120},
        "qty": {"type": "integer", "minimum": 0},
        "unit_price_usd": {"type": "number", "exclusiveMinimum": 0},
        "status": {"enum": ["active", "deprecated", "eol"]},
        "firmware": {"type": "string"},
    },
    "required": ["part_id", "name", "qty", "status"],
    "additionalProperties": False,
}


def build_validator(schema: dict[str, Any]) -> Draft202012Validator:
    """Compile the schema once; fail fast if the schema itself is invalid."""
    try:
        Draft202012Validator.check_schema(schema)
    except SchemaError as exc:
        raise ValueError(f"schema is not valid 2020-12: {exc.message}") from exc
    return Draft202012Validator(schema)


def to_problem_details(
    validator: Draft202012Validator, instance: Any
) -> dict[str, Any] | None:
    """Return None if valid, else an RFC 9457 problem document (status 422)."""
    errors = sorted(validator.iter_errors(instance), key=lambda e: list(e.path))
    if not errors:
        return None
    return {
        "type": "https://problems.northwind-robotics.example/schema-validation",
        "title": "Payload does not conform to the Part schema",
        "status": 422,
        "detail": f"{len(errors)} schema violation(s) found.",
        "instance": "/v2/parts",
        "errors": [
            {
                "pointer": "/" + "/".join(str(p) for p in e.absolute_path),
                "keyword": e.validator,
                "message": e.message,
            }
            for e in errors
        ],
    }


def _demo() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    validator = build_validator(PART_SCHEMA)

    good = {
        "part_id": "NR-1001", "name": "Servo Motor 42mm",
        "qty": 120, "unit_price_usd": 18.75, "status": "active",
    }
    bad = {
        "part_id": "servo-1",          # violates pattern
        "name": "",                    # violates minLength
        "qty": -4,                     # violates minimum
        "status": "retired",           # not in enum
        "debug_note": "leftover",      # additionalProperties: false
    }
    assert to_problem_details(validator, good) is None
    problem = to_problem_details(validator, bad)
    assert problem is not None and problem["status"] == 422
    body = json.dumps(problem, indent=2)
    logger.info("responding 422 with application/problem+json")
    print(body)
    assert len(problem["errors"]) == 5  # one per violation, all collected


if __name__ == "__main__":
    _demo()
