"""Listing 1 extracted from chapters/chapter_04_serialization_contracts.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""mini_protobuf.py -- a hand-rolled Protocol Buffers wire-format codec.

Implements (proto3 semantics) for a single message:
    message Part {
      string part_id  = 1;  // LEN     wire type 2
      uint32 qty      = 2;  // VARINT  wire type 0
      sint32 delta    = 3;  // VARINT  wire type 0 (zigzag)
      double unit_kg  = 4;  // I64     wire type 1
      float  width_mm = 5;  // I32     wire type 5
    }
Pure standard library; offline; deterministic. Python 3.11+.
"""
from __future__ import annotations

import struct
from dataclasses import dataclass

WIRE_VARINT = 0
WIRE_I64 = 1
WIRE_LEN = 2
WIRE_I32 = 5
_MAX_VARINT_BYTES = 10  # a 64-bit varint never exceeds 10 bytes


class DecodeError(ValueError):
    """Raised when a byte stream is not a valid Part encoding."""


def encode_varint(value: int) -> bytes:
    """Encode an unsigned 64-bit integer as a varint (7 bits/byte, LSB first)."""
    if not 0 <= value < 1 << 64:
        raise ValueError(f"varint out of uint64 range: {value}")
    out = bytearray()
    while True:
        bits = value & 0x7F
        value >>= 7
        out.append(bits | 0x80 if value else bits)  # MSB set => more bytes
        if not value:
            return bytes(out)


def decode_varint(buf: bytes, pos: int) -> tuple[int, int]:
    """Decode a varint at buf[pos:]; return (value, next_pos)."""
    result, shift = 0, 0
    for i in range(_MAX_VARINT_BYTES):
        if pos + i >= len(buf):
            raise DecodeError("truncated varint")
        byte = buf[pos + i]
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:  # continuation bit clear => final byte
            return result, pos + i + 1
        shift += 7
    raise DecodeError("varint exceeds 64 bits")


def zigzag_encode(n: int) -> int:
    """Map signed n to unsigned so small magnitudes stay short."""
    return (n << 1) ^ (n >> 63)


def zigzag_decode(u: int) -> int:
    return (u >> 1) ^ -(u & 1)


def make_tag(field_number: int, wire_type: int) -> bytes:
    if not 1 <= field_number < 1 << 29:
        raise ValueError(f"field number out of range: {field_number}")
    return encode_varint((field_number << 3) | wire_type)


@dataclass(frozen=True)
class Part:
    part_id: str = ""
    qty: int = 0
    delta: int = 0
    unit_kg: float = 0.0
    width_mm: float = 0.0

    def encode(self) -> bytes:
        """Serialize; proto3 rule: default-valued scalar fields are omitted."""
        out = bytearray()
        if self.part_id:
            raw = self.part_id.encode("utf-8")
            out += make_tag(1, WIRE_LEN) + encode_varint(len(raw)) + raw
        if self.qty:
            out += make_tag(2, WIRE_VARINT) + encode_varint(self.qty)
        if self.delta:
            out += make_tag(3, WIRE_VARINT) + encode_varint(zigzag_encode(self.delta))
        if self.unit_kg != 0.0:
            out += make_tag(4, WIRE_I64) + struct.pack("<d", self.unit_kg)
        if self.width_mm != 0.0:
            out += make_tag(5, WIRE_I32) + struct.pack("<f", self.width_mm)
        return bytes(out)

    @classmethod
    def decode(cls, buf: bytes) -> "Part":
        """Parse wire bytes. Unknown fields are skipped (forward compat)."""
        part_id, qty, delta, unit_kg, width_mm = "", 0, 0, 0.0, 0.0
        pos = 0
        while pos < len(buf):
            tag, pos = decode_varint(buf, pos)
            field_number, wire_type = tag >> 3, tag & 0b111
            if wire_type == WIRE_VARINT:
                value, pos = decode_varint(buf, pos)
                if field_number == 2:
                    qty = value
                elif field_number == 3:
                    delta = zigzag_decode(value)
            elif wire_type == WIRE_LEN:
                length, pos = decode_varint(buf, pos)
                if pos + length > len(buf):
                    raise DecodeError("LEN field overruns buffer")
                payload = buf[pos:pos + length]
                pos += length
                if field_number == 1:
                    part_id = payload.decode("utf-8")
            elif wire_type == WIRE_I64:
                (value,) = struct.unpack_from("<d", buf, pos)
                pos += 8
                if field_number == 4:
                    unit_kg = value
            elif wire_type == WIRE_I32:
                (value,) = struct.unpack_from("<f", buf, pos)
                pos += 4
                if field_number == 5:
                    width_mm = value
            else:
                raise DecodeError(f"unsupported wire type {wire_type}")
        return cls(part_id=part_id, qty=qty, delta=delta,
                   unit_kg=unit_kg, width_mm=width_mm)


def _demo() -> None:
    part = Part(part_id="A1", qty=300, delta=-3, unit_kg=1.5, width_mm=42.0)
    wire = part.encode()
    print(f"Encoded {len(wire)} bytes:")
    for i, byte in enumerate(wire):
        print(f"  offset {i:2d}: 0x{byte:02X}  0b{byte:08b}")
    roundtrip = Part.decode(wire)
    assert roundtrip == part, "round-trip mismatch"
    # The varint for qty=300 must be exactly the textbook pair 0xAC 0x02:
    assert wire[5:7] == bytes([0xAC, 0x02])
    # zigzag(-3) == 5 must occupy a single byte after the field-3 tag:
    assert wire[7] == 0x18 and wire[8] == 0x05
    # Unknown-field tolerance: append field 99 (VARINT) and re-decode.
    tolerant = Part.decode(wire + make_tag(99, WIRE_VARINT) + encode_varint(7))
    assert tolerant == part
    print("Round-trip OK; varint, zigzag, and unknown-field checks passed.")


if __name__ == "__main__":
    _demo()
