"""Listing 2 extracted from chapters/chapter_01_http_wire_protocol.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Chunked transfer encoding + keep-alive demo over raw sockets.

The server streams a body as three chunks, then serves a second request
on the SAME connection (keep-alive). The client parses chunks by hand.
Offline, deterministic, stdlib only (Python 3.11+).
"""
from __future__ import annotations

import socket
import socketserver
import threading

HOST = "127.0.0.1"
MAX_CHUNK = 1 << 20  # 1 MiB sanity bound against hostile size lines


def recv_until(sock: socket.socket, marker: bytes,
               limit: int = 65536) -> tuple[bytes, bytes]:
    """Read until marker (inclusive); return (head, leftover bytes).

    Keeping the leftover is essential: a single recv() may return header
    and body bytes together, and discarding the tail desyncs framing.
    """
    buf = b""
    while marker not in buf:
        chunk = sock.recv(4096)
        if not chunk:
            raise ConnectionError("EOF before marker")
        buf += chunk
        if len(buf) > limit:
            raise ValueError("header section exceeds limit")
    head, _, rest = buf.partition(marker)
    return head + marker, rest


def read_chunked_body(sock: socket.socket, buffered: bytes) -> bytes:
    """Parse a chunked body. `buffered` holds bytes already read past
    the header terminator (may be empty). Returns decoded body."""
    body = bytearray()
    pending = bytearray(buffered)

    def read_line() -> bytes:
        while b"\r\n" not in pending:
            data = sock.recv(4096)
            if not data:
                raise ConnectionError("EOF inside chunked body")
            pending.extend(data)
        line, _, rest = bytes(pending).partition(b"\r\n")
        pending.clear()
        pending.extend(rest)
        return line

    while True:
        size = int(read_line().split(b";")[0], 16)  # ignore extensions
        if size > MAX_CHUNK:
            raise ValueError(f"chunk size {size} exceeds bound")
        if size == 0:
            while read_line() != b"":  # consume trailers
                pass
            return bytes(body)
        while len(pending) < size + 2:  # data + trailing CRLF
            data = sock.recv(4096)
            if not data:
                raise ConnectionError("EOF inside chunk data")
            pending.extend(data)
        body.extend(pending[:size])
        if pending[size : size + 2] != b"\r\n":
            raise ValueError("chunk missing trailing CRLF")
        del pending[: size + 2]


class ChunkedHandler(socketserver.BaseRequestHandler):
    def handle(self) -> None:
        sock: socket.socket = self.request
        sock.settimeout(5.0)
        for _ in range(2):  # serve two requests on one connection
            head, _ = recv_until(sock, b"\r\n\r\n")  # requests are head-only
            request_line = head.split(b"\r\n", 1)[0].decode("ascii")
            keep_alive = b"connection: close" not in head.lower()
            if request_line.startswith("GET /stream "):
                parts = [b"Weld-", b"Bot ", b"#42 online"]
                payload = b"".join(
                    b"%X\r\n%s\r\n" % (len(p), p) for p in parts
                ) + b"0\r\n\r\n"
                sock.sendall(
                    b"HTTP/1.1 200 OK\r\n"
                    b"Content-Type: text/plain\r\n"
                    b"Transfer-Encoding: chunked\r\n\r\n" + payload
                )
            else:
                body = b"pong"
                sock.sendall(
                    b"HTTP/1.1 200 OK\r\nContent-Length: 4\r\n\r\n" + body
                )
            if not keep_alive:
                break


def main() -> None:
    server = socketserver.ThreadingTCPServer((HOST, 0), ChunkedHandler)
    server.daemon_threads = True
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        port = server.server_address[1]
        with socket.create_connection((HOST, port), timeout=5.0) as sock:
            sock.sendall(
                b"GET /stream HTTP/1.1\r\nHost: localhost\r\n\r\n"
            )
            head, buffered = recv_until(sock, b"\r\n\r\n")
            print("=== RESPONSE HEAD (request 1) ===")
            print(head.decode("ascii"), end="")
            body = read_chunked_body(sock, buffered)
            print("=== DECODED CHUNKED BODY ===")
            print(repr(body))
            # Second request on the SAME socket: keep-alive in action.
            sock.sendall(
                b"GET /ping HTTP/1.1\r\nHost: localhost\r\n"
                b"Connection: close\r\n\r\n"
            )
            # Server closes after this response: read until EOF.
            reply2 = b""
            while True:
                chunk = sock.recv(4096)
                if not chunk:
                    break
                reply2 += chunk
            print("=== RESPONSE (request 2, same connection) ===")
            print(reply2.decode("ascii"))
        assert body == b"Weld-Bot #42 online"
        assert b"pong" in reply2
        print("=== OK: chunked decode + keep-alive reuse verified ===")
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5.0)


if __name__ == "__main__":
    main()
