"""Listing 1 extracted from chapters/chapter_01_http_wire_protocol.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Raw-socket HTTP/1.1 client against a local stdlib server.

Prints the exact bytes sent and received, with CRLF framing rendered
visibly. Offline, deterministic, stdlib only (Python 3.11+).
"""
from __future__ import annotations

import socket
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HOST = "127.0.0.1"
BODY = b'{"id":42,"name":"Weld-Bot"}'


def visible(data: bytes) -> str:
    """Render bytes with escapes so CRLF framing is visible."""
    return "".join(
        {0x0D: r"\r", 0x0A: r"\n"}.get(b) or (chr(b) if 32 <= b < 127 else rf"\x{b:02x}")
        for b in data
    )


class RobotHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"  # enable keep-alive responses

    def do_GET(self) -> None:  # noqa: N802 (stdlib naming)
        if self.path != "/robots/42":
            self.send_error(404, "Not Found")
            return
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(BODY)))
        self.end_headers()
        self.wfile.write(BODY)

    def log_message(self, fmt: str, *args: object) -> None:
        pass  # keep stdout deterministic


def raw_get(host: str, port: int, path: str) -> tuple[bytes, bytes]:
    request = (
        f"GET {path} HTTP/1.1\r\n"
        f"Host: {host}:{port}\r\n"
        "Accept: application/json\r\n"
        "Connection: close\r\n"  # close => read-until-EOF is unambiguous
        "\r\n"
    ).encode("ascii")
    with socket.create_connection((host, port), timeout=5.0) as sock:
        sock.sendall(request)
        chunks: list[bytes] = []
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            chunks.append(chunk)
    return request, b"".join(chunks)


def main() -> None:
    server = ThreadingHTTPServer((HOST, 0), RobotHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        port = server.server_address[1]
        sent, received = raw_get(HOST, port, "/robots/42")
        print("=== BYTES SENT ===")
        print(visible(sent))
        print("=== BYTES RECEIVED ===")
        print(visible(received))
        assert b"HTTP/1.1 200 OK\r\n" in received
        assert received.endswith(BODY)
        print("=== OK: status line and body verified ===")
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5.0)


if __name__ == "__main__":
    main()
