"""Listing 4 extracted from chapters/chapter_01_http_wire_protocol.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""HTTP/2 frame parser: decode a captured byte stream, stdlib only.

The fixture is constructed in-script (client preface + SETTINGS,
SETTINGS-ACK, HEADERS, DATA) so results are deterministic and offline.
"""
from __future__ import annotations

import struct
from dataclasses import dataclass

MAX_FRAME_SIZE = 2**14  # RFC 9113 default SETTINGS_MAX_FRAME_SIZE
CLIENT_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

FRAME_TYPES = {
    0x0: "DATA", 0x1: "HEADERS", 0x2: "PRIORITY", 0x3: "RST_STREAM",
    0x4: "SETTINGS", 0x5: "PUSH_PROMISE", 0x6: "PING", 0x7: "GOAWAY",
    0x8: "WINDOW_UPDATE", 0x9: "CONTINUATION",
}
FLAG_NAMES = {
    0x0: {0x1: "END_STREAM", 0x8: "PADDED"},
    0x1: {0x1: "END_STREAM", 0x4: "END_HEADERS", 0x8: "PADDED",
          0x20: "PRIORITY"},
    0x4: {0x1: "ACK"},
    0x6: {0x1: "ACK"},
    0x9: {0x4: "END_HEADERS"},
}


@dataclass(frozen=True)
class Frame:
    length: int
    type_code: int
    flags: int
    stream_id: int
    payload: bytes

    @property
    def type_name(self) -> str:
        return FRAME_TYPES.get(self.type_code, f"UNKNOWN(0x{self.type_code:02x})")

    @property
    def flag_names(self) -> str:
        known = FLAG_NAMES.get(self.type_code, {})
        names = [v for bit, v in known.items() if self.flags & bit]
        return "|".join(names) if names else "-"


def parse_frame(buf: bytes, offset: int) -> tuple[Frame, int]:
    """Parse one frame starting at offset. Raises on truncation."""
    if len(buf) - offset < 9:
        raise ValueError("truncated frame header")
    length = int.from_bytes(buf[offset : offset + 3], "big")
    type_code, flags = buf[offset + 3], buf[offset + 4]
    raw_sid = struct.unpack_from(">I", buf, offset + 5)[0]
    stream_id = raw_sid & 0x7FFFFFFF  # strip reserved bit
    end = offset + 9 + length
    if length > MAX_FRAME_SIZE:
        raise ValueError(f"frame length {length} exceeds MAX_FRAME_SIZE")
    if len(buf) < end:
        raise ValueError("truncated frame payload")
    return Frame(length, type_code, flags, stream_id,
                 buf[offset + 9 : end]), end


def build_fixture() -> bytes:
    """Preface + SETTINGS + SETTINGS-ACK + HEADERS + DATA on stream 1."""
    def frame(t: int, f: int, sid: int, payload: bytes) -> bytes:
        return (len(payload).to_bytes(3, "big") + bytes([t, f])
                + (sid & 0x7FFFFFFF).to_bytes(4, "big") + payload)

    settings = struct.pack(">HI", 0x3, 100)  # MAX_CONCURRENT_STREAMS=100
    headers_block = bytes([0x82, 0x86, 0x84])  # HPACK: :method GET,
                                               # :scheme http, :path /
    data = b'{"robot":"Weld-Bot"}'
    return b"".join([
        CLIENT_PREFACE,
        frame(0x4, 0x0, 0, settings),        # SETTINGS
        frame(0x4, 0x1, 0, b""),             # SETTINGS ack
        frame(0x1, 0x4 | 0x1, 1, headers_block),  # HEADERS END_HEADERS|END_STREAM
        frame(0x0, 0x1, 1, data),            # DATA END_STREAM
    ])


def main() -> None:
    stream = build_fixture()
    assert stream[:24] == CLIENT_PREFACE
    print(f"client preface (24 octets): {CLIENT_PREFACE!r}")
    print(f"{'len':>5} {'type':<14} {'flags':<28} {'stream':>6}")
    offset = len(CLIENT_PREFACE)
    frames: list[Frame] = []
    while offset < len(stream):
        frame_obj, offset = parse_frame(stream, offset)
        frames.append(frame_obj)
        print(f"{frame_obj.length:>5} {frame_obj.type_name:<14} "
              f"{frame_obj.flag_names:<28} {frame_obj.stream_id:>6}")
    assert [f.type_code for f in frames] == [0x4, 0x4, 0x1, 0x0]
    assert frames[2].stream_id == 1 and frames[2].flags & 0x4
    assert frames[3].payload == b'{"robot":"Weld-Bot"}'
    print("=== OK: 4 frames parsed, flags and stream IDs verified ===")


if __name__ == "__main__":
    main()
