"""Listing 7 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Offline tests for the WebSocket demo and the RFC 6455 handshake math."""
from __future__ import annotations

import asyncio

from ws_demo import BroadcastHub, demo, sec_websocket_accept


def test_sec_websocket_accept_matches_rfc6455_example() -> None:
    # Worked example straight from RFC 6455 section 1.3.
    assert sec_websocket_accept("dGhlIHNhbXBsZSBub25jZQ==") == \
        "s3pPLMBiTxaQ9kYGzzhZRbK+xOo="


def test_echo_broadcast_ping_and_clean_close() -> None:
    received = asyncio.run(demo())
    assert "echo:NWR-07 online" in received
    assert "peer got broadcast:NWR-07 online" in received  # delivered to the peer
    assert "pong received" in received


def test_hub_disconnect_cleans_registry() -> None:
    async def scenario() -> BroadcastHub:
        from websockets.asyncio.client import connect
        from websockets.asyncio.server import serve

        hub = BroadcastHub()
        async with await serve(hub.handler, "127.0.0.1", 0) as server:
            port = server.sockets[0].getsockname()[1]
            async with connect(f"ws://127.0.0.1:{port}"):
                assert len(hub.clients) == 1
            # allow the server task to run its finally block deterministically
            for _ in range(10):
                await asyncio.sleep(0)
                if not hub.clients:
                    break
        return hub

    hub = asyncio.run(scenario())
    assert hub.clients == set()
