"""Listing 8 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Long polling, for contrast with SSE: hold the request until data or deadline."""
from __future__ import annotations

import asyncio

from fastapi import FastAPI, Query
from pydantic import BaseModel

HOLD_SECONDS = 15.0  # server-side deadline, always below the proxy idle timeout


class Notification(BaseModel):
    notification_id: int
    robot: str
    message: str


class NotificationBus:
    def __init__(self) -> None:
        self._waiters: list[asyncio.Queue[Notification]] = []

    def subscribe(self) -> asyncio.Queue[Notification]:
        queue: asyncio.Queue[Notification] = asyncio.Queue()
        self._waiters.append(queue)
        return queue

    def publish(self, note: Notification) -> None:
        for queue in self._waiters:
            queue.put_nowait(note)


def create_app(bus: NotificationBus) -> FastAPI:
    app = FastAPI(title="Northwind Robotics Long-Poll Notifications")

    @app.get("/notifications/next", response_model=Notification | None)
    async def next_notification(after: int = Query(0, ge=0)) -> Notification | None:
        queue = bus.subscribe()
        try:
            return await asyncio.wait_for(queue.get(), timeout=HOLD_SECONDS)
        except TimeoutError:
            return None  # 200 with null body: client reconnects immediately

    return app
