"""Listing 4 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Server-Sent Events: FastAPI producer + a dependency-free client parser."""
from __future__ import annotations

from collections.abc import AsyncIterator, Iterable, Iterator
from dataclasses import dataclass

from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse

# The scripted Northwind Robotics telemetry feed (synthetic, deterministic).
TELEMETRY_FEED: list[tuple[int, str, str]] = [
    (1, "telemetry", '{"robot": "NWR-07", "battery": 0.82}'),
    (2, "telemetry", '{"robot": "NWR-07", "battery": 0.79}'),
    (3, "alert", '{"robot": "NWR-07", "alert": "dock requested"}'),
]
RETRY_MS = 2000


def format_sse(data: str, *, event: str | None = None,
               event_id: int | None = None, retry: int | None = None) -> str:
    """Serialize one SSE event block. Multi-line data gets one "data:" per line."""
    lines: list[str] = []
    if event is not None:
        lines.append(f"event: {event}")
    for data_line in data.splitlines():
        lines.append(f"data: {data_line}")
    if event_id is not None:
        lines.append(f"id: {event_id}")
    if retry is not None:
        lines.append(f"retry: {retry}")
    return "\n".join(lines) + "\n\n"


@dataclass(frozen=True)
class ServerSentEvent:
    data: str
    event: str = "message"
    event_id: str | None = None
    retry: int | None = None


def parse_sse(lines: Iterable[str]) -> Iterator[ServerSentEvent]:
    """Parse text/event-stream lines per the WHATWG dispatch rules.

    A blank line dispatches the buffered event; lines starting with ":" are
    comments (keep-alives) and are ignored.
    """
    data_parts: list[str] = []
    event_type: str | None = None
    event_id: str | None = None
    retry: int | None = None

    def dispatch() -> ServerSentEvent | None:
        nonlocal data_parts, event_type
        if not data_parts:
            event_type = None
            return None
        parsed = ServerSentEvent("\n".join(data_parts),
                                 event_type or "message", event_id, retry)
        data_parts, event_type = [], None
        return parsed

    for raw in lines:
        line = raw.rstrip("\r\n")
        if line == "":
            dispatched = dispatch()
            if dispatched is not None:
                yield dispatched
        elif line.startswith(":"):
            continue
        else:
            field, _, value = line.partition(":")
            if value.startswith(" "):
                value = value[1:]
            if field == "data":
                data_parts.append(value)
            elif field == "event":
                event_type = value
            elif field == "id":
                event_id = value
            elif field == "retry":
                if value.isdigit():
                    retry = int(value)
    dispatched = dispatch()
    if dispatched is not None:
        yield dispatched


def create_app() -> FastAPI:
    app = FastAPI(title="Northwind Robotics Telemetry Stream")

    async def event_generator(last_event_id: int) -> AsyncIterator[str]:
        # Announce the reconnection delay first, then resume AFTER last_event_id.
        yield format_sse("connected", event="control", retry=RETRY_MS)
        for event_id, event_type, data in TELEMETRY_FEED:
            if event_id > last_event_id:
                yield format_sse(data, event=event_type, event_id=event_id)
        yield ": keep-alive\n\n"

    @app.get("/stream")
    async def stream(request: Request) -> StreamingResponse:
        raw_last_id = request.headers.get("last-event-id", "0")
        last_event_id = int(raw_last_id) if raw_last_id.isdigit() else 0
        return StreamingResponse(
            event_generator(last_event_id),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    return app
