"""Listing 5 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Offline tests for the SSE producer, parser, and Last-Event-ID resume."""
from __future__ import annotations

from fastapi.testclient import TestClient

from sse_streams import RETRY_MS, create_app, format_sse, parse_sse

FIXTURE_STREAM = (
    ": this is a comment keep-alive\n"
    "\n"
    "event: telemetry\n"
    "data: {\"robot\": \"NWR-07\",\n"
    "data: \"battery\": 0.82}\n"
    "id: 42\n"
    "retry: 1500\n"
    "\n"
    "data: bare message with default event type\n"
    "\n"
)


def test_parser_handles_comments_multiline_data_id_and_retry() -> None:
    events = list(parse_sse(FIXTURE_STREAM.splitlines(keepends=True)))
    assert len(events) == 2
    first, second = events
    assert first.event == "telemetry"
    assert first.data == '{"robot": "NWR-07",\n"battery": 0.82}'  # multi-line join
    assert first.event_id == "42"
    assert first.retry == 1500
    assert second.event == "message"  # default type
    assert second.retry == 1500  # retry persists until replaced


def test_format_sse_round_trips_through_parser() -> None:
    wire = format_sse("line one\nline two", event="alert", event_id=7, retry=500)
    (event,) = list(parse_sse(wire.splitlines(keepends=True)))
    assert (event.data, event.event, event.event_id, event.retry) == (
        "line one\nline two", "alert", "7", 500,
    )


def test_server_streams_all_events_with_ids() -> None:
    client = TestClient(create_app())
    with client.stream("GET", "/stream") as response:
        assert response.status_code == 200
        assert response.headers["content-type"].startswith("text/event-stream")
        assert response.headers["x-accel-buffering"] == "no"
        events = list(parse_sse(response.iter_lines()))
    ids = [e.event_id for e in events if e.event_id is not None]
    assert ids == ["1", "2", "3"]
    assert events[0].retry == RETRY_MS
    assert events[-1].event == "alert"


def test_server_resumes_after_last_event_id() -> None:
    """Reconnect with Last-Event-ID: 2 -> only event 3 is replayed."""
    client = TestClient(create_app())
    with client.stream("GET", "/stream", headers={"Last-Event-ID": "2"}) as response:
        events = list(parse_sse(response.iter_lines()))
    replayed = [e for e in events if e.event_id is not None]
    assert [e.event_id for e in replayed] == ["3"]
    assert replayed[0].event == "alert"
