"""Listing 1 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Webhook receiver with Stripe-style HMAC-SHA256 signature verification."""
from __future__ import annotations

import hashlib
import hmac
import json
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

SIGNATURE_HEADER = "x-northwind-signature"
TOLERANCE_SECONDS = 300


def compute_signature(secret: str, timestamp: int, body: bytes) -> str:
    """Return the hex HMAC-SHA256 of "<timestamp>.<body>"."""
    signed_payload = str(timestamp).encode("utf-8") + b"." + body
    digest = hmac.new(secret.encode("utf-8"), signed_payload, hashlib.sha256)
    return digest.hexdigest()


def parse_signature_header(header: str) -> tuple[int, list[str]]:
    """Parse "t=...,v1=..." into (timestamp, [signatures]); ValueError if malformed."""
    timestamp: int | None = None
    signatures: list[str] = []
    for part in header.split(","):
        key, _, value = part.partition("=")
        if key.strip() == "t":
            try:
                timestamp = int(value)
            except ValueError as exc:
                raise ValueError("non-integer timestamp") from exc
        elif key.strip() == "v1":
            signatures.append(value.strip())
    if timestamp is None or not signatures:
        raise ValueError("malformed signature header")
    return timestamp, signatures


@dataclass
class IdempotencyStore:
    """In-memory set of processed event ids (swap for Redis/Postgres in prod)."""

    processed: set[str] = field(default_factory=set)

    def is_duplicate(self, event_id: str) -> bool:
        return event_id in self.processed

    def mark_processed(self, event_id: str) -> None:
        self.processed.add(event_id)


def _problem(status: int, title: str, detail: str) -> JSONResponse:
    return JSONResponse(
        status_code=status,
        media_type="application/problem+json",
        content={"type": "about:blank", "title": title,
                 "status": status, "detail": detail},
    )


def create_app(
    secret: str,
    store: IdempotencyStore,
    now: Callable[[], float] = time.time,
    tolerance_seconds: int = TOLERANCE_SECONDS,
) -> FastAPI:
    app = FastAPI(title="Northwind Robotics Webhook Receiver")

    @app.post("/webhooks/telemetry")
    async def receive_telemetry(request: Request) -> JSONResponse:
        body = await request.body()
        raw_header = request.headers.get(SIGNATURE_HEADER, "")
        try:
            timestamp, signatures = parse_signature_header(raw_header)
        except ValueError:
            return _problem(400, "Malformed Signature",
                            "Signature header is missing or malformed.")

        # Replay protection: refuse events signed too far from our clock.
        if abs(now() - timestamp) > tolerance_seconds:
            return _problem(400, "Stale Timestamp",
                            "Signature timestamp outside tolerance window.")

        expected = compute_signature(secret, timestamp, body)
        if not any(hmac.compare_digest(expected, c) for c in signatures):
            return _problem(400, "Invalid Signature",
                            "No v1 signature matches the payload.")

        try:
            event: dict[str, Any] = json.loads(body)
            event_id = str(event["id"])
        except (json.JSONDecodeError, KeyError, TypeError):
            return _problem(400, "Malformed Event",
                            "Body is not a JSON event with an id field.")

        # Idempotent receiver: at-least-once delivery means duplicates WILL arrive.
        if store.is_duplicate(event_id):
            return JSONResponse(status_code=200,
                                content={"status": "duplicate", "id": event_id})
        store.mark_processed(event_id)
        return JSONResponse(status_code=200,
                            content={"status": "processed", "id": event_id})

    return app
