"""Listing 3 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Offline, deterministic tests for the webhook receiver and delivery worker."""
from __future__ import annotations

import json

import pytest
from fastapi.testclient import TestClient

from webhook_delivery import DeliveryOutcome, WebhookDeliverer, WebhookEvent
from webhook_receiver import (
    IdempotencyStore, compute_signature, create_app, parse_signature_header,
)

SECRET = "whsec_northwind_test_only"
NOW = 1_700_000_000  # fixed clock: no wall-time dependence


def signed_headers(secret: str, timestamp: int, body: bytes) -> dict[str, str]:
    sig = compute_signature(secret, timestamp, body)
    return {"x-northwind-signature": f"t={timestamp},v1={sig}"}


def event_body(event_id: str = "evt_1001") -> bytes:
    return json.dumps({"id": event_id, "type": "robot.telemetry",
                       "data": {"robot": "NWR-07", "battery": 0.82}}).encode()


@pytest.fixture()
def client() -> TestClient:
    app = create_app(SECRET, IdempotencyStore(), now=lambda: float(NOW))
    return TestClient(app)


def test_valid_signature_is_processed(client: TestClient) -> None:
    body = event_body()
    resp = client.post("/webhooks/telemetry", content=body,
                       headers=signed_headers(SECRET, NOW, body))
    assert resp.status_code == 200
    assert resp.json() == {"status": "processed", "id": "evt_1001"}


def test_tampered_body_is_rejected(client: TestClient) -> None:
    body = event_body()
    headers = signed_headers(SECRET, NOW, body)
    tampered = body.replace(b"0.82", b"0.01")  # attacker flips the battery level
    resp = client.post("/webhooks/telemetry", content=tampered, headers=headers)
    assert resp.status_code == 400
    assert resp.json()["title"] == "Invalid Signature"


def test_stale_timestamp_is_rejected(client: TestClient) -> None:
    body = event_body()
    old = NOW - 3600  # signed an hour ago: outside the 300 s tolerance
    resp = client.post("/webhooks/telemetry", content=body,
                       headers=signed_headers(SECRET, old, body))
    assert resp.status_code == 400
    assert resp.json()["title"] == "Stale Timestamp"


def test_wrong_secret_is_rejected(client: TestClient) -> None:
    body = event_body()
    headers = signed_headers("whsec_attacker_guess", NOW, body)
    resp = client.post("/webhooks/telemetry", content=body, headers=headers)
    assert resp.status_code == 400


def test_replayed_delivery_is_idempotent(client: TestClient) -> None:
    body = event_body()
    headers = signed_headers(SECRET, NOW, body)
    first = client.post("/webhooks/telemetry", content=body, headers=headers)
    replay = client.post("/webhooks/telemetry", content=body, headers=headers)
    assert first.json()["status"] == "processed"
    assert replay.status_code == 200  # ack again, but do not reprocess
    assert replay.json()["status"] == "duplicate"


def test_header_parsing_supports_rotation_overlap() -> None:
    ts, sigs = parse_signature_header("t=1700000000,v1=aaa,v1=bbb")
    assert ts == NOW
    assert sigs == ["aaa", "bbb"]


def make_event() -> WebhookEvent:
    return WebhookEvent("evt_1001", "robot.telemetry", NOW, {"robot": "NWR-07"})


class FakeTransport:
    """Scripted statuses; records every call. OSError simulates connection failure."""

    def __init__(self, script: list[int | type[OSError]]) -> None:
        self.script = script
        self.calls: list[tuple[str, dict[str, str], bytes]] = []

    def __call__(self, url: str, headers: dict[str, str], body: bytes) -> int:
        self.calls.append((url, headers, body))
        outcome = self.script.pop(0)
        if isinstance(outcome, type):
            raise outcome("connection refused")
        return outcome


def make_deliverer(transport: FakeTransport) -> tuple[WebhookDeliverer, list[float]]:
    sleeps: list[float] = []
    deliverer = WebhookDeliverer(
        SECRET, transport, max_attempts=5, base_delay_seconds=1.0,
        now=lambda: float(NOW), sleeper=sleeps.append,
    )
    return deliverer, sleeps


def test_delivery_succeeds_first_try() -> None:
    transport = FakeTransport([200])
    deliverer, sleeps = make_deliverer(transport)
    outcome = deliverer.deliver("https://ops.northwind-robotics.example/hook", make_event())
    assert outcome is DeliveryOutcome.DELIVERED
    assert len(transport.calls) == 1 and sleeps == [] and deliverer.dead_letters == []


def test_delivery_retries_5xx_with_backoff_then_succeeds() -> None:
    transport = FakeTransport([500, 503, 200])
    deliverer, sleeps = make_deliverer(transport)
    outcome = deliverer.deliver("https://ops.northwind-robotics.example/hook", make_event())
    assert outcome is DeliveryOutcome.DELIVERED
    assert len(transport.calls) == 3
    assert sleeps == [1.0, 2.0]  # deterministic exponential backoff, no real waiting


def test_delivery_dead_letters_after_max_attempts() -> None:
    transport = FakeTransport([500, 500, 500, 500, 500])
    deliverer, sleeps = make_deliverer(transport)
    outcome = deliverer.deliver("https://ops.northwind-robotics.example/hook", make_event())
    assert outcome is DeliveryOutcome.DEAD_LETTERED
    assert sleeps == [1.0, 2.0, 4.0, 8.0]
    assert len(deliverer.dead_letters) == 1
    assert deliverer.dead_letters[0].reason == "max attempts exhausted"


def test_delivery_does_not_retry_permanent_4xx() -> None:
    transport = FakeTransport([422])
    deliverer, sleeps = make_deliverer(transport)
    outcome = deliverer.deliver("https://ops.northwind-robotics.example/hook", make_event())
    assert outcome is DeliveryOutcome.REJECTED_PERMANENT
    assert len(transport.calls) == 1 and sleeps == []
    assert deliverer.dead_letters[0].reason == "permanent 422"


def test_network_error_is_retryable() -> None:
    transport = FakeTransport([OSError, 200])
    deliverer, _ = make_deliverer(transport)
    outcome = deliverer.deliver("https://ops.northwind-robotics.example/hook", make_event())
    assert outcome is DeliveryOutcome.DELIVERED
    assert transport.calls[0][1]["x-northwind-signature"].startswith(f"t={NOW},v1=")
