"""Listing 6 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Minimal WebSocket echo/broadcast demo + the RFC 6455 handshake math."""
from __future__ import annotations

import asyncio
import base64
import hashlib
from typing import Any

from websockets.asyncio.client import connect
from websockets.asyncio.server import ServerConnection, serve

WS_GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"  # fixed by RFC 6455 section 1.3


def sec_websocket_accept(key: str) -> str:
    """Derive Sec-WebSocket-Accept from the client's Sec-WebSocket-Key."""
    sha1 = hashlib.sha1((key + WS_GUID).encode("ascii")).digest()
    return base64.b64encode(sha1).decode("ascii")


class BroadcastHub:
    """Tracks connected robot consoles; every message is echoed and broadcast."""

    def __init__(self) -> None:
        self.clients: set[ServerConnection] = set()

    async def handler(self, ws: ServerConnection) -> None:
        self.clients.add(ws)
        try:
            async for message in ws:
                await ws.send(f"echo:{message}")  # direct echo to the sender
                for peer in self.clients - {ws}:
                    await peer.send(f"broadcast:{message}")
        finally:
            self.clients.discard(ws)


async def run_server(hub: BroadcastHub) -> Any:
    return await serve(hub.handler, "127.0.0.1", 0)  # port 0 => OS picks a free port


async def demo() -> list[str]:
    """Deterministic scripted session; asyncio.Event provides synchronization."""
    hub = BroadcastHub()
    received: list[str] = []
    peer_ready = asyncio.Event()

    async with await run_server(hub) as server:
        port = server.sockets[0].getsockname()[1]

        async def peer() -> None:
            async with connect(f"ws://127.0.0.1:{port}") as ws:
                peer_ready.set()
                async for message in ws:
                    received.append(f"peer got {message}")

        peer_task = asyncio.create_task(peer())
        await peer_ready.wait()  # explicit synchronization, never sleep-based

        async with connect(f"ws://127.0.0.1:{port}") as ws:
            await ws.send("NWR-07 online")
            received.append(await ws.recv())  # our own echo

            pong = await ws.ping()  # protocol-level keep-alive (opcode 0x9/0xA)
            await asyncio.wait_for(pong, timeout=5)
            received.append("pong received")

            await ws.close(code=1000, reason="demo complete")  # clean close
        peer_task.cancel()

    return received


if __name__ == "__main__":
    print(sec_websocket_accept("dGhlIHNhbXBsZSBub25jZQ=="))  # RFC 6455 example
    for line in asyncio.run(demo()):
        print(line)
