"""Listing 2 extracted from chapters/chapter_11_async_event_driven_apis.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Webhook delivery worker: bounded retries, backoff, and a dead-letter log."""
from __future__ import annotations

import json
import time
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum
from typing import Any

from webhook_receiver import compute_signature

RETRYABLE_STATUSES = frozenset({408, 409, 425, 429, 500, 502, 503, 504})


class DeliveryOutcome(str, Enum):
    DELIVERED = "delivered"
    DEAD_LETTERED = "dead_lettered"
    REJECTED_PERMANENT = "rejected_permanent"


@dataclass(frozen=True)
class WebhookEvent:
    event_id: str
    event_type: str
    occurred_at: int
    payload: dict[str, Any]

    def body_bytes(self) -> bytes:
        doc = {"id": self.event_id, "type": self.event_type,
               "occurred_at": self.occurred_at, "data": self.payload}
        return json.dumps(doc, sort_keys=True).encode("utf-8")


@dataclass(frozen=True)
class Attempt:
    number: int
    status: int | None  # None => transport raised (connection refused, DNS, ...)
    retryable: bool


@dataclass(frozen=True)
class DeadLetter:
    event_id: str
    endpoint: str
    attempts: tuple[Attempt, ...]
    reason: str


Transport = Callable[[str, dict[str, str], bytes], int]


class WebhookDeliverer:
    def __init__(
        self,
        secret: str,
        transport: Transport,
        *,
        max_attempts: int = 5,
        base_delay_seconds: float = 1.0,
        now: Callable[[], float] = time.time,
        sleeper: Callable[[float], None] = time.sleep,
    ) -> None:
        if max_attempts < 1:
            raise ValueError("max_attempts must be >= 1")
        self._secret = secret
        self._transport = transport
        self._max_attempts = max_attempts
        self._base_delay = base_delay_seconds
        self._now = now
        self._sleeper = sleeper
        self.dead_letters: list[DeadLetter] = []

    def backoff_delay(self, attempt_number: int) -> float:
        """Exponential backoff with a deterministic cap: 1, 2, 4, 8, ... capped at 60s."""
        return min(self._base_delay * (2 ** (attempt_number - 1)), 60.0)

    def deliver(self, endpoint: str, event: WebhookEvent) -> DeliveryOutcome:
        body = event.body_bytes()
        attempts: list[Attempt] = []
        for number in range(1, self._max_attempts + 1):
            timestamp = int(self._now())
            headers = {
                "content-type": "application/json",
                "x-northwind-signature": (
                    f"t={timestamp},v1={compute_signature(self._secret, timestamp, body)}"
                ),
            }
            try:
                status = self._transport(endpoint, headers, body)
                retryable = status in RETRYABLE_STATUSES
            except OSError:
                status, retryable = None, True
            attempts.append(Attempt(number=number, status=status, retryable=retryable))

            if status is not None and 200 <= status < 300:
                return DeliveryOutcome.DELIVERED
            if status is not None and not retryable:
                # 4xx (other than 408/409/425/429) means "stop calling me";
                # retrying forever is how webhook loops turn into a DDoS.
                self._dead_letter(event, endpoint, attempts, f"permanent {status}")
                return DeliveryOutcome.REJECTED_PERMANENT
            if number < self._max_attempts:
                self._sleeper(self.backoff_delay(number))

        self._dead_letter(event, endpoint, attempts, "max attempts exhausted")
        return DeliveryOutcome.DEAD_LETTERED

    def _dead_letter(
        self, event: WebhookEvent, endpoint: str, attempts: list[Attempt], reason: str
    ) -> None:
        self.dead_letters.append(
            DeadLetter(event.event_id, endpoint, tuple(attempts), reason)
        )
