"""Extract executable artifacts from the book's LaTeX chapters.

Scans chapters/chapter_*.tex for minted blocks and materializes them under
code/chNN/ so every listing in the book is runnable without copy-pasting
from the PDF:

  * {python} blocks  -> code/chNN/listing_NN.py  (plus py_compile gate)
  * requirements.txt blocks -> code/chNN/requirements.txt

Chapters that already ship a curated code/chNN/ directory (authored and
tested by the chapter pipeline) are left untouched except for the
py_compile gate over their existing *.py files.

Usage (PowerShell, from the book root):
    python tools\\extract_code.py            # write artifacts + verify
    python tools\\extract_code.py --check    # CI mode: fail if out of sync
"""
from __future__ import annotations

import argparse
import py_compile
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS_DIR = ROOT / "chapters"
CODE_DIR = ROOT / "code"

MINTED_RE = re.compile(
    r"\\begin\{minted\}(?:\[[^\]]*\])?\{([^}]*)\}\n(.*?)\\end\{minted\}",
    re.DOTALL,
)
CHAPTER_RE = re.compile(r"chapter_(\d+)_([a-z0-9_]+)\.tex$")
REQUIREMENTS_HINT = re.compile(
    r"^[a-zA-Z0-9_\-\[\]]+\s*(>=|==|~=|<=)", re.MULTILINE
)

HEADER = (
    '"""Listing {n} extracted from chapters/{chapter}.\n\n'
    "Auto-generated by tools/extract_code.py -- do not edit here.\n"
    '"""\n\n'
)


@dataclass
class ChapterResult:
    chapter: str
    python_blocks: int = 0
    requirements_written: bool = False
    compiled: list[str] = field(default_factory=list)
    failed: list[str] = field(default_factory=list)
    curated: bool = False


def chapter_key(path: Path) -> str:
    m = CHAPTER_RE.match(path.name)
    if not m:
        raise ValueError(f"unexpected chapter filename: {path.name}")
    return f"ch{m.group(1)}"


def extract_blocks(text: str, language: str) -> list[str]:
    return [body for lang, body in MINTED_RE.findall(text) if lang == language]


def looks_like_requirements(body: str) -> bool:
    lines = [
        ln.strip()
        for ln in body.splitlines()
        if ln.strip() and not ln.strip().startswith("#")
    ]
    return bool(lines) and all(REQUIREMENTS_HINT.match(ln) for ln in lines)


def py_compile_ok(path: Path) -> bool:
    try:
        py_compile.compile(str(path), doraise=True, quiet=2)
        return True
    except py_compile.PyCompileError:
        return False


def process_chapter(tex_path: Path, check_only: bool) -> ChapterResult:
    ch = chapter_key(tex_path)
    result = ChapterResult(chapter=ch)
    out_dir = CODE_DIR / ch
    text = tex_path.read_text(encoding="utf-8")

    python_blocks = extract_blocks(text, "python")
    result.python_blocks = len(python_blocks)

    # requirements.txt: find a minted text block that parses as pip pins
    req_body = next(
        (body for _, body in MINTED_RE.findall(text)
         if _ != "python" and looks_like_requirements(body)),
        None,
    )

    if out_dir.exists() and any(out_dir.glob("*.py")):
        # Curated directory: verify listings, never overwrite; still fill in a
        # missing requirements.txt from the chapter's minted block.
        result.curated = True
        targets = sorted(out_dir.rglob("*.py"))
        req_file = out_dir / "requirements.txt"
        if req_body is not None and not req_file.exists():
            if check_only:
                result.failed.append("requirements.txt (missing)")
            else:
                req_file.write_text(req_body.strip() + "\n", encoding="utf-8")
                result.requirements_written = True
    else:
        targets = []
        if not check_only:
            out_dir.mkdir(parents=True, exist_ok=True)
        for i, body in enumerate(python_blocks, start=1):
            target = out_dir / f"listing_{i:02d}.py"
            payload = HEADER.format(n=i, chapter=tex_path.name) + body
            if check_only:
                if not target.exists() or target.read_text(encoding="utf-8") != payload:
                    result.failed.append(f"{target.name} (out of sync)")
                else:
                    result.compiled.append(target.name)
                    if not py_compile_ok(target):
                        result.failed.append(f"{target.name} (compile)")
                continue
            target.write_text(payload, encoding="utf-8")
            targets.append(target)
        if req_body is not None and not check_only:
            (out_dir / "requirements.txt").write_text(
                req_body.strip() + "\n", encoding="utf-8"
            )
            result.requirements_written = True
        if req_body is not None and check_only:
            req_file = out_dir / "requirements.txt"
            if not req_file.exists() or req_file.read_text(encoding="utf-8") != req_body.strip() + "\n":
                result.failed.append("requirements.txt (out of sync)")

    for target in targets:
        if py_compile_ok(target):
            result.compiled.append(target.name)
        else:
            result.failed.append(target.name)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify code/ is in sync; do not write")
    args = parser.parse_args()

    chapters = sorted(CHAPTERS_DIR.glob("chapter_*.tex"))
    if not chapters:
        print("no chapters found", file=sys.stderr)
        return 2

    total_failed = 0
    for tex in chapters:
        res = process_chapter(tex, args.check)
        total_failed += len(res.failed)
        kind = "curated" if res.curated else "extracted"
        status = "OK " if not res.failed else "FAIL"
        print(f"[{status}] {res.chapter} ({kind}, {res.python_blocks} python blocks, "
              f"{len(res.compiled)} compiled, {len(res.failed)} failed)")
        for failure in res.failed:
            print(f"       - {failure}")

    if total_failed:
        print(f"\n{total_failed} failure(s)", file=sys.stderr)
        return 1
    print("\nAll chapters extracted and compile-clean.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
