"""Listing 6 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""test_contract.py -- Contract tests: every error path is valid problem+json.

Listing 7.5. In-process ASGI tests via httpx TestClient. Fully offline.
"""
from __future__ import annotations

import jsonschema
import pytest
from fastapi.testclient import TestClient

from app import app

PROBLEM_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["type", "title", "status"],
    "properties": {
        "type": {"type": "string", "format": "uri-reference"},
        "title": {"type": "string", "minLength": 1},
        "status": {"type": "integer", "minimum": 400, "maximum": 599},
        "detail": {"type": "string"},
        "instance": {"type": "string"},
        "code": {"type": "string", "pattern": "^NRW-[A-Z-]+$"},
        "trace_id": {"type": "string", "minLength": 1},
        "errors": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["pointer", "code", "message"],
                "properties": {
                    "pointer": {"type": "string", "pattern": "^/"},
                    "code": {"type": "string"},
                    "message": {"type": "string"},
                },
            },
        },
    },
    "additionalProperties": False,
}

PII_FRAGMENTS = ("@", "123-45-6789", "Traceback", 'File "')


@pytest.fixture()
def client() -> TestClient:
    return TestClient(app, raise_server_exceptions=False)


def assert_problem(response, expected_status: int) -> dict:
    assert response.status_code == expected_status
    assert response.headers["content-type"].startswith("application/problem+json")
    body = response.json()
    jsonschema.validate(body, PROBLEM_SCHEMA)
    assert body["status"] == expected_status
    assert "X-Trace-Id" in response.headers
    assert body["trace_id"] == response.headers["X-Trace-Id"]
    return body


def test_404_is_problem_json(client: TestClient) -> None:
    body = assert_problem(client.get("/shipments/shp_99999999"), 404)
    assert body["code"] == "NRW-SHIPMENT-NOT-FOUND"
    assert body["type"].endswith("/shipment-not-found")


def test_422_maps_pydantic_errors_to_json_pointers(client: TestClient) -> None:
    payload = {
        "destination": {"street": "", "city": "Springfield", "country": "USA"},
        "lines": [{"sku": "bad-sku", "quantity": 0, "unit_weight_kg": "not-a-number"}],
        "priority": "hyperdrive",
    }
    body = assert_problem(client.post("/shipments", json=payload), 422)
    assert body["code"] == "NRW-VALIDATION-FAILED"
    pointers = {err["pointer"] for err in body["errors"]}
    # Each failure is located by an RFC 6901 JSON Pointer.
    assert "/destination/street" in pointers
    assert "/destination/country" in pointers
    assert "/lines/0/sku" in pointers
    assert "/lines/0/quantity" in pointers
    assert "/lines/0/unit_weight_kg" in pointers  # unparseable decimal
    assert "/priority" in pointers


def test_422_cross_field_invariant(client: TestClient) -> None:
    payload = {
        "destination": {"street": "1 Gearbox Lane", "city": "Springfield", "country": "US"},
        "lines": [{"sku": "NRW-AR-1001", "quantity": 10, "unit_weight_kg": 4.5}],
        "priority": "express",
    }
    body = assert_problem(client.post("/shipments", json=payload), 422)
    assert body["errors"][0]["pointer"] == "/"
    assert "express" in body["errors"][0]["message"]


def test_409_domain_conflict(client: TestClient) -> None:
    create = client.post(
        "/shipments",
        json={
            "destination": {"street": "9 Servo Rd", "city": "Springfield", "country": "US"},
            "lines": [{"sku": "NRW-FR-9000", "quantity": 1, "unit_weight_kg": 120}],
            "priority": "freight",
        },
    )
    assert create.status_code == 201
    shipment_id = create.json()["shipment_id"]
    body = assert_problem(client.post(f"/shipments/{shipment_id}/cancel"), 409)
    assert body["code"] == "NRW-SHIPMENT-STATE-CONFLICT"


def test_500_is_redacted_and_never_leaks_pii(client: TestClient) -> None:
    response = client.get("/debug/leaky")
    body = assert_problem(response, 500)
    for fragment in PII_FRAGMENTS:
        assert fragment not in response.text
    # The generic shape is preserved; the caller gets an actionable trace_id.
    assert body["code"] == "NRW-INTERNAL"


def test_429_carries_retry_after(client: TestClient) -> None:
    response = client.get("/shipments-throttled")
    assert_problem(response, 429)
    assert response.headers["Retry-After"] == "30"


def test_503_dependency_failure_is_retriable(client: TestClient) -> None:
    body = assert_problem(client.get("/warehouse/ping"), 503)
    assert body["code"] == "NRW-WAREHOUSE-UNAVAILABLE"


def test_client_supplied_trace_id_is_echoed(client: TestClient) -> None:
    response = client.get(
        "/shipments/shp_99999999", headers={"X-Trace-Id": "req-abc-123"}
    )
    assert response.headers["X-Trace-Id"] == "req-abc-123"
    assert response.json()["trace_id"] == "req-abc-123"


def test_malformed_trace_id_is_replaced(client: TestClient) -> None:
    response = client.get(
        "/shipments/shp_99999999", headers={"X-Trace-Id": "a" * 500}
    )
    trace_id = response.headers["X-Trace-Id"]
    assert trace_id != "a" * 500
    assert len(trace_id) <= 64


def test_happy_path_unaffected(client: TestClient) -> None:
    response = client.get("/shipments/shp_00000001")
    assert response.status_code == 200
    assert response.json()["shipment_id"] == "shp_00000001"
