"""Listing 1 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""problem_details.py -- Reusable RFC 9457 problem-details library.

Listing 7.1. Offline-first, stdlib + pydantic + fastapi only.
"""
from __future__ import annotations

import re
import uuid
from typing import Any, Optional

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field

PROBLEM_MEDIA_TYPE = "application/problem+json"

# Synthetic, obviously fictional documentation namespace (RFC 9457 type URIs).
TYPE_BASE = "https://docs.example.invalid/problems"


class ErrorLocation(BaseModel):
    """One field-level validation failure, located by JSON Pointer (RFC 6901)."""

    pointer: str = Field(description="JSON Pointer to the offending value")
    code: str = Field(description="Machine-readable error code")
    message: str = Field(description="Human-readable, redacted message")


class ProblemDetail(BaseModel):
    """RFC 9457 problem detail object with Northwind Robotics extensions."""

    model_config = ConfigDict(populate_by_name=True)

    type: str = Field(default="about:blank")
    title: str
    status: int
    detail: Optional[str] = None
    instance: Optional[str] = None
    # Extension members.
    code: Optional[str] = None
    trace_id: Optional[str] = None
    errors: list[ErrorLocation] = Field(default_factory=list)


class ProblemException(Exception):
    """Base class: a domain exception that maps 1:1 to a ProblemDetail."""

    status: int = 500
    title: str = "Internal Server Error"
    type_slug: str = "internal"
    code: str = "NRW-INTERNAL"

    def __init__(
        self,
        detail: Optional[str] = None,
        *,
        instance: Optional[str] = None,
        errors: Optional[list[ErrorLocation]] = None,
    ) -> None:
        super().__init__(detail)
        self.detail = detail
        self.instance = instance
        self.errors = errors or []

    def to_problem(self, trace_id: str) -> ProblemDetail:
        return ProblemDetail(
            type=f"{TYPE_BASE}/{self.type_slug}",
            title=self.title,
            status=self.status,
            detail=self.detail,
            instance=self.instance,
            code=self.code,
            trace_id=trace_id,
            errors=self.errors,
        )


class ShipmentNotFound(ProblemException):
    status = 404
    title = "Shipment Not Found"
    type_slug = "shipment-not-found"
    code = "NRW-SHIPMENT-NOT-FOUND"


class ShipmentStateConflict(ProblemException):
    status = 409
    title = "Shipment State Conflict"
    type_slug = "shipment-state-conflict"
    code = "NRW-SHIPMENT-STATE-CONFLICT"


class WarehouseUnavailable(ProblemException):
    status = 503
    title = "Dependency Unavailable"
    type_slug = "warehouse-unavailable"
    code = "NRW-WAREHOUSE-UNAVAILABLE"


class RateLimitExceeded(ProblemException):
    status = 429
    title = "Rate Limit Exceeded"
    type_slug = "rate-limit-exceeded"
    code = "NRW-RATE-LIMIT-EXCEEDED"

    def __init__(self, retry_after: int, **kwargs: Any) -> None:
        super().__init__(
            detail=f"Retry after {retry_after} seconds.", **kwargs
        )
        self.retry_after = retry_after


def json_pointer(loc: list[Any]) -> str:
    """Convert a Pydantic error `loc` tuple to an RFC 6901 JSON Pointer."""
    parts = []
    for seg in loc:
        if seg == "body":  # FastAPI wraps body params under "body"
            continue
        parts.append(str(seg).replace("~", "~0").replace("/", "~1"))
    return "/" + "/".join(parts)


def problem_response(
    problem: ProblemDetail,
    headers: Optional[dict[str, str]] = None,
) -> JSONResponse:
    payload = problem.model_dump(exclude_none=True)
    return JSONResponse(
        status_code=problem.status,
        content=payload,
        media_type=PROBLEM_MEDIA_TYPE,
        headers=headers,
    )


def register_problem_handlers(app: FastAPI) -> None:
    """Single pipeline: domain exception -> problem mapper -> redaction -> response."""

    @app.exception_handler(ProblemException)
    async def handle_problem(
        request: Request, exc: ProblemException
    ) -> JSONResponse:
        trace_id = getattr(request.state, "trace_id", str(uuid.uuid4()))
        problem = exc.to_problem(trace_id)
        headers = None
        if isinstance(exc, RateLimitExceeded):
            headers = {"Retry-After": str(exc.retry_after)}
        return problem_response(problem, headers=headers)

    @app.exception_handler(RequestValidationError)
    async def handle_validation(
        request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        trace_id = getattr(request.state, "trace_id", str(uuid.uuid4()))
        # 422: the payload was syntactically valid JSON but semantically invalid.
        locs = [
            ErrorLocation(
                pointer=json_pointer(list(err.get("loc", ()))),
                code=str(err.get("type", "invalid")),
                # Pydantic messages can echo raw input; drop ctx, keep it safe.
                message=str(err.get("msg", "Invalid value")),
            )
            for err in exc.errors()
        ]
        problem = ProblemDetail(
            type=f"{TYPE_BASE}/validation-failed",
            title="Validation Failed",
            status=422,
            detail="Request payload failed semantic validation.",
            instance=str(request.url.path),
            code="NRW-VALIDATION-FAILED",
            trace_id=trace_id,
            errors=locs,
        )
        return problem_response(problem)

    @app.exception_handler(Exception)
    async def handle_unexpected(
        request: Request, exc: Exception
    ) -> JSONResponse:
        trace_id = getattr(request.state, "trace_id", str(uuid.uuid4()))
        # Full context goes to the server log; the client gets a redacted body.
        print(f"trace_id={trace_id} unhandled={exc!r}")
        problem = ProblemDetail(
            type=f"{TYPE_BASE}/internal",
            title="Internal Server Error",
            status=500,
            detail="An unexpected error occurred. "
            "Reference the trace_id when contacting support.",
            instance=str(request.url.path),
            code="NRW-INTERNAL",
            trace_id=trace_id,
        )
        return problem_response(problem)


SECRET_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"), "<email>"),
    (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "<tax-id>"),
    (re.compile(r"(?i)(api[_-]?key|token|password)=[^&\s]+"), r"\1=<redacted>"),
]


def redact_text(text: str) -> str:
    """Scrub PII-like patterns and secrets from arbitrary text."""
    for pattern, replacement in SECRET_PATTERNS:
        text = pattern.sub(replacement, text)
    return text
