"""Listing 7 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""error_codes.py -- Machine-readable error-code registry with doc generation.

Listing 7.6. One source of truth: clients, docs, and alerts all derive from
this registry. Run directly to print the generated Markdown catalogue.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Retriable(str, Enum):
    YES = "yes"
    NO = "no"
    CONDITIONAL = "conditional"


@dataclass(frozen=True)
class ErrorCode:
    code: str            # stable, machine-readable, never reused
    http_status: int
    type_slug: str       # suffix of the RFC 9457 type URI
    title: str           # short, stable, localizable key
    retriable: Retriable
    owner: str           # team accountable for this failure mode
    remediation: str     # one-line client-actionable guidance


REGISTRY: tuple[ErrorCode, ...] = (
    ErrorCode(
        code="NRW-VALIDATION-FAILED",
        http_status=422,
        type_slug="validation-failed",
        title="Validation Failed",
        retriable=Retriable.NO,
        owner="api-platform",
        remediation="Fix the fields named in errors[].pointer and resend.",
    ),
    ErrorCode(
        code="NRW-SHIPMENT-NOT-FOUND",
        http_status=404,
        type_slug="shipment-not-found",
        title="Shipment Not Found",
        retriable=Retriable.NO,
        owner="fulfillment",
        remediation="Verify the shipment_id; do not retry blindly.",
    ),
    ErrorCode(
        code="NRW-SHIPMENT-STATE-CONFLICT",
        http_status=409,
        type_slug="shipment-state-conflict",
        title="Shipment State Conflict",
        retriable=Retriable.CONDITIONAL,
        owner="fulfillment",
        remediation="Refresh the resource, re-evaluate preconditions, retry once.",
    ),
    ErrorCode(
        code="NRW-RATE-LIMIT-EXCEEDED",
        http_status=429,
        type_slug="rate-limit-exceeded",
        title="Rate Limit Exceeded",
        retriable=Retriable.YES,
        owner="api-platform",
        remediation="Back off for Retry-After seconds, then retry with jitter.",
    ),
    ErrorCode(
        code="NRW-WAREHOUSE-UNAVAILABLE",
        http_status=503,
        type_slug="warehouse-unavailable",
        title="Dependency Unavailable",
        retriable=Retriable.YES,
        owner="warehouse-integrations",
        remediation="Retry with exponential backoff; alert if it persists > 5 min.",
    ),
    ErrorCode(
        code="NRW-INTERNAL",
        http_status=500,
        type_slug="internal",
        title="Internal Server Error",
        retriable=Retriable.NO,
        owner="api-platform",
        remediation="Report the trace_id to support; do not retry mutations.",
    ),
)


def validate_registry(registry: tuple[ErrorCode, ...] = REGISTRY) -> None:
    """Fail fast at import time if the registry is internally inconsistent."""
    codes = [entry.code for entry in registry]
    assert len(codes) == len(set(codes)), "duplicate error codes"
    for entry in registry:
        assert entry.code.startswith("NRW-"), f"bad prefix: {entry.code}"
        assert 400 <= entry.http_status <= 599, f"bad status: {entry.code}"
        assert entry.remediation, f"missing remediation: {entry.code}"
        if entry.http_status < 500:
            # Client-facing codes must explain what the CLIENT can do.
            assert "support" not in entry.remediation.lower() or entry.http_status == 500


def render_markdown(registry: tuple[ErrorCode, ...] = REGISTRY) -> str:
    """Generate the public error catalogue page from the registry."""
    lines = [
        "# Northwind Robotics API -- Error Code Catalogue",
        "",
        "| Code | HTTP | Title | Retriable | Owner | Remediation |",
        "|---|---|---|---|---|---|",
    ]
    for entry in registry:
        lines.append(
            f"| `{entry.code}` | {entry.http_status} | {entry.title} "
            f"| {entry.retriable.value} | {entry.owner} | {entry.remediation} |"
        )
    return "\n".join(lines)


validate_registry()

if __name__ == "__main__":
    print(render_markdown())
