"""Listing 5 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""app.py -- Northwind Robotics shipments service, wired for RFC 9457 errors.

Listing 7.4. In-memory store only: offline, deterministic, no network.
"""
from __future__ import annotations

from decimal import Decimal

from fastapi import FastAPI, Request

from problem_details import (
    ProblemException,
    RateLimitExceeded,
    ShipmentNotFound,
    ShipmentStateConflict,
    WarehouseUnavailable,
    register_problem_handlers,
)
from redaction import CorrelationIdMiddleware, ProblemRedactionMiddleware
from shipment_models import Shipment

# In-memory store keyed by shipment_id. Synthetic data only.
STORE: dict[str, Shipment] = {
    "shp_00000001": Shipment(
        shipment_id="shp_00000001",
        destination={
            "street": "1 Gearbox Lane",
            "city": "Springfield",
            "country": "US",
        },
        lines=[{"sku": "NRW-AR-1001", "quantity": 2, "unit_weight_kg": Decimal("4.5")}],
        priority="standard",
    )
}
SEQUENCE = {"next": 2}


def create_app() -> FastAPI:
    app = FastAPI(title="Northwind Robotics Shipments", version="1.0.0")
    # Middleware order matters: correlation first, redaction outermost-last.
    app.add_middleware(ProblemRedactionMiddleware)
    app.add_middleware(CorrelationIdMiddleware)
    register_problem_handlers(app)

    @app.post("/shipments", status_code=201)
    def create_shipment(shipment: Shipment, request: Request) -> Shipment:
        new_id = f"shp_{SEQUENCE['next']:08d}"
        SEQUENCE["next"] += 1
        stored = shipment.model_copy(update={"shipment_id": new_id})
        STORE[new_id] = stored
        return stored

    @app.get("/shipments/{shipment_id}")
    def get_shipment(shipment_id: str) -> Shipment:
        if shipment_id not in STORE:
            raise ShipmentNotFound(
                detail=f"No shipment with id {shipment_id!r} exists.",
                instance=f"/shipments/{shipment_id}",
            )
        return STORE[shipment_id]

    @app.post("/shipments/{shipment_id}/cancel")
    def cancel_shipment(shipment_id: str) -> Shipment:
        shipment = STORE.get(shipment_id)
        if shipment is None:
            raise ShipmentNotFound(detail="Cannot cancel a missing shipment.")
        if shipment.priority == "freight":
            # Domain rule: freight contracts lock at booking time.
            raise ShipmentStateConflict(
                detail="Freight shipments cannot be cancelled after booking.",
                instance=f"/shipments/{shipment_id}",
            )
        return shipment

    @app.get("/warehouse/ping")
    def warehouse_ping() -> dict[str, str]:
        # Simulated dependency failure: retriable, server-owned.
        raise WarehouseUnavailable(detail="Warehouse API timed out after 3 attempts.")

    @app.get("/shipments-throttled")
    def throttled() -> dict[str, str]:
        raise RateLimitExceeded(retry_after=30)

    @app.get("/debug/leaky")
    def leaky_failure() -> dict[str, str]:
        # A careless developer echoes request context into the error detail.
        raise ProblemException(
            detail="Failed to notify jane.doe@example.invalid; "
            "tax id 123-45-6789 on file."
        )

    return app


app = create_app()
