"""Listing 4 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""redaction.py -- Correlation IDs and response redaction middleware.

Listing 7.3. Guarantees: problem+json bodies never leak PII patterns or
stack traces; full context is logged server-side under the trace_id.
"""
from __future__ import annotations

import json
import logging
import re
import uuid
from typing import Awaitable, Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp

logger = logging.getLogger("northwind.errors")

TRACE_HEADER = "X-Trace-Id"
PROBLEM_MEDIA_TYPE = "application/problem+json"

# Deterministic, conservative scrub rules. Extend via registry, not edits.
PII_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"), "<email>"),
    (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "<tax-id>"),
    (re.compile(r"\b(?:\d[ -]?){13,16}\b"), "<card-number>"),
    (re.compile(r"(?i)(api[_-]?key|token|password|secret)[\"']?\s*[:=]\s*[\"']?[^&\s\"']+"), r"\1=<redacted>"),
]

STACK_TRACE_MARKER = re.compile(r"(Traceback \(most recent call last\)|File \"[^\"]+\", line \d+)")


def scrub(text: str) -> str:
    """Remove PII-like patterns and stack-trace fragments from text."""
    for pattern, replacement in PII_PATTERNS:
        text = pattern.sub(replacement, text)
    if STACK_TRACE_MARKER.search(text):
        return "An internal error occurred. Contact support with the trace_id."
    return text


class CorrelationIdMiddleware(BaseHTTPMiddleware):
    """Accept or mint a trace ID and expose it on request.state + response."""

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        incoming = request.headers.get(TRACE_HEADER, "")
        # Accept only safe trace IDs: bounded length, no control chars.
        trace_id = incoming if re.fullmatch(r"[\w\-]{1,64}", incoming) else str(uuid.uuid4())
        request.state.trace_id = trace_id
        response = await call_next(request)
        response.headers[TRACE_HEADER] = trace_id
        return response


class ProblemRedactionMiddleware(BaseHTTPMiddleware):
    """Last line of defense: scrub every problem+json body before it leaves."""

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        response = await call_next(request)
        content_type = response.headers.get("content-type", "")
        if not content_type.startswith(PROBLEM_MEDIA_TYPE):
            return response

        body = b""
        async for chunk in response.body_iterator:  # type: ignore[attr-defined]
            body += chunk if isinstance(chunk, bytes) else chunk.encode()

        original = body.decode("utf-8", errors="replace")
        cleaned = scrub(original)
        if cleaned != original:
            trace_id = getattr(request.state, "trace_id", "unknown")
            # Server-side keeps the full payload for forensics; client gets scrubbed.
            logger.warning(
                "problem response redacted",
                extra={"trace_id": trace_id, "raw_body": original},
            )
        headers = dict(response.headers)
        headers["content-length"] = str(len(cleaned.encode()))
        return Response(
            content=cleaned,
            status_code=response.status_code,
            headers=headers,
            media_type=PROBLEM_MEDIA_TYPE,
        )
