"""Listing 2 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

import httpx

resp = httpx.post("https://api.example.invalid/shipments", json=payload)
if resp.is_error:
    problem = resp.json() if resp.headers["content-type"].startswith(
        "application/problem+json") else {}
    match problem.get("code"):
        case "NRW-VALIDATION-FAILED":
            fix_fields(problem["errors"])          # JSON Pointers per field
        case "NRW-RATE-LIMIT-EXCEEDED":
            sleep(float(resp.headers["Retry-After"]))
        case _:
            escalate(problem.get("trace_id"))      # never match on "detail"
