"""Listing 3 extracted from chapters/chapter_07_errors_validation_problem_details.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""shipment_models.py -- Strict Pydantic v2 validation showcase.

Listing 7.2. Northwind Robotics "Shipment" resource. Demonstrates strict mode,
field_validator vs model_validator, and Annotated custom types.
"""
from __future__ import annotations

from decimal import Decimal
from typing import Annotated, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

# --- Custom types via Annotated: reusable, composable, self-documenting. ----
Sku = Annotated[
    str,
    StringConstraints(pattern=r"^NRW-[A-Z]{2}-\d{4}$", min_length=11, max_length=11),
]
CountryCode = Annotated[str, StringConstraints(pattern=r"^[A-Z]{2}$")]


class Address(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    street: str = Field(min_length=1, max_length=120)
    city: str = Field(min_length=1, max_length=60)
    country: CountryCode


class PackageLine(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    sku: Sku
    quantity: int = Field(ge=1, le=10_000)
    # Decimal avoids binary float money errors. JSON has no decimal literal,
    # so this field opts OUT of strict mode (strict=False) and is hardened
    # by a validator instead -- blanket strictness breaks legitimate input.
    unit_weight_kg: Decimal = Field(strict=False, gt=Decimal("0"), le=Decimal("500"))

    @field_validator("quantity")
    @classmethod
    def quantity_not_suspiciously_round(cls, value: int) -> int:
        # Business heuristic: quantities over 5000 require explicit review.
        if value > 5000:
            raise ValueError("quantity above 5000 requires manual review")
        return value

    @field_validator("unit_weight_kg")
    @classmethod
    def weight_is_finite(cls, value: Decimal) -> Decimal:
        if not value.is_finite():
            raise ValueError("unit_weight_kg must be a finite number")
        return value.quantize(Decimal("0.001"))


class Shipment(BaseModel):
    """Strict at the boundary: no silent coercion, no unknown fields."""

    model_config = ConfigDict(strict=True, extra="forbid")

    shipment_id: Optional[str] = Field(default=None, pattern=r"^shp_\d{8}$")
    destination: Address
    lines: list[PackageLine] = Field(min_length=1)
    priority: str = Field(default="standard")

    @field_validator("priority")
    @classmethod
    def priority_is_known(cls, value: str) -> str:
        allowed = {"standard", "express", "freight"}
        if value not in allowed:
            raise ValueError(f"priority must be one of {sorted(allowed)}")
        return value

    @model_validator(mode="after")
    def express_shipments_stay_light(self) -> "Shipment":
        # Cross-field invariant: express parcels cannot exceed 30 kg total.
        if self.priority == "express":
            total = sum(
                line.unit_weight_kg * line.quantity for line in self.lines
            )
            if total > Decimal("30"):
                raise ValueError(
                    f"express shipments must weigh <= 30 kg, got {total} kg"
                )
        return self


def demo_coercion_pitfall() -> dict[str, str]:
    """Show why lax mode is dangerous at the API boundary."""
    outcome: dict[str, str] = {}

    class LaxPackage(BaseModel):  # default: lax coercion
        quantity: int

    coerced = LaxPackage(quantity="12")  # type: ignore[arg-type]
    outcome["lax_accepts_string"] = f"{coerced.quantity!r} (silently coerced)"

    try:
        PackageLine(sku="NRW-AR-1001", quantity="12", unit_weight_kg=Decimal("1.0"))  # type: ignore[arg-type]
    except Exception as exc:
        first = str(exc).splitlines()[0]
        outcome["strict_rejects_string"] = first
    return outcome


if __name__ == "__main__":
    for key, value in demo_coercion_pitfall().items():
        print(f"{key}: {value}")
