"""Listing 2 extracted from chapters/chapter_05_client_side_security.tex.

Auto-generated by tools/extract_code.py -- do not edit here.
"""

"""Listing 5.2 -- Complete OAuth 2.0 Authorization Code + PKCE flow, offline.

A stdlib-only, fully local demonstration:
  * ``StubIdP``  -- an in-memory authorization server (authorize + token
    endpoints) implementing PKCE verification, refresh-token rotation, and
    reuse detection, per RFC 6749 / RFC 7636 semantics.
  * ``PkceClient`` -- a public client that generates a code_verifier /
    code_challenge (S256), obtains a code, exchanges it, and refreshes.

Deterministic: the verifier and codes come from a seeded PRNG. In
production, use ``secrets.token_urlsafe`` instead of ``random.Random``.

All identifiers are synthetic fixtures for the fictional Northwind Robotics
universe. No real network is used: the server binds to the loopback
interface on an ephemeral port.
"""

from __future__ import annotations

import base64
import hashlib
import json
import random
import threading
import urllib.parse
import urllib.request
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, HTTPServer

CLIENT_ID = "nwr-parts-cli"
REDIRECT_URI = "http://127.0.0.1/callback"
VERIFIER_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"


def s256_challenge(verifier: str) -> str:
    """RFC 7636 S256: BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))."""
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def make_verifier(rng: random.Random, length: int = 64) -> str:
    """RFC 7636: 43-128 chars from the unreserved set. Use secrets in prod."""
    if not 43 <= length <= 128:
        raise ValueError("code_verifier length must be in [43, 128]")
    return "".join(rng.choice(VERIFIER_ALPHABET) for _ in range(length))


@dataclass
class PendingGrant:
    challenge: str
    method: str


class StubIdP:
    """In-memory authorization-server state shared by the HTTP handler."""

    def __init__(self, seed: int = 20260301) -> None:
        self._rng = random.Random(seed)
        self._grants: dict[str, PendingGrant] = {}
        self._active: dict[str, str] = {}   # refresh_token -> family id
        self._retired: dict[str, str] = {}  # rotated-out token -> family id
        self._counter = 0

    def _mint(self, prefix: str) -> str:
        self._counter += 1
        return f"{prefix}-{self._counter:04d}-nwr-synthetic"

    def create_grant(self, challenge: str, method: str) -> str:
        code = self._mint("code")
        self._grants[code] = PendingGrant(challenge=challenge, method=method)
        return code

    def exchange_code(self, code: str, verifier: str) -> dict[str, object]:
        grant = self._grants.pop(code, None)  # one-time use
        if grant is None:
            raise PermissionError("invalid_grant: unknown or reused code")
        if grant.method != "S256" or s256_challenge(verifier) != grant.challenge:
            raise PermissionError("invalid_grant: PKCE verification failed")
        return self._issue_tokens(family=self._mint("fam"))

    def refresh(self, refresh_token: str) -> dict[str, object]:
        if refresh_token in self._retired:
            # Reuse of an already-rotated token == theft signal:
            # revoke the ENTIRE token family (RFC 6749 section 10.4 pattern).
            family = self._retired[refresh_token]
            self._active = {t: f for t, f in self._active.items() if f != family}
            raise PermissionError("invalid_grant: refresh token reuse detected; family revoked")
        family = self._active.pop(refresh_token, None)
        if family is None:
            raise PermissionError("invalid_grant: unknown refresh token")
        self._retired[refresh_token] = family  # rotate: old token retires
        return self._issue_tokens(family=family)

    def _issue_tokens(self, family: str) -> dict[str, object]:
        refresh = self._mint("rt")
        self._active[refresh] = family
        return {
            "access_token": self._mint("at"),
            "token_type": "Bearer",
            "expires_in": 300,
            "refresh_token": refresh,
        }


class IdPHandler(BaseHTTPRequestHandler):
    idp: StubIdP  # injected by make_server()

    def do_GET(self) -> None:  # noqa: N802 -- /authorize
        params = urllib.parse.parse_qs(urllib.parse.urlsplit(self.path).query)
        try:
            if not self.path.startswith("/authorize"):
                raise ValueError("unknown endpoint")
            if params["client_id"][0] != CLIENT_ID:
                raise PermissionError("unauthorized_client")
            if params.get("code_challenge_method", [""])[0] != "S256":
                raise PermissionError("invalid_request: only S256 is accepted")
            code = self.idp.create_grant(params["code_challenge"][0], "S256")
            location = REDIRECT_URI + "?" + urllib.parse.urlencode(
                {"code": code, "state": params["state"][0]}
            )
            self.send_response(302)
            self.send_header("Location", location)
            self.end_headers()
        except (KeyError, ValueError, PermissionError) as exc:
            self._json(400, {"error": str(exc)})

    def do_POST(self) -> None:  # noqa: N802 -- /token
        length = int(self.headers.get("Content-Length", "0"))
        form = urllib.parse.parse_qs(self.rfile.read(length).decode("utf-8"))
        try:
            if not self.path.startswith("/token"):
                raise ValueError("unknown endpoint")
            grant_type = form["grant_type"][0]
            if grant_type == "authorization_code":
                tokens = self.idp.exchange_code(form["code"][0], form["code_verifier"][0])
            elif grant_type == "refresh_token":
                tokens = self.idp.refresh(form["refresh_token"][0])
            else:
                raise ValueError(f"unsupported_grant_type: {grant_type}")
            self._json(200, tokens)
        except (KeyError, ValueError) as exc:
            self._json(400, {"error": str(exc)})
        except PermissionError as exc:
            self._json(403, {"error": str(exc)})

    def _json(self, status: int, body: dict[str, object]) -> None:
        data = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, format: str, *args: object) -> None:
        pass


class PkceClient:
    def __init__(self, base_url: str, rng: random.Random) -> None:
        self.base_url = base_url
        self.rng = rng

    def _post_form(self, path: str, fields: dict[str, str]) -> dict[str, object]:
        req = urllib.request.Request(
            self.base_url + path,
            data=urllib.parse.urlencode(fields).encode("utf-8"),
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            raise PermissionError(exc.read().decode("utf-8")) from exc

    def authorize_and_exchange(self) -> dict[str, object]:
        verifier = make_verifier(self.rng)
        params = {
            "response_type": "code",
            "client_id": CLIENT_ID,
            "redirect_uri": REDIRECT_URI,
            "scope": "parts:read",
            "state": make_verifier(self.rng, 43),
            "code_challenge": s256_challenge(verifier),
            "code_challenge_method": "S256",
        }
        # A real CLI opens the system browser here; we follow the 302 locally.
        url = self.base_url + "/authorize?" + urllib.parse.urlencode(params)
        opener = urllib.request.build_opener(NoRedirect())
        try:
            opener.open(url)
            raise RuntimeError("authorize endpoint must answer 302, not 200")
        except urllib.error.HTTPError as exc:
            if exc.code != 302:
                raise
            location = exc.headers["Location"]
        query = urllib.parse.parse_qs(urllib.parse.urlsplit(location).query)
        if query["state"][0] != params["state"]:
            raise PermissionError("state mismatch: possible CSRF")
        return self._post_form(
            "/token",
            {
                "grant_type": "authorization_code",
                "code": query["code"][0],
                "redirect_uri": REDIRECT_URI,
                "client_id": CLIENT_ID,
                "code_verifier": verifier,
            },
        )

    def refresh(self, refresh_token: str) -> dict[str, object]:
        return self._post_form(
            "/token",
            {"grant_type": "refresh_token", "refresh_token": refresh_token,
             "client_id": CLIENT_ID},
        )


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):  # type: ignore[override]
        return None


def main() -> None:
    idp = StubIdP(seed=20260301)
    handler = type("BoundIdPHandler", (IdPHandler,), {"idp": idp})
    server = HTTPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    client = PkceClient(f"http://127.0.0.1:{server.server_address[1]}",
                        random.Random(42))
    try:
        tokens = client.authorize_and_exchange()
        print(f"[1] code exchanged        -> access={tokens['access_token']} "
              f"refresh={tokens['refresh_token']}")

        rotated = client.refresh(str(tokens["refresh_token"]))
        print(f"[2] refresh rotated       -> access={rotated['access_token']} "
              f"refresh={rotated['refresh_token']}")

        try:
            client.refresh(str(tokens["refresh_token"]))  # replay old token
        except PermissionError as exc:
            print(f"[3] reuse of old refresh  -> REJECTED: {json.loads(exc.args[0])['error']}")
        try:
            client.refresh(str(rotated["refresh_token"]))  # family was revoked
        except PermissionError as exc:
            print(f"[4] family after reuse    -> REVOKED: {json.loads(exc.args[0])['error']}")
    finally:
        server.shutdown()


if __name__ == "__main__":
    main()
